select
`SOURCE_DATABASE` as source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        TRY_CAST(`Order-Num` AS DECIMAL(18,0)) as order_num,
        NULLIF(TRIM(`Order-NumCV`), '') as order_numcv,
        NULLIF(TRIM(`Cust-Key`), '') as cust_key,
        CAST(TRY_TO_TIMESTAMP(`Order-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as order_date,
        NULLIF(TRIM(`Sales-Agent-ID`), '') as sales_agent_id,
        NULLIF(TRIM(`Sales-Agent-First-Name`), '') as sales_agent_first_name,
        NULLIF(TRIM(`Sales-Agent-Middle-Name`), '') as sales_agent_middle_name,
        NULLIF(TRIM(`Sales-Agent-Last-Name`), '') as sales_agent_last_name,
        NULLIF(TRIM(`Sales-Agent-SS-Num`), '') as sales_agent_ss_num,
        NULLIF(TRIM(`Sales-Agent-Other-ID`), '') as sales_agent_other_id,
        NULLIF(TRIM(`Cancel-by`), '') as cancel_by,
        CAST(TRY_TO_TIMESTAMP(`Cancel-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cancel_date,
        NULLIF(TRIM(`Cancel-time`), '') as cancel_time,
        NULLIF(TRIM(`Cancel-Reason`), '') as cancel_reason,
        NULLIF(TRIM(`Shipto-Attention`), '') as shipto_attention,
        TRY_CAST(`Shipto-Seq-Num` AS DECIMAL(18,0)) as shipto_seq_num,
        NULLIF(TRIM(`Shipto-Name`), '') as shipto_name,
        NULLIF(TRIM(`Shipto-Address-1`), '') as shipto_address_1,
        NULLIF(TRIM(`Shipto-Address-2`), '') as shipto_address_2,
        NULLIF(TRIM(`Shipto-Address-3`), '') as shipto_address_3,
        NULLIF(TRIM(`Shipto-City`), '') as shipto_city,
        NULLIF(TRIM(`Shipto-State`), '') as shipto_state,
        NULLIF(TRIM(`Shipto-Zip`), '') as shipto_zip,
        NULLIF(TRIM(`Shipto-Country`), '') as shipto_country,
        NULLIF(TRIM(`Shipto-Warehouse`), '') as shipto_warehouse,
        NULLIF(TRIM(`Shipper-ID`), '') as shipper_id,
        NULLIF(TRIM(`Ship-Mode`), '') as ship_mode,
        NULLIF(TRIM(`Ship-Route`), '') as ship_route,
        NULLIF(TRIM(`Order-Terms-Key`), '') as order_terms_key,
        NULLIF(TRIM(`Order-Terms-Code`), '') as order_terms_code,
        NULLIF(TRIM(`Customer-PO-Num`), '') as customer_po_num,
        CAST(TRY_TO_TIMESTAMP(`Ship-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as ship_date,
        TRY_CAST(`Print-Count` AS DECIMAL(18,0)) as print_count,
        NULLIF(TRIM(`FOB-Remark`), '') as fob_remark,
        NULLIF(TRIM(`Requisition-Num`), '') as requisition_num,
        NULLIF(TRIM(`Order-Currency`), '') as order_currency,
        NULLIF(TRIM(`Pick-Status`), '') as pick_status,
        TRY_CAST(`Pick-Print-Count` AS DECIMAL(18,0)) as pick_print_count,
        IF(UPPER(TRIM(`Warehouse-Transfer`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Warehouse-Transfer`))='FALSE', FALSE, NULL)) as is_warehouse_transfer,
        NULLIF(TRIM(`Transfer-CC-to-Warehouse`), '') as transfer_cc_to_warehouse,
        TRY_CAST(`Net-Days-to-Age-Due-Date` AS DECIMAL(18,0)) as net_days_to_age_due_date,
        IF(UPPER(TRIM(`Order-On-Hold`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Order-On-Hold`))='FALSE', FALSE, NULL)) as is_order_on_hold,
        NULLIF(TRIM(`Default-Ship-From-Warehouse`), '') as default_ship_from_warehouse,
        NULLIF(TRIM(`Default-Order-Type`), '') as default_order_type,
        CAST(TRY_TO_TIMESTAMP(`Delivery-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as delivery_date,
        NULLIF(TRIM(`Delivery-Type`), '') as delivery_type,
        NULLIF(TRIM(`Supplier-Key`), '') as supplier_key,
        TRY_CAST(`Supplier-Ship-From-Seq-Num` AS DECIMAL(18,0)) as supplier_ship_from_seq_num,
        TRY_CAST(`Internal-Key` AS DECIMAL(18,0)) as internal_key,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Update-Date-Time`), '') as update_date_time,
        NULLIF(TRIM(`Origin`), '') as origin,
        TRY_CAST(`Drop-Ship-Cust-Shipto-Seq-Num` AS DECIMAL(18,0)) as drop_ship_cust_shipto_seq_num,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-Name`), '') as drop_ship_shipfrom_name,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-Address-1`), '') as drop_ship_shipfrom_address_1,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-Address-2`), '') as drop_ship_shipfrom_address_2,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-Address-3`), '') as drop_ship_shipfrom_address_3,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-City`), '') as drop_ship_shipfrom_city,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-State`), '') as drop_ship_shipfrom_state,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-Zip`), '') as drop_ship_shipfrom_zip,
        NULLIF(TRIM(`Drop-Ship-Shipfrom-Country`), '') as drop_ship_shipfrom_country,
        NULLIF(TRIM(`Order-Status`), '') as order_status,
        IF(UPPER(TRIM(`Cancelled`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Cancelled`))='FALSE', FALSE, NULL)) as is_cancelled,
        IF(UPPER(TRIM(`Closed`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Closed`))='FALSE', FALSE, NULL)) as is_closed,
        NULLIF(TRIM(`Freight-Terms`), '') as freight_terms,
        NULLIF(TRIM(`Letter-of-Credit`), '') as letter_of_credit,
        NULLIF(TRIM(`Cancel-Code`), '') as cancel_code,
        NULLIF(TRIM(`Misc-Description@1`), '') as misc_description_1,
        NULLIF(TRIM(`Misc-Description@2`), '') as misc_description_2,
        NULLIF(TRIM(`Misc-Description@3`), '') as misc_description_3,
        NULLIF(TRIM(`Misc-Description@4`), '') as misc_description_4,
        NULLIF(TRIM(`Misc-Description@5`), '') as misc_description_5,
        NULLIF(TRIM(`Misc-Description@6`), '') as misc_description_6,
        NULLIF(TRIM(`Misc-Description@7`), '') as misc_description_7,
        NULLIF(TRIM(`Misc-Description@8`), '') as misc_description_8,
        NULLIF(TRIM(`Misc-Description@9`), '') as misc_description_9,
        NULLIF(TRIM(`Misc-Description@10`), '') as misc_description_10,
        TRY_CAST(`Misc-Amount@1` AS DECIMAL(38,2)) as misc_amount_1,
        TRY_CAST(`Misc-Amount@2` AS DECIMAL(38,2)) as misc_amount_2,
        TRY_CAST(`Misc-Amount@3` AS DECIMAL(38,2)) as misc_amount_3,
        TRY_CAST(`Misc-Amount@4` AS DECIMAL(38,2)) as misc_amount_4,
        TRY_CAST(`Misc-Amount@5` AS DECIMAL(38,2)) as misc_amount_5,
        TRY_CAST(`Misc-Amount@6` AS DECIMAL(38,2)) as misc_amount_6,
        TRY_CAST(`Misc-Amount@7` AS DECIMAL(38,2)) as misc_amount_7,
        TRY_CAST(`Misc-Amount@8` AS DECIMAL(38,2)) as misc_amount_8,
        TRY_CAST(`Misc-Amount@9` AS DECIMAL(38,2)) as misc_amount_9,
        TRY_CAST(`Misc-Amount@10` AS DECIMAL(38,2)) as misc_amount_10,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@1`), '') as misc_gl_acct_ptr_1,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@2`), '') as misc_gl_acct_ptr_2,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@3`), '') as misc_gl_acct_ptr_3,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@4`), '') as misc_gl_acct_ptr_4,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@5`), '') as misc_gl_acct_ptr_5,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@6`), '') as misc_gl_acct_ptr_6,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@7`), '') as misc_gl_acct_ptr_7,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@8`), '') as misc_gl_acct_ptr_8,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@9`), '') as misc_gl_acct_ptr_9,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@10`), '') as misc_gl_acct_ptr_10,
        NULLIF(TRIM(`Pallet-Product-Key`), '') as pallet_product_key,
        NULLIF(TRIM(`Pallet-Packaging-Key`), '') as pallet_packaging_key,
        TRY_CAST(`Pallet-Num` AS DECIMAL(18,0)) as pallet_num,
        NULLIF(TRIM(`Cust-ID`), '') as cust_id,
        NULLIF(TRIM(`Sales-Tax-Code`), '') as sales_tax_code,
        TRY_CAST(`Order-Open-Amount` AS DECIMAL(38,2)) as order_open_amount,
        CAST(TRY_TO_TIMESTAMP(`Last-Evaluation-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_evaluation_date,
        NULLIF(TRIM(`Last-Evaluation-By`), '') as last_evaluation_by,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@1`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@1`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_1,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@2`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@2`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_2,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@3`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@3`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_3,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@4`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@4`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_4,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@5`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@5`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_5,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@6`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@6`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_6,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@7`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@7`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_7,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@8`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@8`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_8,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@9`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@9`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_9,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@10`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Taxable@10`))='FALSE', FALSE, NULL)) as is_misc_sales_taxable_10,
        NULLIF(TRIM(`WT-To-Warehouse`), '') as wt_to_warehouse,
        TRY_CAST(`Freight-Cost` AS DECIMAL(38,2)) as freight_cost,
        TRY_CAST(`E-Tracking-Num` AS DECIMAL(18,0)) as e_tracking_num,
        NULLIF(TRIM(`E-Tracking-NumCV`), '') as e_tracking_numcv,
        NULLIF(TRIM(`Delivery-Time`), '') as delivery_time,
        NULLIF(TRIM(`User-2`), '') as user_2,
        NULLIF(TRIM(`Delivery-Date-Time`), '') as delivery_date_time,
        NULLIF(TRIM(`Ship-Date-Comment`), '') as ship_date_comment,
        NULLIF(TRIM(`Security-Access-2`), '') as security_access_2,
        NULLIF(TRIM(`Image-File`), '') as image_file,
        NULLIF(TRIM(`Contact-Name`), '') as contact_name,
        NULLIF(TRIM(`Inactivity-Hold-Update-By`), '') as inactivity_hold_update_by,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`Pallet-Weight-Total` AS DECIMAL(18,2)) as pallet_weight_total,
        TRY_CAST(`Payment-Amount` AS DECIMAL(38,2)) as payment_amount,
        IF(UPPER(TRIM(`Requires-Palletization`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Requires-Palletization`))='FALSE', FALSE, NULL)) as is_requires_palletization,
        IF(UPPER(TRIM(`Collect-Payment-Now`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Collect-Payment-Now`))='FALSE', FALSE, NULL)) as is_collect_payment_now,
        TRY_CAST(`Pallet-Total-Num` AS DECIMAL(18,0)) as pallet_total_num,
        TRY_CAST(`Spare-Integer-2` AS DECIMAL(18,0)) as spare_integer_2,
        TRY_CAST(`Blanket-Order-Num` AS DECIMAL(18,0)) as blanket_order_num,
        NULLIF(TRIM(`Created-Date-Time`), '') as created_date_time,
        NULLIF(TRIM(`DNU-Hold-Reason`), '') as dnu_hold_reason,
        IF(UPPER(TRIM(`DNU-Pre-Release-Cr-Hold`))='TRUE', TRUE,
      IF(UPPER(TRIM(`DNU-Pre-Release-Cr-Hold`))='FALSE', FALSE, NULL)) as is_dnu_pre_release_cr_hold,
        NULLIF(TRIM(`Sales-Agent-ID-2`), '') as sales_agent_id_2,
        NULLIF(TRIM(`Sales-Agent-First-Name-2`), '') as sales_agent_first_name_2,
        NULLIF(TRIM(`Sales-Agent-Middle-Name-2`), '') as sales_agent_middle_name_2,
        NULLIF(TRIM(`Sales-Agent-Last-Name-2`), '') as sales_agent_last_name_2,
        NULLIF(TRIM(`Sales-Agent-SS-Num-2`), '') as sales_agent_ss_num_2,
        NULLIF(TRIM(`Sales-Agent-Other-ID-2`), '') as sales_agent_other_id_2,
        NULLIF(TRIM(`Shipto-Phone`), '') as shipto_phone,
        NULLIF(TRIM(`Shipto-Fax`), '') as shipto_fax,
        NULLIF(TRIM(`Credit-Hold-Update-By`), '') as credit_hold_update_by,
        NULLIF(TRIM(`Freight-Remark`), '') as freight_remark,
        TRY_CAST(`Misc-Percent@1` AS DECIMAL(9,2)) as misc_percent_1,
        TRY_CAST(`Misc-Percent@2` AS DECIMAL(9,2)) as misc_percent_2,
        TRY_CAST(`Misc-Percent@3` AS DECIMAL(9,2)) as misc_percent_3,
        TRY_CAST(`Misc-Percent@4` AS DECIMAL(9,2)) as misc_percent_4,
        TRY_CAST(`Misc-Percent@5` AS DECIMAL(9,2)) as misc_percent_5,
        TRY_CAST(`Misc-Percent@6` AS DECIMAL(9,2)) as misc_percent_6,
        TRY_CAST(`Misc-Percent@7` AS DECIMAL(9,2)) as misc_percent_7,
        TRY_CAST(`Misc-Percent@8` AS DECIMAL(9,2)) as misc_percent_8,
        TRY_CAST(`Misc-Percent@9` AS DECIMAL(9,2)) as misc_percent_9,
        TRY_CAST(`Misc-Percent@10` AS DECIMAL(9,2)) as misc_percent_10,
        TRY_CAST(`Misc-Min-Percent-Amount@1` AS DECIMAL(38,2)) as misc_min_percent_amount_1,
        TRY_CAST(`Misc-Min-Percent-Amount@2` AS DECIMAL(38,2)) as misc_min_percent_amount_2,
        TRY_CAST(`Misc-Min-Percent-Amount@3` AS DECIMAL(38,2)) as misc_min_percent_amount_3,
        TRY_CAST(`Misc-Min-Percent-Amount@4` AS DECIMAL(38,2)) as misc_min_percent_amount_4,
        TRY_CAST(`Misc-Min-Percent-Amount@5` AS DECIMAL(38,2)) as misc_min_percent_amount_5,
        TRY_CAST(`Misc-Min-Percent-Amount@6` AS DECIMAL(38,2)) as misc_min_percent_amount_6,
        TRY_CAST(`Misc-Min-Percent-Amount@7` AS DECIMAL(38,2)) as misc_min_percent_amount_7,
        TRY_CAST(`Misc-Min-Percent-Amount@8` AS DECIMAL(38,2)) as misc_min_percent_amount_8,
        TRY_CAST(`Misc-Min-Percent-Amount@9` AS DECIMAL(38,2)) as misc_min_percent_amount_9,
        TRY_CAST(`Misc-Min-Percent-Amount@10` AS DECIMAL(38,2)) as misc_min_percent_amount_10,
        TRY_CAST(`Misc-Max-Percent-Amount@1` AS DECIMAL(38,2)) as misc_max_percent_amount_1,
        TRY_CAST(`Misc-Max-Percent-Amount@2` AS DECIMAL(38,2)) as misc_max_percent_amount_2,
        TRY_CAST(`Misc-Max-Percent-Amount@3` AS DECIMAL(38,2)) as misc_max_percent_amount_3,
        TRY_CAST(`Misc-Max-Percent-Amount@4` AS DECIMAL(38,2)) as misc_max_percent_amount_4,
        TRY_CAST(`Misc-Max-Percent-Amount@5` AS DECIMAL(38,2)) as misc_max_percent_amount_5,
        TRY_CAST(`Misc-Max-Percent-Amount@6` AS DECIMAL(38,2)) as misc_max_percent_amount_6,
        TRY_CAST(`Misc-Max-Percent-Amount@7` AS DECIMAL(38,2)) as misc_max_percent_amount_7,
        TRY_CAST(`Misc-Max-Percent-Amount@8` AS DECIMAL(38,2)) as misc_max_percent_amount_8,
        TRY_CAST(`Misc-Max-Percent-Amount@9` AS DECIMAL(38,2)) as misc_max_percent_amount_9,
        TRY_CAST(`Misc-Max-Percent-Amount@10` AS DECIMAL(38,2)) as misc_max_percent_amount_10,
        NULLIF(TRIM(`Profit-Hold-Update-By`), '') as profit_hold_update_by,
        TRY_CAST(`Freight-Charge` AS DECIMAL(38,2)) as freight_charge,
        NULLIF(TRIM(`Ship-Time`), '') as ship_time,
        CAST(TRY_TO_TIMESTAMP(`Cust-Requested-Del-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cust_requested_del_date,
        NULLIF(TRIM(`Cust-Requested-Del-Window`), '') as cust_requested_del_window,
        NULLIF(TRIM(`Logistics-Carrier`), '') as logistics_carrier,
        NULLIF(TRIM(`Logistics-ID`), '') as logistics_id,
        CAST(TRY_TO_TIMESTAMP(`Market-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as market_date,
        TRY_CAST(`Misc-Cost-Amount@1` AS DECIMAL(38,2)) as misc_cost_amount_1,
        TRY_CAST(`Misc-Cost-Amount@2` AS DECIMAL(38,2)) as misc_cost_amount_2,
        TRY_CAST(`Misc-Cost-Amount@3` AS DECIMAL(38,2)) as misc_cost_amount_3,
        TRY_CAST(`Misc-Cost-Amount@4` AS DECIMAL(38,2)) as misc_cost_amount_4,
        TRY_CAST(`Misc-Cost-Amount@5` AS DECIMAL(38,2)) as misc_cost_amount_5,
        TRY_CAST(`Misc-Cost-Amount@6` AS DECIMAL(38,2)) as misc_cost_amount_6,
        TRY_CAST(`Misc-Cost-Amount@7` AS DECIMAL(38,2)) as misc_cost_amount_7,
        TRY_CAST(`Misc-Cost-Amount@8` AS DECIMAL(38,2)) as misc_cost_amount_8,
        TRY_CAST(`Misc-Cost-Amount@9` AS DECIMAL(38,2)) as misc_cost_amount_9,
        TRY_CAST(`Misc-Cost-Amount@10` AS DECIMAL(38,2)) as misc_cost_amount_10,
        TRY_CAST(`Misc-Cost-Percent@1` AS DECIMAL(9,2)) as misc_cost_percent_1,
        TRY_CAST(`Misc-Cost-Percent@2` AS DECIMAL(9,2)) as misc_cost_percent_2,
        TRY_CAST(`Misc-Cost-Percent@3` AS DECIMAL(9,2)) as misc_cost_percent_3,
        TRY_CAST(`Misc-Cost-Percent@4` AS DECIMAL(9,2)) as misc_cost_percent_4,
        TRY_CAST(`Misc-Cost-Percent@5` AS DECIMAL(9,2)) as misc_cost_percent_5,
        TRY_CAST(`Misc-Cost-Percent@6` AS DECIMAL(9,2)) as misc_cost_percent_6,
        TRY_CAST(`Misc-Cost-Percent@7` AS DECIMAL(9,2)) as misc_cost_percent_7,
        TRY_CAST(`Misc-Cost-Percent@8` AS DECIMAL(9,2)) as misc_cost_percent_8,
        TRY_CAST(`Misc-Cost-Percent@9` AS DECIMAL(9,2)) as misc_cost_percent_9,
        TRY_CAST(`Misc-Cost-Percent@10` AS DECIMAL(9,2)) as misc_cost_percent_10,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@1` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_1,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@2` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_2,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@3` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_3,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@4` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_4,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@5` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_5,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@6` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_6,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@7` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_7,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@8` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_8,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@9` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_9,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@10` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_10,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@1` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_1,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@2` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_2,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@3` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_3,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@4` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_4,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@5` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_5,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@6` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_6,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@7` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_7,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@8` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_8,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@9` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_9,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@10` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_10,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@1`), '') as misc_cost_gl_acct_ptr_1,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@2`), '') as misc_cost_gl_acct_ptr_2,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@3`), '') as misc_cost_gl_acct_ptr_3,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@4`), '') as misc_cost_gl_acct_ptr_4,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@5`), '') as misc_cost_gl_acct_ptr_5,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@6`), '') as misc_cost_gl_acct_ptr_6,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@7`), '') as misc_cost_gl_acct_ptr_7,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@8`), '') as misc_cost_gl_acct_ptr_8,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@9`), '') as misc_cost_gl_acct_ptr_9,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@10`), '') as misc_cost_gl_acct_ptr_10,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@1`), '') as misc_cogs_gl_acct_ptr_1,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@2`), '') as misc_cogs_gl_acct_ptr_2,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@3`), '') as misc_cogs_gl_acct_ptr_3,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@4`), '') as misc_cogs_gl_acct_ptr_4,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@5`), '') as misc_cogs_gl_acct_ptr_5,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@6`), '') as misc_cogs_gl_acct_ptr_6,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@7`), '') as misc_cogs_gl_acct_ptr_7,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@8`), '') as misc_cogs_gl_acct_ptr_8,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@9`), '') as misc_cogs_gl_acct_ptr_9,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@10`), '') as misc_cogs_gl_acct_ptr_10,
        IF(UPPER(TRIM(`Temporary-ShipTo-Address`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Temporary-ShipTo-Address`))='FALSE', FALSE, NULL)) as is_temporary_shipto_address,
        NULLIF(TRIM(`Tracking-Num`), '') as tracking_num,
        NULLIF(TRIM(`Assigned-Picker-User-ID`), '') as assigned_picker_user_id,
        NULLIF(TRIM(`Shipment-Status`), '') as shipment_status,
        TRY_CAST(`Misc-Charge-Threshold@1` AS DECIMAL(38,2)) as misc_charge_threshold_1,
        TRY_CAST(`Misc-Charge-Threshold@2` AS DECIMAL(38,2)) as misc_charge_threshold_2,
        TRY_CAST(`Misc-Charge-Threshold@3` AS DECIMAL(38,2)) as misc_charge_threshold_3,
        TRY_CAST(`Misc-Charge-Threshold@4` AS DECIMAL(38,2)) as misc_charge_threshold_4,
        TRY_CAST(`Misc-Charge-Threshold@5` AS DECIMAL(38,2)) as misc_charge_threshold_5,
        TRY_CAST(`Misc-Charge-Threshold@6` AS DECIMAL(38,2)) as misc_charge_threshold_6,
        TRY_CAST(`Misc-Charge-Threshold@7` AS DECIMAL(38,2)) as misc_charge_threshold_7,
        TRY_CAST(`Misc-Charge-Threshold@8` AS DECIMAL(38,2)) as misc_charge_threshold_8,
        TRY_CAST(`Misc-Charge-Threshold@9` AS DECIMAL(38,2)) as misc_charge_threshold_9,
        TRY_CAST(`Misc-Charge-Threshold@10` AS DECIMAL(38,2)) as misc_charge_threshold_10,
        TRY_CAST(`Misc-Charge-Threshold-Amount@1` AS DECIMAL(38,2)) as misc_charge_threshold_amount_1,
        TRY_CAST(`Misc-Charge-Threshold-Amount@2` AS DECIMAL(38,2)) as misc_charge_threshold_amount_2,
        TRY_CAST(`Misc-Charge-Threshold-Amount@3` AS DECIMAL(38,2)) as misc_charge_threshold_amount_3,
        TRY_CAST(`Misc-Charge-Threshold-Amount@4` AS DECIMAL(38,2)) as misc_charge_threshold_amount_4,
        TRY_CAST(`Misc-Charge-Threshold-Amount@5` AS DECIMAL(38,2)) as misc_charge_threshold_amount_5,
        TRY_CAST(`Misc-Charge-Threshold-Amount@6` AS DECIMAL(38,2)) as misc_charge_threshold_amount_6,
        TRY_CAST(`Misc-Charge-Threshold-Amount@7` AS DECIMAL(38,2)) as misc_charge_threshold_amount_7,
        TRY_CAST(`Misc-Charge-Threshold-Amount@8` AS DECIMAL(38,2)) as misc_charge_threshold_amount_8,
        TRY_CAST(`Misc-Charge-Threshold-Amount@9` AS DECIMAL(38,2)) as misc_charge_threshold_amount_9,
        TRY_CAST(`Misc-Charge-Threshold-Amount@10` AS DECIMAL(38,2)) as misc_charge_threshold_amount_10,
        NULLIF(TRIM(`Misc-Shipment-Charge@1`), '') as misc_shipment_charge_1,
        NULLIF(TRIM(`Misc-Shipment-Charge@2`), '') as misc_shipment_charge_2,
        NULLIF(TRIM(`Misc-Shipment-Charge@3`), '') as misc_shipment_charge_3,
        NULLIF(TRIM(`Misc-Shipment-Charge@4`), '') as misc_shipment_charge_4,
        NULLIF(TRIM(`Misc-Shipment-Charge@5`), '') as misc_shipment_charge_5,
        NULLIF(TRIM(`Misc-Shipment-Charge@6`), '') as misc_shipment_charge_6,
        NULLIF(TRIM(`Misc-Shipment-Charge@7`), '') as misc_shipment_charge_7,
        NULLIF(TRIM(`Misc-Shipment-Charge@8`), '') as misc_shipment_charge_8,
        NULLIF(TRIM(`Misc-Shipment-Charge@9`), '') as misc_shipment_charge_9,
        NULLIF(TRIM(`Misc-Shipment-Charge@10`), '') as misc_shipment_charge_10,
        CAST(TRY_TO_TIMESTAMP(`Confirmed-Delivery-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as confirmed_delivery_date,
        NULLIF(TRIM(`Confirmed-Delivery-Time`), '') as confirmed_delivery_time,
        NULLIF(TRIM(`Confirmed-Delivery-Date-Time`), '') as confirmed_delivery_date_time,
        NULLIF(TRIM(`Originating-Warehouse`), '') as originating_warehouse,
        IF(UPPER(TRIM(`Misc-Perc-Total@1`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@1`))='FALSE', FALSE, NULL)) as is_misc_perc_total_1,
        IF(UPPER(TRIM(`Misc-Perc-Total@2`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@2`))='FALSE', FALSE, NULL)) as is_misc_perc_total_2,
        IF(UPPER(TRIM(`Misc-Perc-Total@3`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@3`))='FALSE', FALSE, NULL)) as is_misc_perc_total_3,
        IF(UPPER(TRIM(`Misc-Perc-Total@4`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@4`))='FALSE', FALSE, NULL)) as is_misc_perc_total_4,
        IF(UPPER(TRIM(`Misc-Perc-Total@5`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@5`))='FALSE', FALSE, NULL)) as is_misc_perc_total_5,
        IF(UPPER(TRIM(`Misc-Perc-Total@6`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@6`))='FALSE', FALSE, NULL)) as is_misc_perc_total_6,
        IF(UPPER(TRIM(`Misc-Perc-Total@7`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@7`))='FALSE', FALSE, NULL)) as is_misc_perc_total_7,
        IF(UPPER(TRIM(`Misc-Perc-Total@8`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@8`))='FALSE', FALSE, NULL)) as is_misc_perc_total_8,
        IF(UPPER(TRIM(`Misc-Perc-Total@9`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@9`))='FALSE', FALSE, NULL)) as is_misc_perc_total_9,
        IF(UPPER(TRIM(`Misc-Perc-Total@10`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Perc-Total@10`))='FALSE', FALSE, NULL)) as is_misc_perc_total_10,
        NULLIF(TRIM(`Tax-Country`), '') as tax_country,
        NULLIF(TRIM(`Tax-State`), '') as tax_state,
        IF(UPPER(TRIM(`Hold-Commission`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Hold-Commission`))='FALSE', FALSE, NULL)) as is_hold_commission,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@1`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@1`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_1,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@2`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@2`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_2,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@3`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@3`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_3,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@4`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@4`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_4,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@5`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@5`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_5,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@6`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@6`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_6,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@7`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@7`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_7,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@8`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@8`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_8,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@9`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@9`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_9,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@10`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@10`))='FALSE', FALSE, NULL)) as is_misc_sales_agent_pay_10,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@1`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@1`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_1,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@2`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@2`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_2,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@3`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@3`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_3,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@4`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@4`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_4,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@5`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@5`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_5,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@6`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@6`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_6,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@7`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@7`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_7,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@8`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@8`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_8,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@9`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@9`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_9,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@10`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@10`))='FALSE', FALSE, NULL)) as is_misc_create_offsetting_ap_10,
        NULLIF(TRIM(`Load-Date-Time`), '') as load_date_time,
        NULLIF(TRIM(`Payment-ID-Num`), '') as payment_id_num,
        NULLIF(TRIM(`Payment-Method`), '') as payment_method,
        NULLIF(TRIM(`Shelf-Life-Level`), '') as shelf_life_level,
        NULLIF(TRIM(`Logistics-System`), '') as logistics_system,
        NULLIF(TRIM(`Copied-From-Details`), '') as copied_from_details,
        IF(UPPER(TRIM(`Counter-Sale`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Counter-Sale`))='FALSE', FALSE, NULL)) as is_counter_sale,
        NULLIF(TRIM(`TA-Order-Num`), '') as ta_order_num,
        NULLIF(TRIM(`Spare-Char-8`), '') as spare_char_8,
        IF(UPPER(TRIM(`Spare-Logical-3`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-3`))='FALSE', FALSE, NULL)) as is_spare_logical_3,
        TRY_CAST(`Spare-Decimal-3` AS DECIMAL(38,10)) as spare_decimal_3,
        TRY_CAST(`Spare-Integer-3` AS DECIMAL(18,0)) as spare_integer_3,
        IF(UPPER(TRIM(`Spare-Logical-4`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-4`))='FALSE', FALSE, NULL)) as is_spare_logical_4,
        IF(UPPER(TRIM(`Spare-Logical-5`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-5`))='FALSE', FALSE, NULL)) as is_spare_logical_5,
        NULLIF(TRIM(`Spare-Char-9`), '') as spare_char_9,
        NULLIF(TRIM(`Spare-Char-10`), '') as spare_char_10,
        TRY_CAST(`Spare-Decimal-4` AS DECIMAL(38,10)) as spare_decimal_4,
        IF(UPPER(TRIM(`Spare-Logical-6`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-6`))='FALSE', FALSE, NULL)) as is_spare_logical_6,
        TRY_CAST(`Spare-Decimal-5` AS DECIMAL(38,10)) as spare_decimal_5,
        NULLIF(TRIM(`Spare-Char-11`), '') as spare_char_11,
        NULLIF(TRIM(`Spare-Char-12`), '') as spare_char_12,
        NULLIF(TRIM(`Spare-Char-13`), '') as spare_char_13,
        NULLIF(TRIM(`Spare-Char-14`), '') as spare_char_14
from {{ source('bronze', 'order_hdr') }}
