with cleaned as (

    select
`SOURCE_DATABASE` as source_database,
        NULLIF(TRIM(`System-id`), '') as system_id,
        NULLIF(TRIM(`Product-name`), '') as product_name,
        NULLIF(TRIM(`Product-code`), '') as product_code,
        NULLIF(TRIM(`Product-division-key`), '') as product_division_key,
        NULLIF(TRIM(`Product-key`), '') as product_key,
        NULLIF(TRIM(`Description`), '') as description,
        NULLIF(TRIM(`Long-description`), '') as long_description,
        NULLIF(TRIM(`DOT-Name`), '') as dot_name,
        NULLIF(TRIM(`Cntns`), '') as cntns,
        NULLIF(TRIM(`Hazard-Text`), '') as hazard_text,
        NULLIF(TRIM(`Product-class-key`), '') as product_class_key,
        TRY_CAST(`Specific-Gravity` AS DECIMAL(18,4)) as specific_gravity,
        NULLIF(TRIM(`Package-Group`), '') as package_group,
        NULLIF(TRIM(`Dft-Packaging-key`), '') as dft_packaging_key,
        NULLIF(TRIM(`Product-Type`), '') as product_type,
        NULLIF(TRIM(`UN-code`), '') as un_code,
        NULLIF(TRIM(`Packaging-Group`), '') as packaging_group,
        NULLIF(TRIM(`Freight-class`), '') as freight_class,
        NULLIF(TRIM(`Freight-note`), '') as freight_note,
        TRY_CAST(`Inv-Amount@1` AS DECIMAL(18,4)) as inv_amount_1,
        TRY_CAST(`Inv-Amount@2` AS DECIMAL(18,4)) as inv_amount_2,
        TRY_CAST(`Inv-Amount@3` AS DECIMAL(18,4)) as inv_amount_3,
        TRY_CAST(`Inv-Amount@4` AS DECIMAL(18,4)) as inv_amount_4,
        TRY_CAST(`Inv-Amount@5` AS DECIMAL(18,4)) as inv_amount_5,
        TRY_CAST(`Inv-Amount@6` AS DECIMAL(18,4)) as inv_amount_6,
        TRY_CAST(`Inv-Amount@7` AS DECIMAL(18,4)) as inv_amount_7,
        TRY_CAST(`Inv-Amount@8` AS DECIMAL(18,4)) as inv_amount_8,
        TRY_CAST(`Inv-Amount@9` AS DECIMAL(18,4)) as inv_amount_9,
        TRY_CAST(`Inv-Amount@10` AS DECIMAL(18,4)) as inv_amount_10,
        NULLIF(TRIM(`Inv-Status@1`), '') as inv_status_1,
        NULLIF(TRIM(`Inv-Status@2`), '') as inv_status_2,
        NULLIF(TRIM(`Inv-Status@3`), '') as inv_status_3,
        NULLIF(TRIM(`Inv-Status@4`), '') as inv_status_4,
        NULLIF(TRIM(`Inv-Status@5`), '') as inv_status_5,
        NULLIF(TRIM(`Inv-Status@6`), '') as inv_status_6,
        NULLIF(TRIM(`Inv-Status@7`), '') as inv_status_7,
        NULLIF(TRIM(`Inv-Status@8`), '') as inv_status_8,
        NULLIF(TRIM(`Inv-Status@9`), '') as inv_status_9,
        NULLIF(TRIM(`Inv-Status@10`), '') as inv_status_10,
        IF(UPPER(TRIM(`Inv-Flag@1`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@1`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_1,
        IF(UPPER(TRIM(`Inv-Flag@2`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@2`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_2,
        IF(UPPER(TRIM(`Inv-Flag@3`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@3`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_3,
        IF(UPPER(TRIM(`Inv-Flag@4`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@4`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_4,
        IF(UPPER(TRIM(`Inv-Flag@5`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@5`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_5,
        IF(UPPER(TRIM(`Inv-Flag@6`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@6`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_6,
        IF(UPPER(TRIM(`Inv-Flag@7`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@7`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_7,
        IF(UPPER(TRIM(`Inv-Flag@8`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@8`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_8,
        IF(UPPER(TRIM(`Inv-Flag@9`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@9`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_9,
        IF(UPPER(TRIM(`Inv-Flag@10`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@10`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_10,
        NULLIF(TRIM(`Unit-of-Meas`), '') as unit_of_meas,
        TRY_CAST(`OH-packages` AS DECIMAL(18,0)) as oh_packages,
        NULLIF(TRIM(`CAS-Number`), '') as cas_number,
        NULLIF(TRIM(`HMIS-Health-Rating`), '') as hmis_health_rating,
        NULLIF(TRIM(`HMIS-Flammability-Rating`), '') as hmis_flammability_rating,
        NULLIF(TRIM(`HMIS-Reactivity-Rating`), '') as hmis_reactivity_rating,
        NULLIF(TRIM(`HMIS-Personal-Protection-Rating`), '') as hmis_personal_protection_rating,
        IF(UPPER(TRIM(`SARA-Pure`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`SARA-Pure`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as sara_pure,
        IF(UPPER(TRIM(`SARA-Mixture`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`SARA-Mixture`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as sara_mixture,
        IF(UPPER(TRIM(`SARA-Solid`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`SARA-Solid`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as sara_solid,
        IF(UPPER(TRIM(`SARA-Liquid`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`SARA-Liquid`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as sara_liquid,
        IF(UPPER(TRIM(`SARA-Gas`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`SARA-Gas`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as sara_gas,
        IF(UPPER(TRIM(`DNU-SARA-Immediate`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`DNU-SARA-Immediate`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as dnu_sara_immediate,
        IF(UPPER(TRIM(`DNU-SARA-Chronic`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`DNU-SARA-Chronic`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as dnu_sara_chronic,
        IF(UPPER(TRIM(`DNU-SARA-Fire`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`DNU-SARA-Fire`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as dnu_sara_fire,
        IF(UPPER(TRIM(`DNU-SARA-Sudden-Pressure`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`DNU-SARA-Sudden-Pressure`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as dnu_sara_sudden_pressure,
        IF(UPPER(TRIM(`DNU-SARA-Reactivity`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`DNU-SARA-Reactivity`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as dnu_sara_reactivity,
        NULLIF(TRIM(`SARA-Storage-Code-Type`), '') as sara_storage_code_type,
        NULLIF(TRIM(`SARA-Storage-Code-Temp`), '') as sara_storage_code_temp,
        NULLIF(TRIM(`SARA-Storage-Code-Pressure`), '') as sara_storage_code_pressure,
        NULLIF(TRIM(`EPA-Waste-Code-1`), '') as epa_waste_code_1,
        NULLIF(TRIM(`EPA-Waste-Code-2`), '') as epa_waste_code_2,
        NULLIF(TRIM(`EPA-Waste-Code-3`), '') as epa_waste_code_3,
        NULLIF(TRIM(`EPA-Waste-Code-4`), '') as epa_waste_code_4,
        IF(UPPER(TRIM(`controlled-substance`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`controlled-substance`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as controlled_substance,
        IF(UPPER(TRIM(`section-312`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`section-312`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as section_312,
        NULLIF(TRIM(`Emergency-Response-Guide`), '') as emergency_response_guide,
        CAST(TRY_TO_TIMESTAMP(`MSDS-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as msds_date,
        CAST(TRY_TO_TIMESTAMP(`C-of-A-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as c_of_a_date,
        TRY_CAST(`superfund-rate` AS DECIMAL(18,6)) as superfund_rate,
        TRY_CAST(`Excise-Tax-Rate` AS DECIMAL(18,6)) as excise_tax_rate,
        TRY_CAST(`CFC-Rate` AS DECIMAL(18,6)) as cfc_rate,
        TRY_CAST(`Marine-Tax-Rate` AS DECIMAL(18,6)) as marine_tax_rate,
        IF(UPPER(TRIM(`Lot-Controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Lot-Controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as lot_controlled,
        IF(UPPER(TRIM(`Location-Controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Location-Controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as location_controlled,
        IF(UPPER(TRIM(`Serial-Number-Controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Serial-Number-Controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as serial_number_controlled,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyyMMddHH:mm:ss') as update_date_time,
        NULLIF(TRIM(`User-1`), '') as user_1,
        TRY_CAST(`Freight-Class-Key` AS DECIMAL(18,0)) as freight_class_key,
        TRY_CAST(`Sequence-1` AS DECIMAL(18,0)) as sequence_1,
        IF(UPPER(TRIM(`DisablePosting`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`DisablePosting`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as disable_posting,
        TRY_CAST(`Budget-Amount` AS DECIMAL(18,2)) as budget_amount,
        NULLIF(TRIM(`Signal-word`), '') as signal_word,
        NULLIF(TRIM(`Stmt-of-hazard`), '') as stmt_of_hazard,
        NULLIF(TRIM(`Precautionary-measures`), '') as precautionary_measures,
        NULLIF(TRIM(`First-aid-eye`), '') as first_aid_eye,
        NULLIF(TRIM(`First-aid-skin`), '') as first_aid_skin,
        NULLIF(TRIM(`First-aid-inhalation`), '') as first_aid_inhalation,
        NULLIF(TRIM(`First-aid-ingestion`), '') as first_aid_ingestion,
        NULLIF(TRIM(`Components-1`), '') as components_1,
        NULLIF(TRIM(`Components-2`), '') as components_2,
        NULLIF(TRIM(`Components-3`), '') as components_3,
        NULLIF(TRIM(`DOT-hazard-stmnt`), '') as dot_hazard_stmnt,
        NULLIF(TRIM(`RQ`), '') as rq,
        NULLIF(TRIM(`User-2`), '') as user_2,
        TRY_CAST(`UM-Conversion-Percentage` AS DECIMAL(5,2)) as um_conversion_percentage,
        NULLIF(TRIM(`NFPA-Health-Rating`), '') as nfpa_health_rating,
        NULLIF(TRIM(`NFPA-Flammability-Rating`), '') as nfpa_flammability_rating,
        NULLIF(TRIM(`NFPA-Reactivity-Rating`), '') as nfpa_reactivity_rating,
        NULLIF(TRIM(`NFPA-Special-Hazards-Rating`), '') as nfpa_special_hazards_rating,
        CAST(TRY_TO_TIMESTAMP(`Label-Data-Rev-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as label_data_rev_date,
        TRY_CAST(`UM-Conversion-Type` AS DECIMAL(10,0)) as um_conversion_type,
        TRY_CAST(`Shelf-Life` AS DECIMAL(18,0)) as shelf_life,
        TRY_CAST(`Solution-Factor` AS DECIMAL(18,4)) as solution_factor,
        NULLIF(TRIM(`Receipt-Route`), '') as receipt_route,
        IF(UPPER(TRIM(`Require-HM-Column`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Require-HM-Column`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as require_hm_column,
        NULLIF(TRIM(`Product-Division`), '') as product_division,
        NULLIF(TRIM(`GL-Acct-Ptr`), '') as gl_acct_ptr,
        NULLIF(TRIM(`Product-Class`), '') as product_class,
        IF(UPPER(TRIM(`Use-FIFO`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Use-FIFO`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as use_fifo,
        IF(UPPER(TRIM(`User-Logical-2`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`User-Logical-2`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as user_logical_2,
        NULLIF(TRIM(`MSDS-Image-File`), '') as msds_image_file,
        NULLIF(TRIM(`User-Char-2`), '') as user_char_2,
        TRY_CAST(`User-Decimal-1` AS DECIMAL(18,2)) as user_decimal_1,
        TRY_CAST(`User-Decimal-2` AS DECIMAL(18,2)) as user_decimal_2,
        TRY_CAST(`User-Int-1` AS DECIMAL(18,0)) as user_int_1,
        TRY_CAST(`User-Int-2` AS DECIMAL(18,0)) as user_int_2,
        TRY_CAST(`Weight` AS DECIMAL(18,4)) as weight,
        NULLIF(TRIM(`Weight-UM`), '') as weight_um,
        NULLIF(TRIM(`EHS-Name`), '') as ehs_name,
        IF(UPPER(TRIM(`Section-313`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Section-313`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as section_313,
        NULLIF(TRIM(`Component-CAS-Number@1`), '') as component_cas_number_1,
        NULLIF(TRIM(`Component-CAS-Number@2`), '') as component_cas_number_2,
        NULLIF(TRIM(`Component-CAS-Number@3`), '') as component_cas_number_3,
        NULLIF(TRIM(`Component-CAS-Number@4`), '') as component_cas_number_4,
        NULLIF(TRIM(`Component-CAS-Number@5`), '') as component_cas_number_5,
        NULLIF(TRIM(`Component-CAS-Number@6`), '') as component_cas_number_6,
        NULLIF(TRIM(`Component-CAS-Number@7`), '') as component_cas_number_7,
        NULLIF(TRIM(`Component-CAS-Number@8`), '') as component_cas_number_8,
        NULLIF(TRIM(`Component-CAS-Number@9`), '') as component_cas_number_9,
        NULLIF(TRIM(`Component-CAS-Number@10`), '') as component_cas_number_10,
        NULLIF(TRIM(`Component-CAS-Number@11`), '') as component_cas_number_11,
        NULLIF(TRIM(`Component-CAS-Number@12`), '') as component_cas_number_12,
        NULLIF(TRIM(`Component-CAS-Number@13`), '') as component_cas_number_13,
        NULLIF(TRIM(`Component-CAS-Number@14`), '') as component_cas_number_14,
        NULLIF(TRIM(`Component-CAS-Number@15`), '') as component_cas_number_15,
        NULLIF(TRIM(`Component-CAS-Number@16`), '') as component_cas_number_16,
        NULLIF(TRIM(`Component-CAS-Number@17`), '') as component_cas_number_17,
        NULLIF(TRIM(`Component-CAS-Number@18`), '') as component_cas_number_18,
        NULLIF(TRIM(`Component-CAS-Number@19`), '') as component_cas_number_19,
        NULLIF(TRIM(`Component-CAS-Number@20`), '') as component_cas_number_20,
        TRY_CAST(`SARA-EHS-TPQ` AS DECIMAL(18,2)) as sara_ehs_tpq,
        IF(UPPER(TRIM(`CERCLA-311`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`CERCLA-311`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as cercla_311,
        IF(UPPER(TRIM(`Other-311`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Other-311`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as other_311,
        NULLIF(TRIM(`Tax-UM`), '') as tax_um,
        NULLIF(TRIM(`Tax-Group`), '') as tax_group,
        IF(UPPER(TRIM(`Active`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Active`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as active,
        NULLIF(TRIM(`Security-Access-2`), '') as security_access_2,
        NULLIF(TRIM(`User-Char-3`), '') as user_char_3,
        IF(UPPER(TRIM(`User-Logical-3`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`User-Logical-3`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as user_logical_3,
        NULLIF(TRIM(`HMIS-Physical-Hazard`), '') as hmphysical_hazard,
        NULLIF(TRIM(`Local-TPQ-UM`), '') as local_tpq_um,
        CAST(TRY_TO_TIMESTAMP(`Last-Sale-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_sale_date,
        CAST(TRY_TO_TIMESTAMP(`OH-Zero-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as oh_zero_date,
        TRY_CAST(`Local-TPQ` AS DECIMAL(18,2)) as local_tpq,
        TRY_CAST(`Spare-Decimal-2` AS DECIMAL(20,10)) as spare_decimal_2,
        IF(UPPER(TRIM(`Local-Right-To-Know`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Local-Right-To-Know`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as local_right_to_know,
        IF(UPPER(TRIM(`Quote-Temporary-Product`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Quote-Temporary-Product`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as quote_temporary_product,
        TRY_CAST(`Spare-Integer-1` AS DECIMAL(18,0)) as spare_integer_1,
        TRY_CAST(`Spare-Integer-2` AS DECIMAL(18,0)) as spare_integer_2,
        NULLIF(TRIM(`Product-Name-Change`), '') as product_name_change,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyyMMddHH:mm:ss') as created_date_time,
        NULLIF(TRIM(`Tariff-Code`), '') as tariff_code,
        NULLIF(TRIM(`Product-Synonym`), '') as product_synonym,
        NULLIF(TRIM(`Spec-Sheet-Image-File`), '') as spec_sheet_image_file,
        IF(UPPER(TRIM(`No-CofA-Required`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`No-CofA-Required`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as no_cofa_required,
        NULLIF(TRIM(`Index-Price-Group`), '') as index_price_group,
        IF(UPPER(TRIM(`Do-Not-Track-Inventory`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Do-Not-Track-Inventory`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as do_not_track_inventory,
        TRY_CAST(`Spare-Decimal-3` AS DECIMAL(20,10)) as spare_decimal_3,
        NULLIF(TRIM(`Location-Storage-Code`), '') as location_storage_code,
        NULLIF(TRIM(`Purchase-Limit-Group`), '') as purchase_limit_group,
        NULLIF(TRIM(`Formula-Price-Group`), '') as formula_price_group,
        TRY_CAST(`Component-CAS-Percentage@1` AS DECIMAL(5,2)) as component_cas_percentage_1,
        TRY_CAST(`Component-CAS-Percentage@2` AS DECIMAL(5,2)) as component_cas_percentage_2,
        TRY_CAST(`Component-CAS-Percentage@3` AS DECIMAL(5,2)) as component_cas_percentage_3,
        TRY_CAST(`Component-CAS-Percentage@4` AS DECIMAL(5,2)) as component_cas_percentage_4,
        TRY_CAST(`Component-CAS-Percentage@5` AS DECIMAL(5,2)) as component_cas_percentage_5,
        TRY_CAST(`Component-CAS-Percentage@6` AS DECIMAL(5,2)) as component_cas_percentage_6,
        TRY_CAST(`Component-CAS-Percentage@7` AS DECIMAL(5,2)) as component_cas_percentage_7,
        TRY_CAST(`Component-CAS-Percentage@8` AS DECIMAL(5,2)) as component_cas_percentage_8,
        TRY_CAST(`Component-CAS-Percentage@9` AS DECIMAL(5,2)) as component_cas_percentage_9,
        TRY_CAST(`Component-CAS-Percentage@10` AS DECIMAL(5,2)) as component_cas_percentage_10,
        TRY_CAST(`Component-CAS-Percentage@11` AS DECIMAL(5,2)) as component_cas_percentage_11,
        TRY_CAST(`Component-CAS-Percentage@12` AS DECIMAL(5,2)) as component_cas_percentage_12,
        TRY_CAST(`Component-CAS-Percentage@13` AS DECIMAL(5,2)) as component_cas_percentage_13,
        TRY_CAST(`Component-CAS-Percentage@14` AS DECIMAL(5,2)) as component_cas_percentage_14,
        TRY_CAST(`Component-CAS-Percentage@15` AS DECIMAL(5,2)) as component_cas_percentage_15,
        TRY_CAST(`Component-CAS-Percentage@16` AS DECIMAL(5,2)) as component_cas_percentage_16,
        TRY_CAST(`Component-CAS-Percentage@17` AS DECIMAL(5,2)) as component_cas_percentage_17,
        TRY_CAST(`Component-CAS-Percentage@18` AS DECIMAL(5,2)) as component_cas_percentage_18,
        TRY_CAST(`Component-CAS-Percentage@19` AS DECIMAL(5,2)) as component_cas_percentage_19,
        TRY_CAST(`Component-CAS-Percentage@20` AS DECIMAL(5,2)) as component_cas_percentage_20,
        NULLIF(TRIM(`Auto-Lot-Code-Alias`), '') as auto_lot_code_alias,
        TRY_CAST(`Contained-Calculate-Factor` AS DECIMAL(18,4)) as contained_calculate_factor,
        IF(UPPER(TRIM(`Spare-Logical-4`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-4`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as spare_logical_4,
        NULLIF(TRIM(`Internal-Use-Image-File`), '') as internal_use_image_file,
        IF(UPPER(TRIM(`Food-Grade`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Food-Grade`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as food_grade,
        IF(UPPER(TRIM(`PH-Flammable`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Flammable`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_flammable,
        IF(UPPER(TRIM(`PH-Gas-under-Pressure`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Gas-under-Pressure`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_gas_under_pressure,
        IF(UPPER(TRIM(`PH-Explosive`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Explosive`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_explosive,
        IF(UPPER(TRIM(`PH-Self-heating`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Self-heating`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_self_heating,
        IF(UPPER(TRIM(`PH-Pyrophoric-liquid-solid`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Pyrophoric-liquid-solid`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_pyrophoric_liquid_solid,
        IF(UPPER(TRIM(`PH-Pyrophoric-Gas`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Pyrophoric-Gas`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_pyrophoric_gas,
        IF(UPPER(TRIM(`PH-Corrosive-to-metal`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Corrosive-to-metal`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_corrosive_to_metal,
        IF(UPPER(TRIM(`PH-Oxidizer`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Oxidizer`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_oxidizer,
        IF(UPPER(TRIM(`PH-Organic-peroxide`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Organic-peroxide`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_organic_peroxide,
        IF(UPPER(TRIM(`PH-Self-reactive`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Self-reactive`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_self_reactive,
        IF(UPPER(TRIM(`PH-Water-emits-flammable-gas`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Water-emits-flammable-gas`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_water_emits_flammable_gas,
        IF(UPPER(TRIM(`PH-Combustible-Dust`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-Combustible-Dust`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_combustible_dust,
        IF(UPPER(TRIM(`PH-HNOC`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`PH-HNOC`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as ph_hnoc,
        IF(UPPER(TRIM(`HH-Carcinogenicity`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Carcinogenicity`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_carcinogenicity,
        IF(UPPER(TRIM(`HH-Acute-toxicity`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Acute-toxicity`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_acute_toxicity,
        IF(UPPER(TRIM(`HH-Reproductive-toxicity`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Reproductive-toxicity`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_reproductive_toxicity,
        IF(UPPER(TRIM(`HH-Skin-Corrosion-Irritation`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Skin-Corrosion-Irritation`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_skin_corrosion_irritation,
        IF(UPPER(TRIM(`HH-Respiratory-Skin`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Respiratory-Skin`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_respiratory_skin,
        IF(UPPER(TRIM(`HH-Eye-damage-Irritation`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Eye-damage-Irritation`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_eye_damage_irritation,
        IF(UPPER(TRIM(`HH-Specific-Target-Organ`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Specific-Target-Organ`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_specific_target_organ,
        IF(UPPER(TRIM(`HH-Aspiration-Hazard`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Aspiration-Hazard`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_aspiration_hazard,
        IF(UPPER(TRIM(`HH-Germ-cell-mutagenicity`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Germ-cell-mutagenicity`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_germ_cell_mutagenicity,
        IF(UPPER(TRIM(`HH-Simple-Asphyxiant`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-Simple-Asphyxiant`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_simple_asphyxiant,
        IF(UPPER(TRIM(`HH-HNOC`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`HH-HNOC`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as hh_hnoc,
        NULLIF(TRIM(`Uber-Keywords`), '') as uber_keywords,
        NULLIF(TRIM(`Uber-Search`), '') as uber_search,
        NULLIF(TRIM(`PDR`), '') as pdr,
        NULLIF(TRIM(`Spare-Char-7`), '') as spare_char_7,
        NULLIF(TRIM(`Spare-Char-8`), '') as spare_char_8,
        NULLIF(TRIM(`Spare-Char-9`), '') as spare_char_9,
        IF(UPPER(TRIM(`Spare-Logical-5`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-5`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as spare_logical_5,
        IF(UPPER(TRIM(`Spare-Logical-6`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-6`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as spare_logical_6,
        NULLIF(TRIM(`Supp-Product-Code`), '') as supp_product_code,
        IF(UPPER(TRIM(`Created-From-ProdCatalog`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Created-From-ProdCatalog`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as created_from_prodcatalog,
        NULLIF(TRIM(`Spare-Char-10`), '') as spare_char_10,
        IF(UPPER(TRIM(`Spare-Logical-7`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-7`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as spare_logical_7,
        IF(UPPER(TRIM(`Allow-Name-Override`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Allow-Name-Override`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as allow_name_override,
        NULLIF(TRIM(`Supplier-ID`), '') as supplier_id,
        NULLIF(TRIM(`Secondary-GHS-Product-Label`), '') as secondary_ghs_product_label,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-3`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_3,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-4`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_4
    from {{ source('bronze', 'product') }}

),

free_field as (
    select
        source_database,
        TRY_CAST(data_key AS DECIMAL(18,0)) as data_key_num,
        prod_segment
    from {{ ref('stg_free_field_data') }}
    where lower(program_id) = 'prodfmnt'
      and prod_segment is not null
)

select
    c.*,
    ff.prod_segment as product_segment
from cleaned c
left join free_field ff
    on  c.source_database                        = ff.source_database
    and TRY_CAST(c.product_key AS DECIMAL(18,0))  = ff.data_key_num
