select
    source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Batch-Warehouse`), '') as batch_warehouse,
        TRY_CAST(`Receipt-Num` AS DECIMAL(18,0)) as receipt_num,
        NULLIF(TRIM(`Receipt-NumCV`), '') as receipt_numcv,
        TRY_CAST(`Batch-Num` AS DECIMAL(18,0)) as batch_num,
        NULLIF(TRIM(`Batch-NumCV`), '') as batch_numcv,
        NULLIF(TRIM(`Receipt-Status`), '') as receipt_status,
        NULLIF(TRIM(`Cust-ID`), '') as cust_id,
        NULLIF(TRIM(`Product-Code`), '') as product_code,
        NULLIF(TRIM(`Packaging-Code`), '') as packaging_code,
        NULLIF(TRIM(`Formula-Code`), '') as formula_code,
        TRY_CAST(`Version-1` AS DECIMAL(18,0)) as version,
        TRY_CAST(`Revision` AS DECIMAL(18,0)) as revision,
        NULLIF(TRIM(`Prod-Pkg-Code`), '') as prod_pkg_code,
        NULLIF(TRIM(`Campaign-ID`), '') as campaign_id,
        NULLIF(TRIM(`FG-Receipt-Route`), '') as fg_receipt_route,
        TRY_CAST(`Total-RM-Quantity` AS DECIMAL(38,4)) as total_rm_quantity,
        TRY_CAST(`Quantity` AS DECIMAL(38,4)) as quantity,
        NULLIF(TRIM(`Qty-Cost-UM`), '') as qty_cost_um,
        TRY_CAST(`Standard-Cost` AS DECIMAL(38,4)) as standard_cost,
        TRY_CAST(`Average-Cost` AS DECIMAL(38,4)) as average_cost,
        TRY_CAST(`Last-Cost` AS DECIMAL(38,4)) as last_cost,
        TRY_CAST(`Cost` AS DECIMAL(38,4)) as cost,
        TRY_CAST(`Extended-Cost` AS DECIMAL(38,2)) as extended_cost,
        TRY_CAST(`Extended-Cost-Standard` AS DECIMAL(38,2)) as extended_cost_standard,
        TRY_CAST(`Drum-Off-Quantity-Loss` AS DECIMAL(38,4)) as drum_off_quantity_loss,
        NULLIF(TRIM(`Drum-Off-Loss-UM`), '') as drum_off_loss_um,
        CAST(TRY_TO_TIMESTAMP(`Receipt-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as receipt_date,
        NULLIF(TRIM(`Receipt-Time`), '') as receipt_time,
        TRY_CAST(`Internal-Key` AS DECIMAL(18,0)) as internal_key,
        NULLIF(TRIM(`Cancel-by`), '') as cancel_by,
        CAST(TRY_TO_TIMESTAMP(`Cancel-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cancel_date,
        NULLIF(TRIM(`Cancel-time`), '') as cancel_time,
        NULLIF(TRIM(`Cancel-Reason`), '') as cancel_reason,
        NULLIF(TRIM(`Cancel-Code`), '') as cancel_code,
        NULLIF(TRIM(`Currency`), '') as currency,
        TRY_CAST(`Posting-Period` AS DECIMAL(18,0)) as posting_period,
        TRY_CAST(`Posting-Year` AS DECIMAL(18,0)) as posting_year,
        NULLIF(TRIM(`Year-Period`), '') as year_period,
        NULLIF(TRIM(`Posted-Currency`), '') as posted_currency,
        TRY_CAST(`Posted-Exchange-Rate` AS DECIMAL(18,8)) as posted_exchange_rate,
        IF(UPPER(TRIM(`Posted-to-GL`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-to-GL`)) = 'FALSE', FALSE, NULL)) as posted_to_gl,
        CAST(TRY_TO_TIMESTAMP(`Posted-to-GL-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as posted_to_gl_date,
        NULLIF(TRIM(`Posted-to-GL-Time`), '') as posted_to_gl_time,
        IF(UPPER(TRIM(`Posted-Summary-Entry`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-Summary-Entry`)) = 'FALSE', FALSE, NULL)) as posted_summary_entry,
        NULLIF(TRIM(`Posted-Journal-Number`), '') as posted_journal_number,
        NULLIF(TRIM(`Posted-Drum-Off-Journal-Number`), '') as posted_drum_off_journal_number,
        IF(UPPER(TRIM(`Posted-to-GL-Use-Std-Cost`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-to-GL-Use-Std-Cost`)) = 'FALSE', FALSE, NULL)) as posted_to_gl_use_std_cost,
        NULLIF(TRIM(`Posted-GL-Acct-Ptr`), '') as posted_gl_acct_ptr,
        NULLIF(TRIM(`Posted-Variance-GL-Acct-Ptr`), '') as posted_variance_gl_acct_ptr,
        TRY_CAST(`Quantity-Manufactured` AS DECIMAL(38,4)) as quantity_manufactured,
        TRY_CAST(`Drum-Off-Manufactured` AS DECIMAL(38,4)) as drum_off_manufactured,
        NULLIF(TRIM(`Qty-Manufactured-UM`), '') as qty_manufactured_um,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`User-1`), '') as user_1,
        NULLIF(TRIM(`Image-File-BT`), '') as image_file_bt,
        TRY_TO_TIMESTAMP(`Receipt-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as receipt_date_time,
        NULLIF(TRIM(`User-Defined-Field-Value`), '') as user_defined_field_value,
        NULLIF(TRIM(`Receipt-By`), '') as receipt_by,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`FGCost-Quantity` AS DECIMAL(38,4)) as fgcost_quantity,
        TRY_CAST(`Spare-Decimal-2` AS DECIMAL(38,10)) as spare_decimal_2,
        IF(UPPER(TRIM(`FGCost-Include-Co-Products-Qty`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`FGCost-Include-Co-Products-Qty`)) = 'FALSE', FALSE, NULL)) as fgcost_include_co_products_qty,
        IF(UPPER(TRIM(`Spare-Logical-2`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Spare-Logical-2`)) = 'FALSE', FALSE, NULL)) as spare_logical_2,
        TRY_CAST(`Spare-Integer-1` AS DECIMAL(18,0)) as spare_integer_1,
        TRY_CAST(`Spare-Integer-2` AS DECIMAL(18,0)) as spare_integer_2,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        NULLIF(TRIM(`Receipt-TID`), '') as receipt_tid,
        IF(UPPER(TRIM(`Posting-Hold`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posting-Hold`)) = 'FALSE', FALSE, NULL)) as posting_hold,
        NULLIF(TRIM(`Hold-Reason`), '') as hold_reason,
        NULLIF(TRIM(`Hold-Details`), '') as hold_details,
        NULLIF(TRIM(`Hold-By`), '') as hold_by,
        TRY_TO_TIMESTAMP(`Hold-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as hold_date_time,
        IF(UPPER(TRIM(`Spare-Logical-3`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Spare-Logical-3`)) = 'FALSE', FALSE, NULL)) as spare_logical_3,
        TRY_CAST(`Spare-Decimal-3` AS DECIMAL(38,10)) as spare_decimal_3,
        NULLIF(TRIM(`Receipt-Source`), '') as receipt_source,
        NULLIF(TRIM(`Spare-Char-4`), '') as spare_char_4,
        NULLIF(TRIM(`Spare-Char-5`), '') as spare_char_5,
        NULLIF(TRIM(`Spare-Char-6`), '') as spare_char_6
from {{ source('bronze', 'batch_rec_hdr') }}
