select
`SOURCE_DATABASE` as source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        TRY_CAST(`Invoice-Num` AS DECIMAL(18,0)) as invoice_num,
        NULLIF(TRIM(`Invoice-NumCV`), '') as invoice_numcv,
        TRY_CAST(`Order-Num` AS DECIMAL(18,0)) as order_num,
        NULLIF(TRIM(`Order-NumCV`), '') as order_numcv,
        TRY_CAST(`Bill-of-Lading-Num` AS DECIMAL(18,0)) as bill_of_lading_num,
        NULLIF(TRIM(`Cust-Key`), '') as cust_key,
        TRY_CAST(`Shipto-Seq-Num` AS DECIMAL(18,0)) as shipto_seq_num,
        CAST(TRY_TO_TIMESTAMP(`Ship-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as ship_date,
        CAST(TRY_TO_TIMESTAMP(`Invoice-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as invoice_date,
        CAST(TRY_TO_TIMESTAMP(`Due-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as due_date,
        NULLIF(TRIM(`Sales-Agent-ID`), '') as sales_agent_id,
        NULLIF(TRIM(`Invoice-Currency`), '') as invoice_currency,
        TRY_CAST(`Invoice-Currency-Conversion-Rate` AS DECIMAL(18,8)) as invoice_currency_conversion_rate,
        CAST(TRY_TO_TIMESTAMP(`Invoice-Currency-Conversion-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as invoice_currency_conversion_date,
        NULLIF(TRIM(`Convert-To-Currency`), '') as convert_to_currency,
        TRY_CAST(`Invoice-Amount` AS DECIMAL(38,2)) as invoice_amount,
        TRY_CAST(`Merchandise` AS DECIMAL(38,2)) as merchandise,
        TRY_CAST(`Sales-Tax` AS DECIMAL(38,2)) as sales_tax,
        TRY_CAST(`Domestic-Freight` AS DECIMAL(38,2)) as domestic_freight,
        NULLIF(TRIM(`Domestic-Freight-GL-Acct-Ptr`), '') as domestic_freight_gl_acct_ptr,
        TRY_CAST(`Export-Fees-Pallet` AS DECIMAL(38,2)) as export_fees_pallet,
        TRY_CAST(`Export-Fees-Handling` AS DECIMAL(38,2)) as export_fees_handling,
        TRY_CAST(`Export-Fees-Freight` AS DECIMAL(38,2)) as export_fees_freight,
        TRY_CAST(`Export-Fees-Other` AS DECIMAL(38,2)) as export_fees_other,
        TRY_CAST(`Pallet` AS DECIMAL(38,2)) as pallet,
        TRY_CAST(`Superfund` AS DECIMAL(38,2)) as superfund,
        TRY_CAST(`Excise-Tax` AS DECIMAL(38,2)) as excise_tax,
        TRY_CAST(`Tax-1` AS DECIMAL(38,2)) as tax_1,
        TRY_CAST(`Tax-2` AS DECIMAL(38,2)) as tax_2,
        TRY_CAST(`Tax-3` AS DECIMAL(38,2)) as tax_3,
        TRY_CAST(`Container-Deposit` AS DECIMAL(38,2)) as container_deposit,
        TRY_CAST(`Container-Return` AS DECIMAL(38,2)) as container_return,
        TRY_CAST(`Container-Service-Charge` AS DECIMAL(38,2)) as container_service_charge,
        TRY_CAST(`Cont-Charge-Collected-on-Refunds` AS DECIMAL(38,2)) as cont_charge_collected_on_refunds,
        TRY_CAST(`Commission-Rate` AS DECIMAL(18,4)) as commission_rate,
        NULLIF(TRIM(`Misc-Description@1`), '') as misc_description_1,
        NULLIF(TRIM(`Misc-Description@2`), '') as misc_description_2,
        NULLIF(TRIM(`Misc-Description@3`), '') as misc_description_3,
        NULLIF(TRIM(`Misc-Description@4`), '') as misc_description_4,
        NULLIF(TRIM(`Misc-Description@5`), '') as misc_description_5,
        NULLIF(TRIM(`Misc-Description@6`), '') as misc_description_6,
        NULLIF(TRIM(`Misc-Description@7`), '') as misc_description_7,
        NULLIF(TRIM(`Misc-Description@8`), '') as misc_description_8,
        NULLIF(TRIM(`Misc-Description@9`), '') as misc_description_9,
        NULLIF(TRIM(`Misc-Description@10`), '') as misc_description_10,
        TRY_CAST(`Misc-Amount@1` AS DECIMAL(38,2)) as misc_amount_1,
        TRY_CAST(`Misc-Amount@2` AS DECIMAL(38,2)) as misc_amount_2,
        TRY_CAST(`Misc-Amount@3` AS DECIMAL(38,2)) as misc_amount_3,
        TRY_CAST(`Misc-Amount@4` AS DECIMAL(38,2)) as misc_amount_4,
        TRY_CAST(`Misc-Amount@5` AS DECIMAL(38,2)) as misc_amount_5,
        TRY_CAST(`Misc-Amount@6` AS DECIMAL(38,2)) as misc_amount_6,
        TRY_CAST(`Misc-Amount@7` AS DECIMAL(38,2)) as misc_amount_7,
        TRY_CAST(`Misc-Amount@8` AS DECIMAL(38,2)) as misc_amount_8,
        TRY_CAST(`Misc-Amount@9` AS DECIMAL(38,2)) as misc_amount_9,
        TRY_CAST(`Misc-Amount@10` AS DECIMAL(38,2)) as misc_amount_10,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@1`), '') as mumisc_gl_acct_ptr_1,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@2`), '') as misc_gl_acct_ptr_2,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@3`), '') as misc_gl_acct_ptr_3,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@4`), '') as misc_gl_acct_ptr_4,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@5`), '') as misc_gl_acct_ptr_5,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@6`), '') as misc_gl_acct_ptr_6,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@7`), '') as misc_gl_acct_ptr_7,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@8`), '') as misc_gl_acct_ptr_8,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@9`), '') as misc_gl_acct_ptr_9,
        NULLIF(TRIM(`Misc-GL-Acct-Ptr@10`), '') as misc_gl_acct_ptr_10,
        TRY_CAST(`Posting-Period` AS DECIMAL(18,0)) as posting_period,
        TRY_CAST(`Posting-Year` AS DECIMAL(18,0)) as posting_year,
        IF(UPPER(TRIM(`Posted-to-GL`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Posted-to-GL`)) ='FALSE', FALSE, NULL)) as posted_to_gl,
        CAST(TRY_TO_TIMESTAMP(`Posted-to-GL-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as posted_to_gl_date,
        NULLIF(TRIM(`Posted-to-GL-Time`), '') as posted_to_gl_time,
        IF(UPPER(TRIM(`Posted-in-Summary-Entry`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Posted-in-Summary-Entry`)) ='FALSE', FALSE, NULL)) as posted_in_summary_entry,
        NULLIF(TRIM(`Journal-Number`), '') as journal_number,
        CAST(TRY_TO_TIMESTAMP(`Last-Printed-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_printed_date,
        NULLIF(TRIM(`Sales-Tax-Code`), '') as sales_tax_code,
        NULLIF(TRIM(`Sale-Type`), '') as sale_type,
        IF(UPPER(TRIM(`Invoice-Without-BL`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Invoice-Without-BL`)) ='FALSE', FALSE, NULL)) as invoice_without_bl,
        IF(UPPER(TRIM(`Closed`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Closed`)) ='FALSE', FALSE, NULL)) as closed,
        IF(UPPER(TRIM(`Cancelled`)) = 'TRUE', TRUE,
      IF(UPPER(TRIM(`Cancelled`)) = 'FALSE', FALSE, NULL)) as cancelled,
        NULLIF(TRIM(`Cancel-by`), '') as cancel_by,
        CAST(TRY_TO_TIMESTAMP(`Cancel-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cancel_date,
        NULLIF(TRIM(`Cancel-time`), '') as cancel_time,
        NULLIF(TRIM(`Cancel-Reason`), '') as cancel_reason,
        TRY_CAST(`Internal-Key` AS DECIMAL(18,0)) as internal_key,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as update_date_time,
        NULLIF(TRIM(`User-1`), '') as user_1,
        NULLIF(TRIM(`Invoice-Terms-Key`), '') as invoice_terms_key,
        NULLIF(TRIM(`Invoice-Terms-Code`), '') as invoice_terms_code,
        IF(UPPER(TRIM(`Multiple-BL`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Multiple-BL`)) ='FALSE', FALSE, NULL)) as multiple_bl,
        NULLIF(TRIM(`Billing-Cust-Key`), '') as billing_cust_key,
        IF(UPPER(TRIM(`Posted-to-AR`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Posted-to-AR`)) ='FALSE', FALSE, NULL)) as posted_to_ar,
        CAST(TRY_TO_TIMESTAMP(`Posted-to-AR-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as posted_to_ar_date,
        NULLIF(TRIM(`Posted-to-AR-Time`), '') as posted_to_ar_time,
        NULLIF(TRIM(`Customer-PO-Num`), '') as customer_po_num,
        NULLIF(TRIM(`Requisition-Num`), '') as requisition_num,
        NULLIF(TRIM(`Letter-of-Credit`), '') as letter_of_credit,
        IF(UPPER(TRIM(`Posting-Hold`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Posting-Hold`)) ='FALSE', FALSE, NULL)) as posting_hold,
        NULLIF(TRIM(`Cancel-Code`), '') as cancel_code,
        NULLIF(TRIM(`Year-Period`), '') as year_period,
        TRY_CAST(`Ship-Tran-Num` AS DECIMAL(18,0)) as ship_tran_num,
        IF(UPPER(TRIM(`Printed`)) ='TRUE', TRUE,
      IF(UPPER(TRIM(`Printed`)) ='FALSE', FALSE, NULL)) as printed,
        NULLIF(TRIM(`Pallet-Product-Key`), '') as pallet_product_key,
        NULLIF(TRIM(`Pallet-Packaging-Key`), '') as pallet_packaging_key,
        TRY_CAST(`Pallet-Num` AS DECIMAL(18,0)) as pallet_num,
        NULLIF(TRIM(`Type-1`), '') as type_1,
        TRY_CAST(`Associated-Invoice-Num` AS DECIMAL(18,0)) as associated_invoice_num,
        NULLIF(TRIM(`Associated-Invoice-NumCV`), '') as associated_invoice_numcv,
        NULLIF(TRIM(`Default-Order-Type`), '') as default_order_type,
        NULLIF(TRIM(`Cust-ID`), '') as cust_id,
        NULLIF(TRIM(`COGS-Journal-Number`), '') as cogs_journal_number,
        NULLIF(TRIM(`Default-Ship-From-Warehouse`), '') as default_ship_from_warehouse,
        NULLIF(TRIM(`Shipper-ID`), '') as shipper_id,
        TRY_CAST(`Total-Freight-Weight` AS DECIMAL(38,2)) as total_freight_weight,
        NULLIF(TRIM(`Freight-Weight-UM`), '') as freight_weight_um,
        NULLIF(TRIM(`Image-File-BL`), '') as image_file_bl,
        NULLIF(TRIM(`Image-File-IN`), '') as image_file_in,
        NULLIF(TRIM(`Shipto-State`), '') as shipto_state,
        NULLIF(TRIM(`Shipto-Country`), '') as shipto_country,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@1`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@1`))='FALSE',FALSE,NULL)) as misc_sales_taxable_1,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@2`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@2`))='FALSE',FALSE,NULL)) as misc_sales_taxable_2,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@3`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@3`))='FALSE',FALSE,NULL)) as misc_sales_taxable_3,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@4`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@4`))='FALSE',FALSE,NULL)) as misc_sales_taxable_4,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@5`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@5`))='FALSE',FALSE,NULL)) as misc_sales_taxable_5,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@6`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@6`))='FALSE',FALSE,NULL)) as misc_sales_taxable_6,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@7`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@7`))='FALSE',FALSE,NULL)) as misc_sales_taxable_7,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@8`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@8`))='FALSE',FALSE,NULL)) as misc_sales_taxable_8,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@9`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@9`))='FALSE',FALSE,NULL)) as misc_sales_taxable_9,
        IF(UPPER(TRIM(`Misc-Sales-Taxable@10`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Taxable@10`))='FALSE',FALSE,NULL)) as misc_sales_taxable_10,
        CAST(TRY_TO_TIMESTAMP(`Sales-Tax-Start-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as sales_tax_start_date,
        TRY_CAST(`Sales-Tax-Rate` AS DECIMAL(18,4)) as sales_tax_rate,
        IF(UPPER(TRIM(`Sales-Taxable-Container-Deposit`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-Container-Deposit`))='FALSE',FALSE,NULL)) as sales_taxable_container_deposit,
        IF(UPPER(TRIM(`Sales-Taxable-Container-Return`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-Container-Return`))='FALSE',FALSE,NULL)) as sales_taxable_container_return,
        IF(UPPER(TRIM(`Sales-Taxable-Container-Service`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-Container-Service`))='FALSE',FALSE,NULL)) as sales_taxable_container_service,
        IF(UPPER(TRIM(`Sales-Taxable-Domestic-Freight`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-Domestic-Freight`))='FALSE',FALSE,NULL)) as sales_taxable_domestic_freight,
        IF(UPPER(TRIM(`Sales-Taxable-EF-Freight`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-EF-Freight`))='FALSE',FALSE,NULL)) as sales_taxable_ef_freight,
        IF(UPPER(TRIM(`Sales-Taxable-EF-Handling`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-EF-Handling`))='FALSE',FALSE,NULL)) as sales_taxable_ef_handling,
        IF(UPPER(TRIM(`Sales-Taxable-EF-Other`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-EF-Other`))='FALSE',FALSE,NULL)) as sales_taxable_ef_other,
        IF(UPPER(TRIM(`Sales-Taxable-EF-Pallet`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-EF-Pallet`))='FALSE',FALSE,NULL)) as sales_taxable_ef_pallet,
        IF(UPPER(TRIM(`Sales-Taxable-Pallet`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-Pallet`))='FALSE',FALSE,NULL)) as sales_taxable_pallet,
        NULLIF(TRIM(`Tax-State`), '') as tax_state,
        NULLIF(TRIM(`Tax-Country`), '') as tax_country,
        IF(UPPER(TRIM(`Cust-Apply-Sales-Tax`))='TRUE',TRUE,IF(UPPER(TRIM(`Cust-Apply-Sales-Tax`))='FALSE',FALSE,NULL)) as cust_apply_sales_tax,
        IF(UPPER(TRIM(`Cust-Apply-Excise-Taxes`))='TRUE',TRUE,IF(UPPER(TRIM(`Cust-Apply-Excise-Taxes`))='FALSE',FALSE,NULL)) as cust_apply_excise_taxes,
        IF(UPPER(TRIM(`Cust-Apply-Superfund`))='TRUE',TRUE,IF(UPPER(TRIM(`Cust-Apply-Superfund`))='FALSE',FALSE,NULL)) as cust_apply_superfund,
        IF(UPPER(TRIM(`Cust-Apply-CFC-Tax`))='TRUE',TRUE,IF(UPPER(TRIM(`Cust-Apply-CFC-Tax`))='FALSE',FALSE,NULL)) as cust_apply_cfc_tax,
        IF(UPPER(TRIM(`Cust-Apply-Marine-Tax`))='TRUE',TRUE,IF(UPPER(TRIM(`Cust-Apply-Marine-Tax`))='FALSE',FALSE,NULL)) as cust_apply_marine_tax,
        IF(UPPER(TRIM(`Ship-To-Exempt-From-Sales-Tax`))='TRUE',TRUE,IF(UPPER(TRIM(`Ship-To-Exempt-From-Sales-Tax`))='FALSE',FALSE,NULL)) as ship_to_exempt_from_sales_tax,
        IF(UPPER(TRIM(`Invoice-Level-Excise-Tax-Applied`))='TRUE',TRUE,IF(UPPER(TRIM(`Invoice-Level-Excise-Tax-Applied`))='FALSE',FALSE,NULL)) as invoice_level_excise_tax_applied,
        TRY_CAST(`Sales-Tax-Merchandise` AS DECIMAL(38,2)) as sales_tax_merchandise,
        TRY_CAST(`Sales-Tax-Non-Merchandise` AS DECIMAL(38,2)) as sales_tax_non_merchandise,
        TRY_CAST(`Exempt-Sales-Tax` AS DECIMAL(38,2)) as exempt_sales_tax,
        TRY_CAST(`Exempt-Sales-Tax-Merchandise` AS DECIMAL(38,2)) as exempt_sales_tax_merchandise,
        TRY_CAST(`Exempt-Sales-Tax-Non-Merchandise` AS DECIMAL(38,2)) as exempt_sales_tax_non_merchandise,
        TRY_CAST(`Exempt-Excise-Tax` AS DECIMAL(38,2)) as exempt_excise_tax,
        TRY_CAST(`Excise-Tax-Invoice-Level` AS DECIMAL(38,2)) as excise_tax_invoice_level,
        TRY_CAST(`Exempt-Excise-Tax-Invoice-Level` AS DECIMAL(38,2)) as exempt_excise_tax_invoice_level,
        TRY_CAST(`CFC-Tax` AS DECIMAL(38,2)) as cfc_tax,
        TRY_CAST(`Marine-Tax` AS DECIMAL(38,2)) as marine_tax,
        TRY_CAST(`Sales-Taxable-Amount` AS DECIMAL(38,2)) as sales_taxable_amount,
        TRY_CAST(`Exempt-Sales-Taxable-Amount` AS DECIMAL(38,2)) as exempt_sales_taxable_amount,
        NULLIF(TRIM(`Ref-Type`), '') as ref_type,
        NULLIF(TRIM(`Ref-Num`), '') as ref_num,
        NULLIF(TRIM(`AR-Ref-Cust-Key`), '') as ar_ref_cust_key,
        NULLIF(TRIM(`Interface-Invoice-Number`), '') as interface_invoice_number,
        NULLIF(TRIM(`Shipto-Name`), '') as shipto_name,
        NULLIF(TRIM(`Shipto-Address-1`), '') as shipto_address_1,
        NULLIF(TRIM(`Shipto-Address-2`), '') as shipto_address_2,
        NULLIF(TRIM(`Shipto-Address-3`), '') as shipto_address_3,
        NULLIF(TRIM(`Shipto-City`), '') as shipto_city,
        NULLIF(TRIM(`Shipto-Zip`), '') as shipto_zip,
        NULLIF(TRIM(`Hold-Reason`), '') as hold_reason,
        TRY_CAST(`SCSO-Associated-Invoice-Num` AS DECIMAL(18,0)) as scso_associated_invoice_num,
        IF(UPPER(TRIM(`Consolidated-Invoice`))='TRUE',TRUE,IF(UPPER(TRIM(`Consolidated-Invoice`))='FALSE',FALSE,NULL)) as consolidated_invoice,
        NULLIF(TRIM(`Consolidated-Invoice-Num`), '') as consolidated_invoice_num,
        NULLIF(TRIM(`Security-Access-2`), '') as security_access_2,
        IF(UPPER(TRIM(`Tax-Comp-Breakdown`))='TRUE',TRUE,IF(UPPER(TRIM(`Tax-Comp-Breakdown`))='FALSE',FALSE,NULL)) as tax_comp_breakdown,
        TRY_CAST(`Comp-TOT-Sales-Tax-Merch@1` AS DECIMAL(38,2)) as comp_tot_sales_tax_merch_1,
        TRY_CAST(`Comp-TOT-Sales-Tax-Merch@2` AS DECIMAL(38,2)) as comp_tot_sales_tax_merch_2,
        TRY_CAST(`Comp-TOT-Sales-Tax-Merch@3` AS DECIMAL(38,2)) as comp_tot_sales_tax_merch_3,
        TRY_CAST(`Comp-TOT-Sales-Tax-Non-Merch@1` AS DECIMAL(38,2)) as comp_tot_sales_tax_non_merch_1,
        TRY_CAST(`Comp-TOT-Sales-Tax-Non-Merch@2` AS DECIMAL(38,2)) as comp_tot_sales_tax_non_merch_2,
        TRY_CAST(`Comp-TOT-Sales-Tax-Non-Merch@3` AS DECIMAL(38,2)) as comp_tot_sales_tax_non_merch_3,
        NULLIF(TRIM(`Comp-GL-Acct-Ptr@1`), '') as comp_gl_acct_ptr_1,
        NULLIF(TRIM(`Comp-GL-Acct-Ptr@2`), '') as comp_gl_acct_ptr_2,
        NULLIF(TRIM(`Comp-GL-Acct-Ptr@3`), '') as comp_gl_acct_ptr_3,
        NULLIF(TRIM(`Comp-Tax-Rate-Desc@1`), '') as comp_tax_rate_desc_1,
        NULLIF(TRIM(`Comp-Tax-Rate-Desc@2`), '') as comp_tax_rate_desc_2,
        NULLIF(TRIM(`Comp-Tax-Rate-Desc@3`), '') as comp_tax_rate_desc_3,
        TRY_CAST(`Comp-Tax-Rate@1` AS DECIMAL(18,4)) as comp_tax_rate_1,
        TRY_CAST(`Comp-Tax-Rate@2` AS DECIMAL(18,4)) as comp_tax_rate_2,
        TRY_CAST(`Comp-Tax-Rate@3` AS DECIMAL(18,4)) as comp_tax_rate_3,
        NULLIF(TRIM(`Hold-By`), '') as hold_by,
        TRY_TO_TIMESTAMP(`Hold-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as hold_date_time,
        TRY_TO_TIMESTAMP(`Export-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as export_date_time,
        NULLIF(TRIM(`Export-ID`), '') as export_id,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`Haz-Mat-Handling-Charge` AS DECIMAL(38,2)) as haz_mat_handling_charge,
        TRY_CAST(`Payment-Amount` AS DECIMAL(38,2)) as payment_amount,
        IF(UPPER(TRIM(`DNU-Hazmat-Stored-In-Superfund`))='TRUE',TRUE,IF(UPPER(TRIM(`DNU-Hazmat-Stored-In-Superfund`))='FALSE',FALSE,NULL)) as dnu_hazmat_stored_in_superfund,
        IF(UPPER(TRIM(`Sales-Taxable-Haz-Mat`))='TRUE',TRUE,IF(UPPER(TRIM(`Sales-Taxable-Haz-Mat`))='FALSE',FALSE,NULL)) as sales_taxable_haz_mat,
        TRY_CAST(`Spare-Integer-1` AS DECIMAL(18,0)) as spare_integer_1,
        TRY_CAST(`Spare-Integer-2` AS DECIMAL(18,0)) as spare_integer_2,
        IF(UPPER(TRIM(`Do-Not-Update-Sales-History`))='TRUE',TRUE,IF(UPPER(TRIM(`Do-Not-Update-Sales-History`))='FALSE',FALSE,NULL)) as do_not_update_sales_history,
        NULLIF(TRIM(`AP-Voucher-Remark`), '') as ap_voucher_remark,
        NULLIF(TRIM(`Payment-ID-Num`), '') as payment_id_num,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        TRY_CAST(`Total-Outbound-Charge` AS DECIMAL(38,2)) as total_outbound_charge,
        TRY_CAST(`COGS-Currency-Conversion-Rate` AS DECIMAL(18,8)) as cogs_currency_conversion_rate,
        CAST(TRY_TO_TIMESTAMP(`COGS-Currency-Conversion-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cogs_currency_conversion_date,
        NULLIF(TRIM(`Return-Reason-Code`), '') as return_reason_code,
        NULLIF(TRIM(`Sales-Agent-ID-2`), '') as sales_agent_id_2,
        IF(UPPER(TRIM(`Include-Automated-Print`))='TRUE',TRUE,IF(UPPER(TRIM(`Include-Automated-Print`))='FALSE',FALSE,NULL)) as include_automated_print,
        TRY_CAST(`Misc-Percent@1` AS DECIMAL(18,2)) as misc_percent_1,
        TRY_CAST(`Misc-Percent@2` AS DECIMAL(18,2)) as misc_percent_2,
        TRY_CAST(`Misc-Percent@3` AS DECIMAL(18,2)) as misc_percent_3,
        TRY_CAST(`Misc-Percent@4` AS DECIMAL(18,2)) as misc_percent_4,
        TRY_CAST(`Misc-Percent@5` AS DECIMAL(18,2)) as misc_percent_5,
        TRY_CAST(`Misc-Percent@6` AS DECIMAL(18,2)) as misc_percent_6,
        TRY_CAST(`Misc-Percent@7` AS DECIMAL(18,2)) as misc_percent_7,
        TRY_CAST(`Misc-Percent@8` AS DECIMAL(18,2)) as misc_percent_8,
        TRY_CAST(`Misc-Percent@9` AS DECIMAL(18,2)) as misc_percent_9,
        TRY_CAST(`Misc-Percent@10` AS DECIMAL(18,2)) as misc_percent_10,
        TRY_CAST(`Misc-Min-Percent-Amount@1` AS DECIMAL(38,2)) as misc_min_percent_amount_1,
        TRY_CAST(`Misc-Min-Percent-Amount@2` AS DECIMAL(38,2)) as misc_min_percent_amount_2,
        TRY_CAST(`Misc-Min-Percent-Amount@3` AS DECIMAL(38,2)) as misc_min_percent_amount_3,
        TRY_CAST(`Misc-Min-Percent-Amount@4` AS DECIMAL(38,2)) as misc_min_percent_amount_4,
        TRY_CAST(`Misc-Min-Percent-Amount@5` AS DECIMAL(38,2)) as misc_min_percent_amount_5,
        TRY_CAST(`Misc-Min-Percent-Amount@6` AS DECIMAL(38,2)) as misc_min_percent_amount_6,
        TRY_CAST(`Misc-Min-Percent-Amount@7` AS DECIMAL(38,2)) as misc_min_percent_amount_7,
        TRY_CAST(`Misc-Min-Percent-Amount@8` AS DECIMAL(38,2)) as misc_min_percent_amount_8,
        TRY_CAST(`Misc-Min-Percent-Amount@9` AS DECIMAL(38,2)) as misc_min_percent_amount_9,
        TRY_CAST(`Misc-Min-Percent-Amount@10` AS DECIMAL(38,2)) as misc_min_percent_amount_10,
        TRY_CAST(`Misc-Max-Percent-Amount@1` AS DECIMAL(38,2)) as misc_max_percent_amount_1,
        TRY_CAST(`Misc-Max-Percent-Amount@2` AS DECIMAL(38,2)) as misc_max_percent_amount_2,
        TRY_CAST(`Misc-Max-Percent-Amount@3` AS DECIMAL(38,2)) as misc_max_percent_amount_3,
        TRY_CAST(`Misc-Max-Percent-Amount@4` AS DECIMAL(38,2)) as misc_max_percent_amount_4,
        TRY_CAST(`Misc-Max-Percent-Amount@5` AS DECIMAL(38,2)) as misc_max_percent_amount_5,
        TRY_CAST(`Misc-Max-Percent-Amount@6` AS DECIMAL(38,2)) as misc_max_percent_amount_6,
        TRY_CAST(`Misc-Max-Percent-Amount@7` AS DECIMAL(38,2)) as misc_max_percent_amount_7,
        TRY_CAST(`Misc-Max-Percent-Amount@8` AS DECIMAL(38,2)) as misc_max_percent_amount_8,
        TRY_CAST(`Misc-Max-Percent-Amount@9` AS DECIMAL(38,2)) as misc_max_percent_amount_9,
        TRY_CAST(`Misc-Max-Percent-Amount@10` AS DECIMAL(38,2)) as misc_max_percent_amount_10,
        TRY_CAST(`RMA-Receipt-Num` AS DECIMAL(18,0)) as rma_receipt_num,
        NULLIF(TRIM(`Freight-Cost-Currency`), '') as freight_cost_currency,
        TRY_CAST(`Freight-Cost-Exchange-Rate` AS DECIMAL(18,8)) as freight_cost_exchange_rate,
        CAST(TRY_TO_TIMESTAMP(`Market-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as market_date,
        NULLIF(TRIM(`Alt-Invoice-Num`), '') as alt_invoice_num,
        TRY_CAST(`Misc-Cost-Amount@1` AS DECIMAL(38,2)) as misc_cost_amount_1,
        TRY_CAST(`Misc-Cost-Amount@2` AS DECIMAL(38,2)) as misc_cost_amount_2,
        TRY_CAST(`Misc-Cost-Amount@3` AS DECIMAL(38,2)) as misc_cost_amount_3,
        TRY_CAST(`Misc-Cost-Amount@4` AS DECIMAL(38,2)) as misc_cost_amount_4,
        TRY_CAST(`Misc-Cost-Amount@5` AS DECIMAL(38,2)) as misc_cost_amount_5,
        TRY_CAST(`Misc-Cost-Amount@6` AS DECIMAL(38,2)) as misc_cost_amount_6,
        TRY_CAST(`Misc-Cost-Amount@7` AS DECIMAL(38,2)) as misc_cost_amount_7,
        TRY_CAST(`Misc-Cost-Amount@8` AS DECIMAL(38,2)) as misc_cost_amount_8,
        TRY_CAST(`Misc-Cost-Amount@9` AS DECIMAL(38,2)) as misc_cost_amount_9,
        TRY_CAST(`Misc-Cost-Amount@10` AS DECIMAL(38,2)) as misc_cost_amount_10,
        TRY_CAST(`Misc-Cost-Percent@1` AS DECIMAL(18,2)) as misc_cost_percent_1,
        TRY_CAST(`Misc-Cost-Percent@2` AS DECIMAL(18,2)) as misc_cost_percent_2,
        TRY_CAST(`Misc-Cost-Percent@3` AS DECIMAL(18,2)) as misc_cost_percent_3,
        TRY_CAST(`Misc-Cost-Percent@4` AS DECIMAL(18,2)) as misc_cost_percent_4,
        TRY_CAST(`Misc-Cost-Percent@5` AS DECIMAL(18,2)) as misc_cost_percent_5,
        TRY_CAST(`Misc-Cost-Percent@6` AS DECIMAL(18,2)) as misc_cost_percent_6,
        TRY_CAST(`Misc-Cost-Percent@7` AS DECIMAL(18,2)) as misc_cost_percent_7,
        TRY_CAST(`Misc-Cost-Percent@8` AS DECIMAL(18,2)) as misc_cost_percent_8,
        TRY_CAST(`Misc-Cost-Percent@9` AS DECIMAL(18,2)) as misc_cost_percent_9,
        TRY_CAST(`Misc-Cost-Percent@10` AS DECIMAL(18,2)) as misc_cost_percent_10,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@1` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_1,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@2` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_2,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@3` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_3,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@4` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_4,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@5` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_5,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@6` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_6,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@7` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_7,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@8` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_8,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@9` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_9,
        TRY_CAST(`Misc-Cost-Max-Percent-Amount@10` AS DECIMAL(38,2)) as misc_cost_max_percent_amount_10,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@1` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_1,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@2` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_2,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@3` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_3,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@4` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_4,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@5` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_5,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@6` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_6,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@7` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_7,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@8` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_8,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@9` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_9,
        TRY_CAST(`Misc-Cost-Min-Percent-Amount@10` AS DECIMAL(38,2)) as misc_cost_min_percent_amount_10,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@1`), '') as misc_cost_gl_acct_ptr_1,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@2`), '') as misc_cost_gl_acct_ptr_2,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@3`), '') as misc_cost_gl_acct_ptr_3,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@4`), '') as misc_cost_gl_acct_ptr_4,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@5`), '') as misc_cost_gl_acct_ptr_5,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@6`), '') as misc_cost_gl_acct_ptr_6,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@7`), '') as misc_cost_gl_acct_ptr_7,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@8`), '') as misc_cost_gl_acct_ptr_8,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@9`), '') as misc_cost_gl_acct_ptr_9,
        NULLIF(TRIM(`Misc-Cost-GL-Acct-Ptr@10`), '') as misc_cost_gl_acct_ptr_10,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@1`), '') as misc_cogs_gl_acct_ptr_1,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@2`), '') as misc_cogs_gl_acct_ptr_2,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@3`), '') as misc_cogs_gl_acct_ptr_3,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@4`), '') as misc_cogs_gl_acct_ptr_4,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@5`), '') as misc_cogs_gl_acct_ptr_5,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@6`), '') as misc_cogs_gl_acct_ptr_6,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@7`), '') as misc_cogs_gl_acct_ptr_7,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@8`), '') as misc_cogs_gl_acct_ptr_8,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@9`), '') as misc_cogs_gl_acct_ptr_9,
        NULLIF(TRIM(`Misc-COGS-GL-Acct-Ptr@10`), '') as misc_cogs_gl_acct_ptr_10,
        TRY_CAST(`Misc-Charge-Threshold@1` AS DECIMAL(38,2)) as misc_charge_threshold_1,
        TRY_CAST(`Misc-Charge-Threshold@2` AS DECIMAL(38,2)) as misc_charge_threshold_2,
        TRY_CAST(`Misc-Charge-Threshold@3` AS DECIMAL(38,2)) as misc_charge_threshold_3,
        TRY_CAST(`Misc-Charge-Threshold@4` AS DECIMAL(38,2)) as misc_charge_threshold_4,
        TRY_CAST(`Misc-Charge-Threshold@5` AS DECIMAL(38,2)) as misc_charge_threshold_5,
        TRY_CAST(`Misc-Charge-Threshold@6` AS DECIMAL(38,2)) as misc_charge_threshold_6,
        TRY_CAST(`Misc-Charge-Threshold@7` AS DECIMAL(38,2)) as misc_charge_threshold_7,
        TRY_CAST(`Misc-Charge-Threshold@8` AS DECIMAL(38,2)) as misc_charge_threshold_8,
        TRY_CAST(`Misc-Charge-Threshold@9` AS DECIMAL(38,2)) as misc_charge_threshold_9,
        TRY_CAST(`Misc-Charge-Threshold@10` AS DECIMAL(38,2)) as misc_charge_threshold_10,
        TRY_CAST(`Misc-Charge-Threshold-Amount@1` AS DECIMAL(38,2)) as misc_charge_threshold_amount_1,
        TRY_CAST(`Misc-Charge-Threshold-Amount@2` AS DECIMAL(38,2)) as misc_charge_threshold_amount_2,
        TRY_CAST(`Misc-Charge-Threshold-Amount@3` AS DECIMAL(38,2)) as misc_charge_threshold_amount_3,
        TRY_CAST(`Misc-Charge-Threshold-Amount@4` AS DECIMAL(38,2)) as misc_charge_threshold_amount_4,
        TRY_CAST(`Misc-Charge-Threshold-Amount@5` AS DECIMAL(38,2)) as misc_charge_threshold_amount_5,
        TRY_CAST(`Misc-Charge-Threshold-Amount@6` AS DECIMAL(38,2)) as misc_charge_threshold_amount_6,
        TRY_CAST(`Misc-Charge-Threshold-Amount@7` AS DECIMAL(38,2)) as misc_charge_threshold_amount_7,
        TRY_CAST(`Misc-Charge-Threshold-Amount@8` AS DECIMAL(38,2)) as misc_charge_threshold_amount_8,
        TRY_CAST(`Misc-Charge-Threshold-Amount@9` AS DECIMAL(38,2)) as misc_charge_threshold_amount_9,
        TRY_CAST(`Misc-Charge-Threshold-Amount@10` AS DECIMAL(38,2)) as misc_charge_threshold_amount_10,
        NULLIF(TRIM(`Misc-Shipment-Charge@1`), '') as misc_shipment_charge_1,
        NULLIF(TRIM(`Misc-Shipment-Charge@2`), '') as misc_shipment_charge_2,
        NULLIF(TRIM(`Misc-Shipment-Charge@3`), '') as misc_shipment_charge_3,
        NULLIF(TRIM(`Misc-Shipment-Charge@4`), '') as misc_shipment_charge_4,
        NULLIF(TRIM(`Misc-Shipment-Charge@5`), '') as misc_shipment_charge_5,
        NULLIF(TRIM(`Misc-Shipment-Charge@6`), '') as misc_shipment_charge_6,
        NULLIF(TRIM(`Misc-Shipment-Charge@7`), '') as misc_shipment_charge_7,
        NULLIF(TRIM(`Misc-Shipment-Charge@8`), '') as misc_shipment_charge_8,
        NULLIF(TRIM(`Misc-Shipment-Charge@9`), '') as misc_shipment_charge_9,
        NULLIF(TRIM(`Misc-Shipment-Charge@10`), '') as misc_shipment_charge_10,
        IF(UPPER(TRIM(`Multiple-Payment-Invoice`))='TRUE',TRUE,IF(UPPER(TRIM(`Multiple-Payment-Invoice`))='FALSE',FALSE,NULL)) as multiple_payment_invoice,
        TRY_CAST(`Multiple-Payment-Invoice-Num` AS DECIMAL(18,0)) as multiple_payment_invoice_num,
        NULLIF(TRIM(`Multiple-Payment-Invoice-NumCV`), '') as multiple_payment_invoice_numcv,
        NULLIF(TRIM(`Reserved-Invoice-Numbers`), '') as reserved_invoice_numbers,
        IF(UPPER(TRIM(`CUPS-Agreement-Claim-Flag`))='TRUE',TRUE,IF(UPPER(TRIM(`CUPS-Agreement-Claim-Flag`))='FALSE',FALSE,NULL)) as cups_agreement_claim_flag,
        NULLIF(TRIM(`Originating-Warehouse`), '') as originating_warehouse,
        IF(UPPER(TRIM(`Misc-Perc-Total@1`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@1`))='FALSE',FALSE,NULL)) as misc_perc_total_1,
        IF(UPPER(TRIM(`Misc-Perc-Total@2`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@2`))='FALSE',FALSE,NULL)) as misc_perc_total_2,
        IF(UPPER(TRIM(`Misc-Perc-Total@3`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@3`))='FALSE',FALSE,NULL)) as misc_perc_total_3,
        IF(UPPER(TRIM(`Misc-Perc-Total@4`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@4`))='FALSE',FALSE,NULL)) as misc_perc_total_4,
        IF(UPPER(TRIM(`Misc-Perc-Total@5`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@5`))='FALSE',FALSE,NULL)) as misc_perc_total_5,
        IF(UPPER(TRIM(`Misc-Perc-Total@6`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@6`))='FALSE',FALSE,NULL)) as misc_perc_total_6,
        IF(UPPER(TRIM(`Misc-Perc-Total@7`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@7`))='FALSE',FALSE,NULL)) as misc_perc_total_7,
        IF(UPPER(TRIM(`Misc-Perc-Total@8`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@8`))='FALSE',FALSE,NULL)) as misc_perc_total_8,
        IF(UPPER(TRIM(`Misc-Perc-Total@9`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@9`))='FALSE',FALSE,NULL)) as misc_perc_total_9,
        IF(UPPER(TRIM(`Misc-Perc-Total@10`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Perc-Total@10`))='FALSE',FALSE,NULL)) as misc_perc_total_10,
        NULLIF(TRIM(`Vendor-Tracking-Number`), '') as vendor_tracking_number,
        TRY_CAST(`Spare-Decimal-3` AS DECIMAL(38,10)) as spare_decimal_3,
        IF(UPPER(TRIM(`Collect-Payment-Now`))='TRUE',TRUE,IF(UPPER(TRIM(`Collect-Payment-Now`))='FALSE',FALSE,NULL)) as collect_payment_now,
        IF(UPPER(TRIM(`Hold-Commission`))='TRUE',TRUE,IF(UPPER(TRIM(`Hold-Commission`))='FALSE',FALSE,NULL)) as hold_commission,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@1`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@1`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_1,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@2`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@2`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_2,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@3`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@3`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_3,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@4`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@4`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_4,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@5`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@5`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_5,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@6`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@6`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_6,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@7`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@7`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_7,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@8`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@8`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_8,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@9`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@9`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_9,
        IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@10`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Sales-Agent-Pay@10`))='FALSE',FALSE,NULL)) as misc_sales_agent_pay_10,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@1`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@1`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_1,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@2`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@2`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_2,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@3`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@3`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_3,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@4`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@4`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_4,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@5`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@5`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_5,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@6`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@6`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_6,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@7`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@7`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_7,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@8`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@8`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_8,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@9`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@9`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_9,
        IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@10`))='TRUE',TRUE,IF(UPPER(TRIM(`Misc-Create-Offsetting-AP@10`))='FALSE',FALSE,NULL)) as misc_create_offsetting_ap_10,
        NULLIF(TRIM(`NC-Type`), '') as nc_type,
        TRY_CAST(`Non-Conformance-Num` AS DECIMAL(18,0)) as non_conformance_num,
        NULLIF(TRIM(`Non-Conformance-NumCV`), '') as non_conformance_numcv,
        NULLIF(TRIM(`Commission-Comment`), '') as commission_comment,
        NULLIF(TRIM(`Payment-Method`), '') as payment_method,
        IF(UPPER(TRIM(`Counter-Sale`))='TRUE',TRUE,IF(UPPER(TRIM(`Counter-Sale`))='FALSE',FALSE,NULL)) as counter_sale,
        IF(UPPER(TRIM(`Spare-Logical-6`))='TRUE',TRUE,IF(UPPER(TRIM(`Spare-Logical-6`))='FALSE',FALSE,NULL)) as spare_logical_6,
        IF(UPPER(TRIM(`Spare-Logical-7`))='TRUE',TRUE,IF(UPPER(TRIM(`Spare-Logical-7`))='FALSE',FALSE,NULL)) as spare_logical_7,
        NULLIF(TRIM(`TA-Order-Num`), '') as ta_order_num,
        NULLIF(TRIM(`Spare-Char-7`), '') as spare_char_7,
        TRY_CAST(`Spare-Decimal-4` AS DECIMAL(38,10)) as spare_decimal_4,
        NULLIF(TRIM(`Spare-Char-8`), '') as spare_char_8,
        NULLIF(TRIM(`Spare-Char-9`), '') as spare_char_9,
        NULLIF(TRIM(`Spare-Char-10`), '') as spare_char_10,
        TRY_CAST(`Spare-Decimal-5` AS DECIMAL(38,10)) as spare_decimal_5,
        IF(UPPER(TRIM(`Spare-Logical-8`))='TRUE',TRUE,IF(UPPER(TRIM(`Spare-Logical-8`))='FALSE',FALSE,NULL)) as spare_logical_8,
        IF(UPPER(TRIM(`Spare-Logical-9`))='TRUE',TRUE,IF(UPPER(TRIM(`Spare-Logical-9`))='FALSE',FALSE,NULL)) as spare_logical_9
from {{ source('bronze', 'invoice_hdr') }}
