select
    source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Facility`), '') as facility,
        NULLIF(TRIM(`product-key`), '') as product_key,
        NULLIF(TRIM(`packaging-key`), '') as packaging_key,
        TRY_CAST(`standard-cost` AS DECIMAL(18,4)) as standard_cost,
        CAST(TRY_TO_TIMESTAMP(`standard-cost-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as standard_cost_date,
        TRY_CAST(`average-cost` AS DECIMAL(18,4)) as average_cost,
        TRY_CAST(`last-cost` AS DECIMAL(18,4)) as last_cost,
        CAST(TRY_TO_TIMESTAMP(`last-cost-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_cost_date,
        TRY_CAST(`replacement-cost` AS DECIMAL(18,4)) as replacement_cost,
        TRY_CAST(`selling-cost` AS DECIMAL(18,4)) as selling_cost,
        TRY_CAST(`Inv-Amount` AS DECIMAL(18,4)) as inv_amount,
        NULLIF(TRIM(`Inv-Status`), '') as inv_status,
        IF(UPPER(TRIM(`Inv-Flag`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag,
        NULLIF(TRIM(`Unit-of-Meas`), '') as unit_of_meas,
        TRY_CAST(`OH-packages` AS DECIMAL(18,0)) as oh_packages,
        IF(UPPER(TRIM(`Lot-Controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Lot-Controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as lot_controlled,
        IF(UPPER(TRIM(`Location-controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Location-controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as location_controlled,
        IF(UPPER(TRIM(`serial-number-controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`serial-number-controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as serial_number_controlled,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyyMMddHH:mm:ss') as update_date_time,
        NULLIF(TRIM(`User-1`), '') as user_1,
        TRY_CAST(`Sequence` AS DECIMAL(18,0)) as sequence,
        NULLIF(TRIM(`Facility-Type`), '') as facility_type,
        IF(UPPER(TRIM(`Internal-Warehouse`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Internal-Warehouse`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as internal_warehouse,
        TRY_CAST(`Reorder-Qty` AS DECIMAL(18,2)) as reorder_qty,
        CAST(TRY_TO_TIMESTAMP(`Last-Counted-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_counted_date,
        NULLIF(TRIM(`ABC-Code`), '') as abc_code,
        NULLIF(TRIM(`Product-Code`), '') as product_code,
        NULLIF(TRIM(`Packaging-Code`), '') as packaging_code,
        NULLIF(TRIM(`Prod-Pkg-Code`), '') as prod_pkg_code,
        TRY_CAST(`Lead-Days-Ship-Domestic` AS DECIMAL(10,0)) as lead_days_ship_domestic,
        TRY_CAST(`Lead-Days-Ship-Intl` AS DECIMAL(10,0)) as lead_days_ship_intl,
        TRY_CAST(`Lead-Hours-Ship-Domestic` AS DECIMAL(10,0)) as lead_hours_ship_domestic,
        TRY_CAST(`Lead-Hours-Ship-Intl` AS DECIMAL(10,0)) as lead_hours_ship_intl,
        TRY_CAST(`Weight` AS DECIMAL(18,4)) as weight,
        NULLIF(TRIM(`Weight-UM`), '') as weight_um,
        IF(UPPER(TRIM(`Facility-Display`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Facility-Display`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as facility_display,
        IF(UPPER(TRIM(`Active`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Active`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as active,
        NULLIF(TRIM(`Supplier-ID`), '') as supplier_id,
        TRY_CAST(`Supp-Ship-From-ID` AS DECIMAL(10,0)) as supp_ship_from_id,
        NULLIF(TRIM(`Purchasing-Agent`), '') as purchasing_agent,
        NULLIF(TRIM(`User-Group-QC-Results`), '') as user_group_qc_results,
        TRY_CAST(`Maximum-Capacity` AS DECIMAL(18,2)) as maximum_capacity,
        NULLIF(TRIM(`EMail-Address`), '') as email_address,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyyMMddHH:mm:ss') as created_date_time,
        TRY_CAST(`Forecast-MAD` AS DECIMAL(18,2)) as forecast_mad,
        TRY_CAST(`Forecast-Calc-Safety-Stock` AS DECIMAL(18,2)) as forecast_calc_safety_stock,
        TRY_CAST(`Forecast-Calc-Reorder-Target` AS DECIMAL(18,2)) as forecast_calc_reorder_target,
        IF(UPPER(TRIM(`Non-Stock`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Non-Stock`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as non_stock,
        TRY_CAST(`Order-Frequency` AS DECIMAL(10,0)) as order_frequency,
        NULLIF(TRIM(`Inventory-Label-Type`), '') as inventory_label_type,
        TRY_CAST(`Last-Forecast-Safety-Factor` AS DECIMAL(10,2)) as last_forecast_safety_factor,
        TRY_CAST(`Last-Forecast-Lead-Time` AS DECIMAL(10,0)) as last_forecast_lead_time,
        TRY_CAST(`Last-Forecast-Order-Frequency` AS DECIMAL(10,0)) as last_forecast_order_frequency,
        CAST(TRY_TO_TIMESTAMP(`Last-Forecast-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_forecast_date,
        NULLIF(TRIM(`Last-Forecast-Period`), '') as last_forecast_period,
        TRY_CAST(`Last-Forecast-Days-In-Week` AS DECIMAL(10,0)) as last_forecast_days_in_week,
        IF(UPPER(TRIM(`Exclude-From-Auto-Lot-Alloc`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Exclude-From-Auto-Lot-Alloc`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as exclude_from_auto_lot_alloc,
        NULLIF(TRIM(`Recommended-Putaway-Location`), '') as recommended_putaway_location,
        NULLIF(TRIM(`Freight-Transfer-Rate-UM`), '') as freight_transfer_rate_um,
        TRY_CAST(`Freight-Transfer-Rate` AS DECIMAL(18,4)) as freight_transfer_rate,
        NULLIF(TRIM(`Drum-Off-Packaging-Code`), '') as drum_off_packaging_code,
        NULLIF(TRIM(`PO-Receipt-Spec-ID`), '') as po_receipt_spec_id,
        TRY_CAST(`Load-Duration` AS DECIMAL(10,0)) as load_duration,
        NULLIF(TRIM(`Default-Load-Slot`), '') as default_load_slot,
        NULLIF(TRIM(`Product-Obsolete`), '') as product_obsolete,
        TRY_CAST(`Spare-Decimal-1` AS DECIMAL(20,10)) as spare_decimal_1,
        TRY_CAST(`Spare-Decimal-2` AS DECIMAL(20,10)) as spare_decimal_2,
        TRY_CAST(`Spare-Decimal-3` AS DECIMAL(20,10)) as spare_decimal_3,
        TRY_CAST(`Spare-Decimal-4` AS DECIMAL(20,10)) as spare_decimal_4,
        IF(UPPER(TRIM(`Spare-Logical-1`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-1`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as spare_logical_1,
        NULLIF(TRIM(`Spare-Char-2`), '') as spare_char_2,
        NULLIF(TRIM(`Spare-Char-3`), '') as spare_char_3,
        TRY_CAST(`Superfund-Rate` AS DECIMAL(18,4)) as superfund_rate,
        IF(UPPER(TRIM(`Override-Product-Superfund-Rate`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Override-Product-Superfund-Rate`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as override_product_superfund_rate
from {{ source('bronze', 'whs_prod_pkg') }}
