select
`SOURCE_DATABASE` as source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        TRY_CAST(`Invoice-Num` AS DECIMAL(18,0)) as invoice_num,
        NULLIF(TRIM(`Invoice-NumCV`), '') as invoice_numcv,
        TRY_CAST(`Seq-Num` AS DECIMAL(18,0)) as seq_num,
        NULLIF(TRIM(`Seq-NumCV`), '') as seq_numcv,
        TRY_CAST(`Tran-Num` AS DECIMAL(18,0)) as tran_num,
        NULLIF(TRIM(`Product-Key`), '') as product_key,
        NULLIF(TRIM(`Packaging-Key`), '') as packaging_key,
        NULLIF(TRIM(`Ship-From-Warehouse`), '') as ship_from_warehouse,
        TRY_CAST(`Quantity-Shipped` AS DECIMAL(18,2)) as quantity_shipped,
        NULLIF(TRIM(`Qty-UM`), '') as qty_um,
        TRY_CAST(`Net-Price` AS DECIMAL(18,4)) as net_price,
        TRY_CAST(`Gross-Price` AS DECIMAL(18,4)) as gross_price,
        TRY_CAST(`Disc-1` AS DECIMAL(9,2)) as disc_1,
        TRY_CAST(`Disc-2` AS DECIMAL(9,2)) as disc_2,
        TRY_CAST(`Allowance` AS DECIMAL(18,4)) as allowance,
        NULLIF(TRIM(`Price-UM`), '') as price_um,
        TRY_CAST(`Container-Deposit` AS DECIMAL(18,2)) as container_deposit,
        TRY_CAST(`Commission-Rate` AS DECIMAL(18,4)) as commission_rate,
        NULLIF(TRIM(`Commission-Type`), '') as commission_type,
        TRY_CAST(`Freight-Rate` AS DECIMAL(18,4)) as freight_rate,
        NULLIF(TRIM(`Freight-Rate-UM`), '') as freight_rate_um,
        TRY_CAST(`Freight-Weight` AS DECIMAL(18,2)) as freight_weight,
        NULLIF(TRIM(`Freight-Weight-UM`), '') as freight_weight_um,
        IF(UPPER(TRIM(`Sales-Taxable`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Sales-Taxable`))='FALSE', FALSE, NULL)) as is_sales_taxable,
        TRY_CAST(`Standard-Cost` AS DECIMAL(18,4)) as standard_cost,
        TRY_CAST(`Average-Cost` AS DECIMAL(18,4)) as average_cost,
        TRY_CAST(`Last-Cost` AS DECIMAL(18,4)) as last_cost,
        TRY_CAST(`Replacement-Cost` AS DECIMAL(18,4)) as replacement_cost,
        TRY_CAST(`Selling-Cost` AS DECIMAL(18,4)) as selling_cost,
        IF(UPPER(TRIM(`Closed`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Closed`))='FALSE', FALSE, NULL)) as is_closed,
        IF(UPPER(TRIM(`Cancelled`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Cancelled`))='FALSE', FALSE, NULL)) as is_cancelled,
        NULLIF(TRIM(`Cancel-by`), '') as cancel_by,
        CAST(TRY_TO_TIMESTAMP(`Cancel-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cancel_date,
        NULLIF(TRIM(`Cancel-time`), '') as cancel_time,
        NULLIF(TRIM(`Cancel-Reason`), '') as cancel_reason,
        TRY_CAST(`Internal-Key` AS DECIMAL(18,0)) as internal_key,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Update-Date-Time`), '') as update_date_time,
        NULLIF(TRIM(`User-1`), '') as user_1,
        TRY_CAST(`Bill-of-Lading-Num` AS DECIMAL(18,0)) as bill_of_lading_num,
        TRY_CAST(`Sale-Measure` AS DECIMAL(18,2)) as sale_measure,
        NULLIF(TRIM(`Sale-UM`), '') as sale_um,
        NULLIF(TRIM(`Sale-Pkg`), '') as sale_pkg,
        TRY_CAST(`Merchandise` AS DECIMAL(38,2)) as merchandise,
        IF(UPPER(TRIM(`Posted-in-Summary-Entry`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Posted-in-Summary-Entry`))='FALSE', FALSE, NULL)) as is_posted_in_summary_entry,
        NULLIF(TRIM(`Journal-Number`), '') as journal_number,
        TRY_CAST(`Order-Trl-Seq-Num` AS DECIMAL(18,0)) as order_trl_seq_num,
        NULLIF(TRIM(`Lot-Code`), '') as lot_code,
        TRY_CAST(`Pkg-Document` AS DECIMAL(18,0)) as pkg_document,
        TRY_CAST(`Posting-Period` AS DECIMAL(9,0)) as posting_period,
        TRY_CAST(`Posting-Year` AS DECIMAL(9,0)) as posting_year,
        NULLIF(TRIM(`Year-Period`), '') as year_period,
        NULLIF(TRIM(`CM-DM-Type`), '') as cm_dm_type,
        NULLIF(TRIM(`Order-Type`), '') as order_type,
        TRY_CAST(`Associated-Seq-Num` AS DECIMAL(18,0)) as associated_seq_num,
        TRY_CAST(`Cost` AS DECIMAL(18,4)) as cost,
        NULLIF(TRIM(`Type-1`), '') as type_1,
        NULLIF(TRIM(`Return-Warehouse`), '') as return_warehouse,
        NULLIF(TRIM(`Return-Location`), '') as return_location,
        NULLIF(TRIM(`Cust-Key`), '') as cust_key,
        NULLIF(TRIM(`Cust-ID`), '') as cust_id,
        NULLIF(TRIM(`Product-Code`), '') as product_code,
        NULLIF(TRIM(`Packaging-Code`), '') as packaging_code,
        NULLIF(TRIM(`Prod-Pkg-Code`), '') as prod_pkg_code,
        NULLIF(TRIM(`Sales-Tax-Code`), '') as sales_tax_code,
        IF(UPPER(TRIM(`Invalid-Sales-Tax-Code`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Invalid-Sales-Tax-Code`))='FALSE', FALSE, NULL)) as is_invalid_sales_tax_code,
        NULLIF(TRIM(`Supplier-Key`), '') as supplier_key,
        TRY_CAST(`Supplier-Ship-From-Seq-Num` AS DECIMAL(18,0)) as supplier_ship_from_seq_num,
        TRY_CAST(`Container-Service` AS DECIMAL(18,2)) as container_service,
        TRY_CAST(`COGS` AS DECIMAL(38,2)) as cogs,
        NULLIF(TRIM(`COGS-Journal-Number`), '') as cogs_journal_number,
        IF(UPPER(TRIM(`Use-Freight-Rate`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Use-Freight-Rate`))='FALSE', FALSE, NULL)) as is_use_freight_rate,
        NULLIF(TRIM(`Price-Remark`), '') as price_remark,
        NULLIF(TRIM(`Freight-Remark`), '') as freight_remark,
        NULLIF(TRIM(`Freight-Class`), '') as freight_class,
        TRY_CAST(`Freight-Cost` AS DECIMAL(18,4)) as freight_cost,
        TRY_CAST(`Extended-Freight-Cost` AS DECIMAL(38,2)) as extended_freight_cost,
        TRY_CAST(`Extended-Freight-Rate` AS DECIMAL(38,2)) as extended_freight_rate,
        IF(UPPER(TRIM(`Charge-Customer-Freight`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Charge-Customer-Freight`))='FALSE', FALSE, NULL)) as is_charge_customer_freight,
        IF(UPPER(TRIM(`Include-Freight-Cost-in-COGS`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Include-Freight-Cost-in-COGS`))='FALSE', FALSE, NULL)) as is_include_freight_cost_in_cogs,
        TRY_CAST(`Cust-Ship-To-ID` AS DECIMAL(18,0)) as cust_ship_to_id,
        NULLIF(TRIM(`Shipto-State`), '') as shipto_state,
        NULLIF(TRIM(`Shipto-Country`), '') as shipto_country,
        CAST(TRY_TO_TIMESTAMP(`Sales-Tax-Start-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as sales_tax_start_date,
        TRY_CAST(`Sales-Tax-Rate` AS DECIMAL(18,4)) as sales_tax_rate,
        NULLIF(TRIM(`Tax-State`), '') as tax_state,
        NULLIF(TRIM(`Tax-Country`), '') as tax_country,
        IF(UPPER(TRIM(`Cust-Prod-Apply-Sales-Tax`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Cust-Prod-Apply-Sales-Tax`))='FALSE', FALSE, NULL)) as is_cust_prod_apply_sales_tax,
        IF(UPPER(TRIM(`Cust-Prod-Apply-Superfund`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Cust-Prod-Apply-Superfund`))='FALSE', FALSE, NULL)) as is_cust_prod_apply_superfund,
        IF(UPPER(TRIM(`Cust-Prod-Apply-CFC-Tax`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Cust-Prod-Apply-CFC-Tax`))='FALSE', FALSE, NULL)) as is_cust_prod_apply_cfc_tax,
        IF(UPPER(TRIM(`Cust-Prod-Apply-Marine-Tax`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Cust-Prod-Apply-Marine-Tax`))='FALSE', FALSE, NULL)) as is_cust_prod_apply_marine_tax,
        IF(UPPER(TRIM(`Excise-Tax-Applied`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Excise-Tax-Applied`))='FALSE', FALSE, NULL)) as is_excise_tax_applied,
        IF(UPPER(TRIM(`Superfund-Taxable`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Superfund-Taxable`))='FALSE', FALSE, NULL)) as is_superfund_taxable,
        IF(UPPER(TRIM(`CFC-Taxable`))='TRUE', TRUE,
      IF(UPPER(TRIM(`CFC-Taxable`))='FALSE', FALSE, NULL)) as is_cfc_taxable,
        IF(UPPER(TRIM(`Marine-Taxable`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Marine-Taxable`))='FALSE', FALSE, NULL)) as is_marine_taxable,
        TRY_CAST(`Superfund-Rate` AS DECIMAL(18,6)) as superfund_rate,
        TRY_CAST(`CFC-Rate` AS DECIMAL(18,6)) as cfc_rate,
        TRY_CAST(`Marine-Tax-Rate` AS DECIMAL(18,6)) as marine_tax_rate,
        NULLIF(TRIM(`Tax-UM`), '') as tax_um,
        NULLIF(TRIM(`Tax-Group`), '') as tax_group,
        NULLIF(TRIM(`Invoice-Currency`), '') as invoice_currency,
        TRY_CAST(`Sales-Tax` AS DECIMAL(38,2)) as sales_tax,
        TRY_CAST(`Exempt-Sales-Tax` AS DECIMAL(38,2)) as exempt_sales_tax,
        TRY_CAST(`Excise-Tax` AS DECIMAL(38,2)) as excise_tax,
        TRY_CAST(`Exempt-Excise-Tax` AS DECIMAL(38,2)) as exempt_excise_tax,
        TRY_CAST(`Superfund` AS DECIMAL(38,2)) as superfund,
        TRY_CAST(`CFC-Tax` AS DECIMAL(38,2)) as cfc_tax,
        TRY_CAST(`Marine-Tax` AS DECIMAL(38,2)) as marine_tax,
        CAST(TRY_TO_TIMESTAMP(`Ship-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as ship_date,
        CAST(TRY_TO_TIMESTAMP(`Invoice-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as invoice_date,
        TRY_CAST(`Rebate-Amount` AS DECIMAL(18,4)) as rebate_amount,
        NULLIF(TRIM(`Rebate-GL-Acct-Ptr`), '') as rebate_gl_acct_ptr,
        TRY_CAST(`Rebate-Voucher-Number` AS DECIMAL(18,0)) as rebate_voucher_number,
        NULLIF(TRIM(`Rebate-Voucher-Type`), '') as rebate_voucher_type,
        IF(UPPER(TRIM(`Rebate-Voucher-Generated`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Rebate-Voucher-Generated`))='FALSE', FALSE, NULL)) as is_rebate_voucher_generated,
        NULLIF(TRIM(`Rebate-Supplier-ID`), '') as rebate_supplier_id,
        TRY_CAST(`Rebate-Supp-Ship-From-ID` AS DECIMAL(18,0)) as rebate_supp_ship_from_id,
        NULLIF(TRIM(`Cost-File`), '') as cost_file,
        NULLIF(TRIM(`Cost-Method`), '') as cost_method,
        IF(UPPER(TRIM(`Rebate-Apply`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Rebate-Apply`))='FALSE', FALSE, NULL)) as is_rebate_apply,
        TRY_CAST(`Supplier-Commission-Percentage` AS DECIMAL(18,4)) as supplier_commission_percentage,
        IF(UPPER(TRIM(`Profit-Hold`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Profit-Hold`))='FALSE', FALSE, NULL)) as is_profit_hold,
        TRY_CAST(`Ship-Tran-Num` AS DECIMAL(18,0)) as ship_tran_num,
        TRY_CAST(`Rebate-Extension` AS DECIMAL(38,2)) as rebate_extension,
        NULLIF(TRIM(`Security-Access-2`), '') as security_access_2,
        TRY_CAST(`Comp-TOT-Sales-Tax-Merch@1` AS DECIMAL(38,2)) as comp_tot_sales_tax_merch_1,
        TRY_CAST(`Comp-TOT-Sales-Tax-Merch@2` AS DECIMAL(38,2)) as comp_tot_sales_tax_merch_2,
        TRY_CAST(`Comp-TOT-Sales-Tax-Merch@3` AS DECIMAL(38,2)) as comp_tot_sales_tax_merch_3,
        NULLIF(TRIM(`Comp-Tax-Rate-Desc@1`), '') as comp_tax_rate_desc_1,
        NULLIF(TRIM(`Comp-Tax-Rate-Desc@2`), '') as comp_tax_rate_desc_2,
        NULLIF(TRIM(`Comp-Tax-Rate-Desc@3`), '') as comp_tax_rate_desc_3,
        TRY_CAST(`Comp-Tax-Rate@1` AS DECIMAL(18,4)) as comp_tax_rate_1,
        TRY_CAST(`Comp-Tax-Rate@2` AS DECIMAL(18,4)) as comp_tax_rate_2,
        TRY_CAST(`Comp-Tax-Rate@3` AS DECIMAL(18,4)) as comp_tax_rate_3,
        NULLIF(TRIM(`Commission-Calc-Qty`), '') as commission_calc_qty,
        NULLIF(TRIM(`Auto-Charge-DelType`), '') as auto_charge_deltype,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`Posted-Freight-Cost` AS DECIMAL(18,4)) as posted_freight_cost,
        TRY_CAST(`Posted-Extended-Freight-Cost` AS DECIMAL(38,2)) as posted_extended_freight_cost,
        IF(UPPER(TRIM(`Zero-Commission`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Zero-Commission`))='FALSE', FALSE, NULL)) as is_zero_commission,
        IF(UPPER(TRIM(`Freight-Cost-Adjusted`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Freight-Cost-Adjusted`))='FALSE', FALSE, NULL)) as is_freight_cost_adjusted,
        TRY_CAST(`Truck-Run-Key` AS DECIMAL(18,0)) as truck_run_key,
        TRY_CAST(`Customer-PO-Line-Num` AS DECIMAL(18,0)) as customer_po_line_num,
        TRY_CAST(`Spare-Integer-3` AS DECIMAL(18,0)) as spare_integer_3,
        NULLIF(TRIM(`Created-Date-Time`), '') as created_date_time,
        TRY_CAST(`Outbound-Cost` AS DECIMAL(38,2)) as outbound_cost,
        TRY_CAST(`Outbound-Charge` AS DECIMAL(38,2)) as outbound_charge,
        IF(UPPER(TRIM(`Return-No-Inventory`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Return-No-Inventory`))='FALSE', FALSE, NULL)) as is_return_no_inventory,
        NULLIF(TRIM(`Return-Reason-Code`), '') as return_reason_code,
        NULLIF(TRIM(`Issue-Hdr-Excise-Tax-List`), '') as issue_hdr_excise_tax_list,
        CAST(TRY_TO_TIMESTAMP(`Market-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as market_date,
        TRY_CAST(`COGS-RM` AS DECIMAL(38,2)) as cogs_rm,
        TRY_CAST(`COGS-Labor` AS DECIMAL(38,2)) as cogs_labor,
        TRY_CAST(`COGS-OC` AS DECIMAL(38,2)) as cogs_oc,
        TRY_CAST(`COGS-Misc` AS DECIMAL(38,2)) as cogs_misc,
        TRY_CAST(`COGS-ADJ` AS DECIMAL(38,2)) as cogs_adj,
        TRY_CAST(`COGS-Reference-ADJ` AS DECIMAL(38,2)) as cogs_reference_adj,
        NULLIF(TRIM(`COGS-Breakout-Parameters`), '') as cogs_breakout_parameters,
        NULLIF(TRIM(`COGS-Breakout-Warnings`), '') as cogs_breakout_warnings,
        TRY_CAST(`Spare-Decimal-3` AS DECIMAL(38,10)) as spare_decimal_3,
        TRY_CAST(`Master-BOL-ID` AS DECIMAL(18,0)) as master_bol_id,
        NULLIF(TRIM(`CUPS-Agreement-Claim-ID`), '') as cups_agreement_claim_id,
        CAST(TRY_TO_TIMESTAMP(`CUPS-Agreement-Claim-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cups_agreement_claim_date,
        TRY_CAST(`CUPS-Accrual-Rate` AS DECIMAL(18,4)) as cups_accrual_rate,
        NULLIF(TRIM(`CUPS-Accrual-UM`), '') as cups_accrual_um,
        TRY_CAST(`Market-Cost` AS DECIMAL(18,4)) as market_cost,
        TRY_CAST(`Volume-Credit-Pct-SlsAgent-1` AS DECIMAL(9,2)) as volume_credit_pct_slsagent_1,
        TRY_CAST(`Calc-Base-Volume-Credit-Amt` AS DECIMAL(38,2)) as calc_base_volume_credit_amt,
        TRY_CAST(`User-Base-Volume-Credit-Amt` AS DECIMAL(38,2)) as user_base_volume_credit_amt,
        TRY_CAST(`Volume-Credit-Amt-SlsAgent-1` AS DECIMAL(38,2)) as volume_credit_amt_slsagent_1,
        TRY_CAST(`Volume-Credit-Amt-SlsAgent-2` AS DECIMAL(38,2)) as volume_credit_amt_slsagent_2,
        TRY_CAST(`Commission-Pct-SlsAgent-1` AS DECIMAL(9,2)) as commission_pct_slsagent_1,
        TRY_CAST(`Calc-Base-Commission-Amt` AS DECIMAL(38,2)) as calc_base_commission_amt,
        TRY_CAST(`User-Base-Commission-Amt` AS DECIMAL(38,2)) as user_base_commission_amt,
        TRY_CAST(`Commission-Amt-SlsAgent-1` AS DECIMAL(38,2)) as commission_amt_slsagent_1,
        TRY_CAST(`Commission-Amt-SlsAgent-2` AS DECIMAL(38,2)) as commission_amt_slsagent_2,
        IF(UPPER(TRIM(`Sales-Agent-Pay`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Sales-Agent-Pay`))='FALSE', FALSE, NULL)) as is_sales_agent_pay,
        TRY_CAST(`Volume-Credit-Pct-SlsAgent-2` AS DECIMAL(9,2)) as volume_credit_pct_slsagent_2,
        TRY_CAST(`Commission-Pct-SlsAgent-2` AS DECIMAL(9,2)) as commission_pct_slsagent_2,
        TRY_CAST(`Company-Discount` AS DECIMAL(9,2)) as company_discount,
        TRY_CAST(`SlsAgent-Discount` AS DECIMAL(9,2)) as slsagent_discount,
        TRY_CAST(`Product-Commission-Pct` AS DECIMAL(9,2)) as product_commission_pct,
        TRY_CAST(`User-Product-Commission-Pct` AS DECIMAL(9,2)) as user_product_commission_pct,
        TRY_CAST(`Bonus-Prod-Class-Amt-SlsAgent-1` AS DECIMAL(18,0)) as bonus_prod_class_amt_slsagent_1,
        TRY_CAST(`Bonus-Prod-Class-Amt-SlsAgent-2` AS DECIMAL(18,0)) as bonus_prod_class_amt_slsagent_2,
        IF(UPPER(TRIM(`DM-Product`))='TRUE', TRUE,
      IF(UPPER(TRIM(`DM-Product`))='FALSE', FALSE, NULL)) as is_dm_product,
        NULLIF(TRIM(`Spare-Char-3`), '') as spare_char_3,
        IF(UPPER(TRIM(`Added-During-Inv-Mtn`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Added-During-Inv-Mtn`))='FALSE', FALSE, NULL)) as is_added_during_inv_mtn,
        TRY_CAST(`Spare-Decimal-4` AS DECIMAL(38,10)) as spare_decimal_4,
        TRY_CAST(`Spare-Decimal-5` AS DECIMAL(38,10)) as spare_decimal_5,
        IF(UPPER(TRIM(`Spare-Logical-5`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-5`))='FALSE', FALSE, NULL)) as is_spare_logical_5,
        IF(UPPER(TRIM(`TA-RentalAutoRenew`))='TRUE', TRUE,
      IF(UPPER(TRIM(`TA-RentalAutoRenew`))='FALSE', FALSE, NULL)) as is_ta_rentalautorenew,
        TRY_CAST(`TA-ID` AS DECIMAL(18,0)) as ta_id,
        IF(UPPER(TRIM(`Spare-Logical-6`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-6`))='FALSE', FALSE, NULL)) as is_spare_logical_6,
        IF(UPPER(TRIM(`Spare-Logical-7`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-7`))='FALSE', FALSE, NULL)) as is_spare_logical_7,
        IF(UPPER(TRIM(`Auto-Charge`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Auto-Charge`))='FALSE', FALSE, NULL)) as is_auto_charge,
        NULLIF(TRIM(`Auto-Charge-Details`), '') as auto_charge_details,
        NULLIF(TRIM(`Auto-Charge-Group`), '') as auto_charge_group,
        TRY_CAST(`Spare-Integer-4` AS DECIMAL(18,0)) as spare_integer_4,
        IF(UPPER(TRIM(`Spare-Logical-8`))='TRUE', TRUE,
      IF(UPPER(TRIM(`Spare-Logical-8`))='FALSE', FALSE, NULL)) as is_spare_logical_8,
        NULLIF(TRIM(`Spare-Char-4`), '') as spare_char_4,
        NULLIF(TRIM(`Spare-Char-5`), '') as spare_char_5,
        NULLIF(TRIM(`Spare-Char-6`), '') as spare_char_6
from {{ source('bronze', 'invoice_trl') }}
