select
    source_database,

        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Batch-Warehouse`), '') as batch_warehouse,
        TRY_CAST(`Receipt-Num` AS DECIMAL(18,0)) as receipt_num,
        NULLIF(TRIM(`Receipt-NumCV`), '') as receipt_numcv,
        TRY_CAST(`Batch-Num` AS DECIMAL(18,0)) as batch_num,
        TRY_CAST(`Line-Num` AS DECIMAL(18,4)) as line_num,
        NULLIF(TRIM(`Line-NumCV`), '') as line_numcv,
        NULLIF(TRIM(`Receipt-Status`), '') as receipt_status,
        NULLIF(TRIM(`RM-Product-Code`), '') as rm_product_code,
        NULLIF(TRIM(`RM-Packaging-Code`), '') as rm_packaging_code,
        NULLIF(TRIM(`RM-Prod-Pkg-Code`), '') as rm_prod_pkg_code,
        NULLIF(TRIM(`Default-Warehouse`), '') as default_warehouse,
        TRY_CAST(`Quantity` AS DECIMAL(38,4)) as quantity,
        NULLIF(TRIM(`Qty-Cost-UM`), '') as qty_cost_um,
        NULLIF(TRIM(`RM-Product-Key`), '') as rm_product_key,
        NULLIF(TRIM(`RM-Packaging-Key`), '') as rm_packaging_key,
        TRY_CAST(`Standard-Cost` AS DECIMAL(38,4)) as standard_cost,
        TRY_CAST(`Average-Cost` AS DECIMAL(38,4)) as average_cost,
        TRY_CAST(`Last-Cost` AS DECIMAL(38,4)) as last_cost,
        TRY_CAST(`Replacement-Cost` AS DECIMAL(38,4)) as replacement_cost,
        TRY_CAST(`Selling-Cost` AS DECIMAL(38,4)) as selling_cost,
        TRY_CAST(`Cost` AS DECIMAL(38,4)) as cost,
        TRY_CAST(`Extended-Cost` AS DECIMAL(38,2)) as extended_cost,
        TRY_CAST(`Orig-Line-Num` AS DECIMAL(18,4)) as orig_line_num,
        TRY_CAST(`Allocated-Quantity` AS DECIMAL(38,4)) as allocated_quantity,
        NULLIF(TRIM(`Allocated-Qty-UM`), '') as allocated_qty_um,
        NULLIF(TRIM(`Posted-GL-Acct-Ptr`), '') as posted_gl_acct_ptr,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`User-1`), '') as user_1,
        NULLIF(TRIM(`Spare-Char-1`), '') as spare_char_1,
        NULLIF(TRIM(`Spare-Char-2`), '') as spare_char_2,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`Spare-Decimal-1` AS DECIMAL(38,10)) as spare_decimal_1,
        TRY_CAST(`Spare-Decimal-2` AS DECIMAL(38,10)) as spare_decimal_2,
        IF(UPPER(TRIM(`Spare-Logical-1`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Spare-Logical-1`)) = 'FALSE', FALSE, NULL)) as spare_logical_1,
        IF(UPPER(TRIM(`Spare-Logical-2`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Spare-Logical-2`)) = 'FALSE', FALSE, NULL)) as spare_logical_2,
        TRY_CAST(`Spare-Integer-1` AS DECIMAL(18,0)) as spare_integer_1,
        TRY_CAST(`Spare-Integer-2` AS DECIMAL(18,0)) as spare_integer_2,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time
from {{ source('bronze', 'batch_rec_trl') }}
