select
    source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Cust-key`), '') as cust_key,
        NULLIF(TRIM(`Ref-type`), '') as ref_type,
        NULLIF(TRIM(`Ref-Num`), '') as ref_num,
        NULLIF(TRIM(`Cust-PO-Number`), '') as cust_po_number,
        NULLIF(TRIM(`Sales-Agent`), '') as sales_agent,
        NULLIF(TRIM(`Item-div`), '') as item_div,
        TRY_CAST(`item-cost` AS DECIMAL(38,2)) as item_cost,
        TRY_CAST(`Amount` AS DECIMAL(38,2)) as amount,
        TRY_CAST(`Open-amt` AS DECIMAL(38,2)) as open_amt,
        NULLIF(TRIM(`Open-amtCV`), '') as open_amtcv,
        NULLIF(TRIM(`Entered-Currency`), '') as entered_currency,
        TRY_CAST(`Ent-Currency-Conversion-Rate` AS DECIMAL(18,8)) as ent_currency_conversion_rate,
        CAST(TRY_TO_TIMESTAMP(`Ent-Currency-Conv-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as ent_currency_conv_date,
        NULLIF(TRIM(`Convert-To-Currency`), '') as convert_to_currency,
        NULLIF(TRIM(`Sale-type`), '') as sale_type,
        CAST(TRY_TO_TIMESTAMP(`Ref-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as ref_date,
        TRY_CAST(`Discount-amt` AS DECIMAL(38,2)) as discount_amt,
        CAST(TRY_TO_TIMESTAMP(`Discount-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as discount_date,
        TRY_CAST(`Discount-taken` AS DECIMAL(38,2)) as discount_taken,
        NULLIF(TRIM(`GL-Acct-Ptr`), '') as gl_acct_ptr,
        IF(UPPER(TRIM(`Posted-to-GL`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-to-GL`)) = 'FALSE', FALSE, NULL)) as posted_to_gl,
        IF(UPPER(TRIM(`On-hold`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`On-hold`)) = 'FALSE', FALSE, NULL)) as on_hold,
        TRY_CAST(`Days-on-hold` AS DECIMAL(18,0)) as days_on_hold,
        CAST(TRY_TO_TIMESTAMP(`Date-on-hold`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as date_on_hold,
        NULLIF(TRIM(`On-hold-by`), '') as on_hold_by,
        TRY_CAST(`Posting-Period` AS DECIMAL(18,0)) as posting_period,
        TRY_CAST(`Posting-Year` AS DECIMAL(18,0)) as posting_year,
        NULLIF(TRIM(`Batch-num`), '') as batch_num,
        IF(UPPER(TRIM(`Remark-attached`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Remark-attached`)) = 'FALSE', FALSE, NULL)) as remark_attached,
        NULLIF(TRIM(`Image-file`), '') as image_file,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`User-1`), '') as user_1,
        NULLIF(TRIM(`Journal-Number`), '') as journal_number,
        IF(UPPER(TRIM(`Posted-In-Summary-Entry`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-In-Summary-Entry`)) = 'FALSE', FALSE, NULL)) as posted_in_summary_entry,
        NULLIF(TRIM(`Year-Period`), '') as year_period,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as update_date_time,
        NULLIF(TRIM(`Sales-Agent-2`), '') as sales_agent_2,
        TRY_CAST(`Bill-of-Lading-Num` AS DECIMAL(18,0)) as bill_of_lading_num,
        NULLIF(TRIM(`Vendor-Tracking-Number`), '') as vendor_tracking_number,
        NULLIF(TRIM(`Spare-Char-1`), '') as spare_char_1
from {{ source('bronze', 'aropen') }}
