select
`SOURCE_DATABASE` as source_database,
        `System-ID` as system_id,
        TRY_CAST(`Order-Num` AS DECIMAL(18,0)) as order_num,
        `Order-NumCV` as order_numcv,
        TRY_CAST(`Seq-Num` AS DECIMAL(18,0)) as seq_num,
        `Seq-NumCV` as seq_numcv,
        `Product-Key` as product_key,
        `Packaging-Key` as packaging_key,
        `Ship-From-Warehouse` as ship_from_warehouse,
        `Order-Type` as order_type,
        TRY_CAST(`Quantity-Ordered` AS DECIMAL(13,2)) as quantity_ordered,
        TRY_CAST(`Quantity-Shipped` AS DECIMAL(13,2)) as quantity_shipped,
        TRY_CAST(`Quantity-Open` AS DECIMAL(13,2)) as quantity_open,
        `Quantity-OpenCV` as quantity_opencv,
        TRY_CAST(`Quantity-Billed` AS DECIMAL(13,2)) as quantity_billed,
        `Qty-UM` as qty_um,
        TRY_CAST(`Container-Weight` AS DECIMAL(13,2)) as container_weight,
        `Container-Weight-UM` as container_weight_um,
        TRY_CAST(`Container-Deposit-Amount` AS DECIMAL(18,4)) as container_deposit_amount,
        `Cust-Stencil-Code` as cust_stencil_code,
        `Cust-Product-Code` as cust_product_code,
        IF(UPPER(TRIM(`Price-Out-of-Range`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Price-Out-of-Range`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_price_out_of_range,
        IF(UPPER(TRIM(`Quantity-Out-of-Range`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Quantity-Out-of-Range`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_quantity_out_of_range,
        IF(UPPER(TRIM(`Filled-Back-Order`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Filled-Back-Order`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_filled_back_order,
        `Order-Status` as order_status,
        `Order-Status-Update-by` as order_status_update_by,
        CAST(TRY_TO_TIMESTAMP(`Order-Status-Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as order_status_update_date,
        `Order-Status-Update-time` as order_status_update_time,
        `Lot-Quality-1` as lot_quality_1,
        `Lot-Quality-2` as lot_quality_2,
        `Pick-Slip-Status` as pick_slip_status,
        `Cancel-by` as cancel_by,
        CAST(TRY_TO_TIMESTAMP(`Cancel-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cancel_date,
        `Cancel-time` as cancel_time,
        `Cancel-Reason` as cancel_reason,
        TRY_CAST(`Net-Price` AS DECIMAL(18,4)) as net_price,
        TRY_CAST(`Special-Cost` AS DECIMAL(18,4)) as special_cost,
        TRY_CAST(`Gross-Price` AS DECIMAL(18,4)) as gross_price,
        TRY_CAST(`Sales-Tax-Amt` AS DECIMAL(18,4)) as sales_tax_amt,
        TRY_CAST(`Other-Tax-Amt` AS DECIMAL(18,4)) as other_tax_amt,
        TRY_CAST(`Container-Amt` AS DECIMAL(18,2)) as container_amt,
        TRY_CAST(`Deposit-Amt` AS DECIMAL(18,2)) as deposit_amt,
        TRY_CAST(`Freight-Amt` AS DECIMAL(18,4)) as freight_amt,
        TRY_CAST(`Other-Amt` AS DECIMAL(18,4)) as other_amt,
        TRY_CAST(`Misc-Charge-Amt` AS DECIMAL(18,4)) as misc_charge_amt,
        TRY_CAST(`Special-Amt` AS DECIMAL(18,4)) as special_amt,
        TRY_CAST(`Special-Allowance-Amt` AS DECIMAL(18,4)) as special_allowance_amt,
        TRY_CAST(`Discount-Amt` AS DECIMAL(18,4)) as discount_amt,
        TRY_CAST(`Merch-Amt` AS DECIMAL(18,4)) as merch_amt,
        TRY_CAST(`Merch-Amt2` AS DECIMAL(18,4)) as merch_amt2,
        TRY_CAST(`Merch-Amt3` AS DECIMAL(18,4)) as merch_amt3,
        TRY_CAST(`Commision-Amt` AS DECIMAL(18,4)) as commision_amt,
        `Created-by` as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        `Update-by` as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        `Update-time` as update_time,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyyMMddHH:mm:ss') as update_date_time,
        `User-1` as user_1,
        `Price-UM` as price_um,
        TRY_CAST(`Disc-1` AS DECIMAL(5,2)) as disc_1,
        TRY_CAST(`Disc-2` AS DECIMAL(5,2)) as disc_2,
        TRY_CAST(`Allowance` AS DECIMAL(13,4)) as allowance,
        TRY_CAST(`Original-Price` AS DECIMAL(18,4)) as original_price,
        TRY_CAST(`Sale-Measure` AS DECIMAL(10,2)) as sale_measure,
        `Sale-MeasureCV` as sale_measurecv,
        `Sale-UM` as sale_um,
        `Sale-Pkg` as sale_pkg,
        `Original-Price-UM` as original_price_um,
        IF(UPPER(TRIM(`Cancelled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Cancelled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as cancelled,
        IF(UPPER(TRIM(`Closed`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Closed`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as closed,
        `Price-Group` as price_group,
        `Price-Schedule-Selection-Basis` as price_schedule_selection_basis,
        `Price-Type` as price_type,
        IF(UPPER(TRIM(`Price-Hold`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Price-Hold`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_price_hold,
        IF(UPPER(TRIM(`Inventory-Hold`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inventory-Hold`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_inventory_hold,
        CAST(TRY_TO_TIMESTAMP(`Ship-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as ship_date,
        CAST(TRY_TO_TIMESTAMP(`Delivery-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as delivery_date,
        IF(UPPER(TRIM(`Sales-Taxable`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Sales-Taxable`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_sales_taxable,
        `Sales-Tax-Code` as sales_tax_code,
        TRY_CAST(`Freight-Rate` AS DECIMAL(13,4)) as freight_rate,
        `Freight-Rate-UM` as freight_rate_um,
        `Price-Remark` as price_remark,
        `Freight-Remark` as freight_remark,
        `Supplier-Key` as supplier_key,
        TRY_CAST(`Supplier-Ship-From-Seq-Num` AS DECIMAL(18,0)) as supplier_ship_from_seq_num,
        `Transfer-CC-to-Warehouse` as transfer_cc_to_warehouse,
        IF(UPPER(TRIM(`Use-Freight-Rate`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Use-Freight-Rate`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_use_freight_rate,
        IF(UPPER(TRIM(`Lot-Selected`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Lot-Selected`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_lot_selected,
        TRY_CAST(`Internal-Key` AS DECIMAL(18,0)) as internal_key,
        `Cust-Key` as cust_key,
        `Lot-Status` as lot_status,
        `Cust-ID` as cust_id,
        `Product-Code` as product_code,
        `Packaging-Code` as packaging_code,
        CAST(TRY_TO_TIMESTAMP(`Order-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as order_date,
        `Prod-Pkg-Code` as prod_pkg_code,
        `Container-Currency` as container_currency,
        IF(UPPER(TRIM(`Container-Tracking`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Container-Tracking`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_container_tracking,
        `Delivery-Time` as delivery_time,
        TRY_TO_TIMESTAMP(`Delivery-Date-Time`, 'yyyyMMddHH:mm:ss') as delivery_date_time,
        `Security-Access-2` as security_access_2,
        `Auto-Charge-DelType` as auto_charge_deltype,
        `Spare-Char-2` as spare_char_2,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`Quantity-Returned-Received` AS DECIMAL(13,2)) as quantity_returned_received,
        TRY_CAST(`Quantity-Backordered` AS DECIMAL(13,2)) as quantity_backordered,
        IF(UPPER(TRIM(`Zero-Commission`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Zero-Commission`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_zero_commission,
        IF(UPPER(TRIM(`Spare-Logical-2`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-2`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_spare_logical_2,
        TRY_CAST(`Num-Containers-Override` AS DECIMAL(18,0)) as num_containers_override,
        TRY_CAST(`Customer-PO-Line-Num` AS DECIMAL(18,0)) as customer_po_line_num,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyyMMddHH:mm:ss') as created_date_time,
        TRY_CAST(`Req-Num-Lot` AS DECIMAL(18,0)) as req_num_lot,
        `Ship-Time` as ship_time,
        IF(UPPER(TRIM(`Manual-Price-Override`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Manual-Price-Override`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_manual_price_override,
        CAST(TRY_TO_TIMESTAMP(`Market-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as market_date,
        TRY_CAST(`Volume-Credit-Pct-SlsAgent-1` AS DECIMAL(5,2)) as volume_credit_pct_slsagent_1,
        TRY_CAST(`Calc-Base-Volume-Credit-Amt` AS DECIMAL(18,2)) as calc_base_volume_credit_amt,
        TRY_CAST(`User-Base-Volume-Credit-Amt` AS DECIMAL(18,2)) as user_base_volume_credit_amt,
        TRY_CAST(`Volume-Credit-Amt-SlsAgent-1` AS DECIMAL(18,2)) as volume_credit_amt_slsagent_1,
        TRY_CAST(`Volume-Credit-Amt-SlsAgent-2` AS DECIMAL(18,2)) as volume_credit_amt_slsagent_2,
        TRY_CAST(`Commission-Pct-SlsAgent-1` AS DECIMAL(5,2)) as commission_pct_slsagent_1,
        TRY_CAST(`Calc-Base-Commission-Amt` AS DECIMAL(18,2)) as calc_base_commission_amt,
        TRY_CAST(`User-Base-Commission-Amt` AS DECIMAL(18,2)) as user_base_commission_amt,
        TRY_CAST(`Commission-Amt-SlsAgent-1` AS DECIMAL(18,2)) as commission_amt_slsagent_1,
        TRY_CAST(`Commission-Amt-SlsAgent-2` AS DECIMAL(18,2)) as commission_amt_slsagent_2,
        IF(UPPER(TRIM(`Sales-Agent-Pay`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Sales-Agent-Pay`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_sales_agent_pay,
        TRY_CAST(`Volume-Credit-Pct-SlsAgent-2` AS DECIMAL(5,2)) as volume_credit_pct_slsagent_2,
        TRY_CAST(`Commission-Pct-SlsAgent-2` AS DECIMAL(5,2)) as commission_pct_slsagent_2,
        TRY_CAST(`Company-Discount` AS DECIMAL(5,2)) as company_discount,
        TRY_CAST(`SlsAgent-Discount` AS DECIMAL(5,2)) as slsagent_discount,
        CAST(TRY_TO_TIMESTAMP(`Original-Ship-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as original_ship_date,
        IF(UPPER(TRIM(`Backorder`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Backorder`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_backorder,
        `Backorder-Code` as backorder_code,
        `Backorder-Reason` as backorder_reason,
        CAST(TRY_TO_TIMESTAMP(`Backorder-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as backorder_date,
        TRY_CAST(`Backorder-Ship-Tran-Num` AS DECIMAL(18,0)) as backorder_ship_tran_num,
        TRY_CAST(`Backorder-Cost` AS DECIMAL(18,4)) as backorder_cost,
        TRY_CAST(`Backorder-Quantity` AS DECIMAL(13,2)) as backorder_quantity,
        TRY_CAST(`Product-Commission-Pct` AS DECIMAL(5,2)) as product_commission_pct,
        TRY_CAST(`User-Product-Commission-Pct` AS DECIMAL(5,2)) as user_product_commission_pct,
        TRY_CAST(`Bonus-Prod-Class-Amt-SlsAgent-1` AS DECIMAL(18,0)) as bonus_prod_class_amt_slsagent_1,
        TRY_CAST(`Bonus-Prod-Class-Amt-SlsAgent-2` AS DECIMAL(18,0)) as bonus_prod_class_amt_slsagent_2,
        IF(UPPER(TRIM(`Spare-Logical-3`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-3`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_spare_logical_3,
        TRY_CAST(`Quantity-Returned` AS DECIMAL(13,2)) as quantity_returned,
        TRY_CAST(`TA-ID` AS DECIMAL(18,0)) as ta_id,
        TRY_CAST(`Spare-Integer-3` AS DECIMAL(18,0)) as spare_integer_3,
        TRY_CAST(`Spare-Integer-4` AS DECIMAL(18,0)) as spare_integer_4,
        TRY_CAST(`Quantity-To-Ship` AS DECIMAL(13,2)) as quantity_to_ship,
        TRY_CAST(`Spare-Decimal-4` AS DECIMAL(20,10)) as spare_decimal_4,
        TRY_CAST(`Spare-Decimal-5` AS DECIMAL(20,10)) as spare_decimal_5,
        `Spare-Char-3` as spare_char_3,
        IF(UPPER(TRIM(`Auto-Charge`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Auto-Charge`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_auto_charge,
        `Auto-Charge-Details` as auto_charge_details,
        `Auto-Charge-Group` as auto_charge_group,
        TRY_CAST(`Spare-Integer-5` AS DECIMAL(18,0)) as spare_integer_5,
        TRY_CAST(`Spare-Integer-6` AS DECIMAL(18,0)) as spare_integer_6,
        TRY_CAST(`Spare-Decimal-6` AS DECIMAL(20,10)) as spare_decimal_6,
        TRY_CAST(`Spare-Decimal-7` AS DECIMAL(20,10)) as spare_decimal_7,
        `Spare-Char-4` as spare_char_4,
        TRY_CAST(`Spare-Decimal-8` AS DECIMAL(20,10)) as spare_decimal_8
from {{ source('bronze', 'order_trl') }}
