select

        source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Product-Key`), '') as product_key,
        NULLIF(TRIM(`Packaging-Key`), '') as packaging_key,
        NULLIF(TRIM(`Inv-Measure`), '') as inv_measure,
        NULLIF(TRIM(`Inv-UM`), '') as inv_um,
        NULLIF(TRIM(`Inv-Pkg`), '') as inv_pkg,
        TRY_CAST(`Weight` AS DECIMAL(38,4)) as weight,
        NULLIF(TRIM(`Weight-UM`), '') as weight_um,
        TRY_CAST(`RQ` AS DECIMAL(38,4)) as rq,
        NULLIF(TRIM(`RQ-UM`), '') as rq_um,
        NULLIF(TRIM(`Freight-Class`), '') as freight_class,
        IF(UPPER(TRIM(`Kit`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Kit`)) = 'FALSE', FALSE, NULL)) as kit,
        TRY_CAST(`Standard-Cost` AS DECIMAL(38,4)) as standard_cost,
        CAST(TRY_TO_TIMESTAMP(`Standard-Cost-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as standard_cost_date,
        TRY_CAST(`Average-Cost` AS DECIMAL(38,4)) as average_cost,
        TRY_CAST(`Last-Cost` AS DECIMAL(38,4)) as last_cost,
        CAST(TRY_TO_TIMESTAMP(`Last-Cost-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_cost_date,
        TRY_CAST(`Replacement-Cost` AS DECIMAL(38,4)) as replacement_cost,
        TRY_CAST(`Selling-Cost` AS DECIMAL(38,4)) as selling_cost,
        TRY_CAST(`Inv-Amount@1` AS DECIMAL(38,2)) as inv_amount_1,
        TRY_CAST(`Inv-Amount@2` AS DECIMAL(38,2)) as inv_amount_2,
        TRY_CAST(`Inv-Amount@3` AS DECIMAL(38,2)) as inv_amount_3,
        TRY_CAST(`Inv-Amount@4` AS DECIMAL(38,2)) as inv_amount_4,
        TRY_CAST(`Inv-Amount@5` AS DECIMAL(38,2)) as inv_amount_5,
        TRY_CAST(`Inv-Amount@6` AS DECIMAL(38,2)) as inv_amount_6,
        TRY_CAST(`Inv-Amount@7` AS DECIMAL(38,2)) as inv_amount_7,
        TRY_CAST(`Inv-Amount@8` AS DECIMAL(38,2)) as inv_amount_8,
        TRY_CAST(`Inv-Amount@9` AS DECIMAL(38,2)) as inv_amount_9,
        TRY_CAST(`Inv-Amount@10` AS DECIMAL(38,2)) as inv_amount_10,
        NULLIF(TRIM(`Inv-Status@1`), '') as inv_status_1,
        NULLIF(TRIM(`Inv-Status@2`), '') as inv_status_2,
        NULLIF(TRIM(`Inv-Status@3`), '') as inv_status_3,
        NULLIF(TRIM(`Inv-Status@4`), '') as inv_status_4,
        NULLIF(TRIM(`Inv-Status@5`), '') as inv_status_5,
        NULLIF(TRIM(`Inv-Status@6`), '') as inv_status_6,
        NULLIF(TRIM(`Inv-Status@7`), '') as inv_status_7,
        NULLIF(TRIM(`Inv-Status@8`), '') as inv_status_8,
        NULLIF(TRIM(`Inv-Status@9`), '') as inv_status_9,
        NULLIF(TRIM(`Inv-Status@10`), '') as inv_status_10,
        IF(UPPER(TRIM(`Inv-Flag@1`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@1`)) = 'FALSE', FALSE, NULL)) as inv_flag_1,
        IF(UPPER(TRIM(`Inv-Flag@2`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@2`)) = 'FALSE', FALSE, NULL)) as inv_flag_2,
        IF(UPPER(TRIM(`Inv-Flag@3`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@3`)) = 'FALSE', FALSE, NULL)) as inv_flag_3,
        IF(UPPER(TRIM(`Inv-Flag@4`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@4`)) = 'FALSE', FALSE, NULL)) as inv_flag_4,
        IF(UPPER(TRIM(`Inv-Flag@5`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@5`)) = 'FALSE', FALSE, NULL)) as inv_flag_5,
        IF(UPPER(TRIM(`Inv-Flag@6`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@6`)) = 'FALSE', FALSE, NULL)) as inv_flag_6,
        IF(UPPER(TRIM(`Inv-Flag@7`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@7`)) = 'FALSE', FALSE, NULL)) as inv_flag_7,
        IF(UPPER(TRIM(`Inv-Flag@8`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@8`)) = 'FALSE', FALSE, NULL)) as inv_flag_8,
        IF(UPPER(TRIM(`Inv-Flag@9`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@9`)) = 'FALSE', FALSE, NULL)) as inv_flag_9,
        IF(UPPER(TRIM(`Inv-Flag@10`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Inv-Flag@10`)) = 'FALSE', FALSE, NULL)) as inv_flag_10,
        NULLIF(TRIM(`Unit-of-Meas`), '') as unit_of_meas,
        TRY_CAST(`OH-packages` AS DECIMAL(18,0)) as oh_packages,
        NULLIF(TRIM(`Old-Product-Number`), '') as old_product_number,
        NULLIF(TRIM(`Dft-Formula-Code`), '') as dft_formula_code,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as update_date_time,
        NULLIF(TRIM(`User-1`), '') as user_1,
        TRY_CAST(`Sequence-1` AS DECIMAL(18,0)) as sequence_1,
        NULLIF(TRIM(`Product-Code`), '') as product_code,
        NULLIF(TRIM(`Packaging-Code`), '') as packaging_code,
        NULLIF(TRIM(`Prod-Pkg-Code`), '') as prod_pkg_code,
        NULLIF(TRIM(`Raw-Material-Spec-ID`), '') as raw_material_spec_id,
        NULLIF(TRIM(`Finished-Good-Spec-ID`), '') as finished_good_spec_id,
        IF(UPPER(TRIM(`Active`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Active`)) = 'FALSE', FALSE, NULL)) as active,
        NULLIF(TRIM(`Security-Access-2`), '') as security_access_2,
        NULLIF(TRIM(`Placard-Code`), '') as placard_code,
        NULLIF(TRIM(`Above-RQ-Shipping-Name`), '') as above_rq_shipping_name,
        NULLIF(TRIM(`Below-RQ-Shipping-Name`), '') as below_rq_shipping_name,
        IF(UPPER(TRIM(`Above-RQ-HM-Flag`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Above-RQ-HM-Flag`)) = 'FALSE', FALSE, NULL)) as above_rq_hm_flag,
        IF(UPPER(TRIM(`Below-RQ-HM-Flag`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Below-RQ-HM-Flag`)) = 'FALSE', FALSE, NULL)) as below_rq_hm_flag,
        NULLIF(TRIM(`BOL-Level`), '') as bol_level,
        NULLIF(TRIM(`DOT-Packaging`), '') as dot_packaging,
        NULLIF(TRIM(`Prod-Pkg-Name`), '') as prod_pkg_name,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`Spare-Decimal-1` AS DECIMAL(38,10)) as spare_decimal_1,
        TRY_CAST(`Spare-Decimal-2` AS DECIMAL(38,10)) as spare_decimal_2,
        IF(UPPER(TRIM(`Print-On-Container-Return-BOL`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Print-On-Container-Return-BOL`)) = 'FALSE', FALSE, NULL)) as print_on_container_return_bol,
        IF(UPPER(TRIM(`Quote-Temporary-Prod-Pkg`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Quote-Temporary-Prod-Pkg`)) = 'FALSE', FALSE, NULL)) as quote_temporary_prod_pkg,
        TRY_CAST(`Shelf-Life` AS DECIMAL(18,0)) as shelf_life,
        TRY_CAST(`Items-Per-Package` AS DECIMAL(18,0)) as items_per_package,
        TRY_CAST(`Spare-Integer-3` AS DECIMAL(18,0)) as spare_integer_3,
        NULLIF(TRIM(`Product-Priority`), '') as product_priority,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        NULLIF(TRIM(`Product-Status`), '') as product_status,
        TRY_CAST(`Packages-Per-Pallet` AS DECIMAL(18,0)) as packages_per_pallet,
        NULLIF(TRIM(`NMFC-Number`), '') as nmfc_number,
        NULLIF(TRIM(`Container-Weight-UM`), '') as container_weight_um,
        TRY_CAST(`Container-Weight` AS DECIMAL(38,4)) as container_weight,
        NULLIF(TRIM(`International-Shipping-Name`), '') as international_shipping_name,
        IF(UPPER(TRIM(`International-HM-Flag`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`International-HM-Flag`)) = 'FALSE', FALSE, NULL)) as international_hm_flag,
        IF(UPPER(TRIM(`Spare-Logical-3`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Spare-Logical-3`)) = 'FALSE', FALSE, NULL)) as spare_logical_3,
        IF(UPPER(TRIM(`Spare-Logical-4`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Spare-Logical-4`)) = 'FALSE', FALSE, NULL)) as spare_logical_4,
        NULLIF(TRIM(`Receipt-Route`), '') as receipt_route,
        NULLIF(TRIM(`Location-Storage-Code`), '') as location_storage_code,
        NULLIF(TRIM(`Inventory-Alert`), '') as inventory_alert,
        CAST(TRY_TO_TIMESTAMP(`MSDS-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as msds_date,
        NULLIF(TRIM(`MSDS-Image-File`), '') as msds_image_file,
        NULLIF(TRIM(`Placard-Code-Exception`), '') as placard_code_exception,
        NULLIF(TRIM(`Uber-Keywords`), '') as uber_keywords,
        NULLIF(TRIM(`Uber-Search`), '') as uber_search,
        NULLIF(TRIM(`DNU-Rental-Class`), '') as dnu_rental_class,
        NULLIF(TRIM(`Product-Image-File`), '') as product_image_file,
        TRY_CAST(`Spare-Integer-4` AS DECIMAL(18,0)) as spare_integer_4,
        NULLIF(TRIM(`Created-From-ProdCatalog`), '') as created_from_prodcatalog,
        TRY_CAST(`Replacement-Price` AS DECIMAL(38,4)) as replacement_price,
        IF(UPPER(TRIM(`Is-Exchange-Type`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Is-Exchange-Type`)) = 'FALSE', FALSE, NULL)) as exchange_type,
        IF(UPPER(TRIM(`Is-Bulk-Tank`)) = 'TRUE', TRUE, IF(UPPER(TRIM(`Is-Bulk-Tank`)) = 'FALSE', FALSE, NULL)) as bulk_tank,
        NULLIF(TRIM(`Rental-Class-Key`), '') as rental_class_key,
        NULLIF(TRIM(`Rental-Class-KeyCV`), '') as rental_class_keycv,
        NULLIF(TRIM(`Spare-Char-9`), '') as spare_char_9,
        NULLIF(TRIM(`Spare-Char-10`), '') as spare_char_10,
        NULLIF(TRIM(`Spare-Char-11`), '') as spare_char_11
from {{ source('bronze', 'prod_pkg') }}
