select
    source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        TRY_CAST(`Voucher-Number` AS DECIMAL(18,0)) as voucher_number,
        NULLIF(TRIM(`Voucher-NumberCV`), '') as voucher_numbercv,
        NULLIF(TRIM(`Voucher-Type`), '') as voucher_type,
        NULLIF(TRIM(`Reference-Number`), '') as reference_number,
        TRY_CAST(`Internal-key` AS DECIMAL(18,0)) as internal_key,
        TRY_CAST(`Supplier-Key` AS DECIMAL(18,0)) as supplier_key,
        CAST(TRY_TO_TIMESTAMP(`Entered-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as entered_date,
        NULLIF(TRIM(`Entered-Time`), '') as entered_time,
        CAST(TRY_TO_TIMESTAMP(`Invoice-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as invoice_date,
        CAST(TRY_TO_TIMESTAMP(`Due-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as due_date,
        NULLIF(TRIM(`Terms-Code`), '') as terms_code,
        CAST(TRY_TO_TIMESTAMP(`Discount-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as discount_date,
        TRY_CAST(`Amount` AS DECIMAL(38,2)) as amount,
        TRY_CAST(`Open-Amount` AS DECIMAL(38,2)) as open_amount,
        NULLIF(TRIM(`AP-GL-Acct-Ptr`), '') as ap_gl_acct_ptr,
        NULLIF(TRIM(`Entered-Currency`), '') as entered_currency,
        TRY_CAST(`Ent-Currency-Conversion-Rate` AS DECIMAL(18,8)) as ent_currency_conversion_rate,
        CAST(TRY_TO_TIMESTAMP(`Ent-Currency-Conv-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as ent_currency_conv_date,
        NULLIF(TRIM(`Convert-To-Currency`), '') as convert_to_currency,
        TRY_CAST(`Discount-Amount` AS DECIMAL(38,2)) as discount_amount,
        NULLIF(TRIM(`Discount-AmountCV`), '') as discount_amountcv,
        TRY_CAST(`Discount-taken` AS DECIMAL(38,2)) as discount_taken,
        TRY_CAST(`Posting-Period` AS DECIMAL(18,0)) as posting_period,
        TRY_CAST(`Posting-Year` AS DECIMAL(18,0)) as posting_year,
        NULLIF(TRIM(`PO-Number`), '') as po_number,
        NULLIF(TRIM(`Remit-To-Name`), '') as remit_to_name,
        NULLIF(TRIM(`Remit-To-Address1`), '') as remit_to_address1,
        NULLIF(TRIM(`Remit-To-Address2`), '') as remit_to_address2,
        NULLIF(TRIM(`Remit-To-Address3`), '') as remit_to_address3,
        NULLIF(TRIM(`Remit-To-City`), '') as remit_to_city,
        NULLIF(TRIM(`Remit-To-State`), '') as remit_to_state,
        NULLIF(TRIM(`Remit-To-Zip`), '') as remit_to_zip,
        NULLIF(TRIM(`Remit-to-Country`), '') as remit_to_country,
        NULLIF(TRIM(`Remit-To-Phone`), '') as remit_to_phone,
        IF(UPPER(TRIM(`Post-direct-to-gl`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Post-direct-to-gl`)) = 'FALSE', FALSE, NULL)) as post_direct_to_gl,
        IF(UPPER(TRIM(`Posted-To-GL`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-To-GL`)) = 'FALSE', FALSE, NULL)) as posted_to_gl,
        CAST(TRY_TO_TIMESTAMP(`Posted-to-GL-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as posted_to_gl_date,
        NULLIF(TRIM(`Posted-to-GL-Time`), '') as posted_to_gl_time,
        NULLIF(TRIM(`Posted-to-GL-by`), '') as posted_to_gl_by,
        NULLIF(TRIM(`Journal-Number`), '') as journal_number,
        NULLIF(TRIM(`Inv-Status`), '') as inv_status,
        IF(UPPER(TRIM(`On-hold`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`On-hold`)) = 'FALSE', FALSE, NULL)) as on_hold,
        CAST(TRY_TO_TIMESTAMP(`On-hold-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as on_hold_date,
        IF(UPPER(TRIM(`Closed`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Closed`)) = 'FALSE', FALSE, NULL)) as closed,
        TRY_CAST(`Days-on-hold` AS DECIMAL(18,0)) as days_on_hold,
        TRY_CAST(`Amount-Paid` AS DECIMAL(38,2)) as amount_paid,
        TRY_CAST(`Other-amt` AS DECIMAL(38,2)) as other_amt,
        IF(UPPER(TRIM(`Cancelled`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Cancelled`)) = 'FALSE', FALSE, NULL)) as cancelled,
        NULLIF(TRIM(`Cancelled-by`), '') as cancelled_by,
        CAST(TRY_TO_TIMESTAMP(`Cancelled-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cancelled_date,
        IF(UPPER(TRIM(`Payment-Completed`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Payment-Completed`)) = 'FALSE', FALSE, NULL)) as payment_completed,
        NULLIF(TRIM(`Invoice-Image-File`), '') as invoice_image_file,
        NULLIF(TRIM(`Payment-method`), '') as payment_method,
        NULLIF(TRIM(`Freight-Ref-Num`), '') as freight_ref_num,
        NULLIF(TRIM(`Freight-BL`), '') as freight_bl,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Interface-Number`), '') as interface_number,
        NULLIF(TRIM(`User-1`), '') as user_1,
        IF(UPPER(TRIM(`Posted-In-Summary-Entry`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-In-Summary-Entry`)) = 'FALSE', FALSE, NULL)) as posted_in_summary_entry,
        NULLIF(TRIM(`Batch-ID`), '') as batch_id,
        TRY_CAST(`Associated-Voucher-Number` AS DECIMAL(18,0)) as associated_voucher_number,
        IF(UPPER(TRIM(`Voucher-1099`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Voucher-1099`)) = 'FALSE', FALSE, NULL)) as voucher_1099,
        IF(UPPER(TRIM(`Intercompany-Transaction`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Intercompany-Transaction`)) = 'FALSE', FALSE, NULL)) as intercompany_transaction,
        TRY_CAST(`Remit-To-Seq-Num` AS DECIMAL(18,0)) as remit_to_seq_num,
        NULLIF(TRIM(`tax-code`), '') as tax_code,
        NULLIF(TRIM(`Year-Period`), '') as year_period,
        NULLIF(TRIM(`Payment-Comment`), '') as payment_comment,
        IF(UPPER(TRIM(`Manual-Use-Tax`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Manual-Use-Tax`)) = 'FALSE', FALSE, NULL)) as manual_use_tax,
        TRY_CAST(`Manual-Taxable-Amount` AS DECIMAL(38,2)) as manual_taxable_amount,
        TRY_CAST(`Manual-Tax-Percent` AS DECIMAL(18,2)) as manual_tax_percent,
        NULLIF(TRIM(`Manual-State-Tax-Code`), '') as manual_state_tax_code,
        TRY_CAST(`Manual-Tax-Rate` AS DECIMAL(18,4)) as manual_tax_rate,
        IF(UPPER(TRIM(`Manual-Tax-Processed`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Manual-Tax-Processed`)) = 'FALSE', FALSE, NULL)) as manual_tax_processed,
        IF(UPPER(TRIM(`Create-Offsetting-AR`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Create-Offsetting-AR`)) = 'FALSE', FALSE, NULL)) as create_offsetting_ar,
        NULLIF(TRIM(`AR-Ref-Cust-Key`), '') as ar_ref_cust_key,
        NULLIF(TRIM(`AR-Ref-Type`), '') as ar_ref_type,
        NULLIF(TRIM(`AR-Ref-Num`), '') as ar_ref_num,
        NULLIF(TRIM(`Manual-Tax-Country`), '') as manual_tax_country,
        NULLIF(TRIM(`Manual-Tax-State`), '') as manual_tax_state,
        NULLIF(TRIM(`Voided-Year-Period`), '') as voided_year_period,
        NULLIF(TRIM(`Voided-Journal-Number`), '') as voided_journal_number,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        NULLIF(TRIM(`Voucher-Origin`), '') as voucher_origin,
        TRY_CAST(`Volume-Credit-Amt` AS DECIMAL(38,2)) as volume_credit_amt,
        NULLIF(TRIM(`DNU-Voucher-Class`), '') as dnu_voucher_class,
        TRY_CAST(`Bonus-Product-Class-Amt` AS DECIMAL(18,0)) as bonus_product_class_amt,
        NULLIF(TRIM(`Std-ID`), '') as std_id,
        NULLIF(TRIM(`NC-Type`), '') as nc_type,
        TRY_CAST(`Non-Conformance-Num` AS DECIMAL(18,0)) as non_conformance_num,
        NULLIF(TRIM(`Non-Conformance-NumCV`), '') as non_conformance_numcv,
        NULLIF(TRIM(`APA-Document-ID`), '') as apa_document_id,
        NULLIF(TRIM(`Spare-Char-2`), '') as spare_char_2,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        TRY_CAST(`Spare-Decimal-1` AS DECIMAL(38,10)) as spare_decimal_1,
        IF(UPPER(TRIM(`Prepaid-PO-Invoice`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Prepaid-PO-Invoice`)) = 'FALSE', FALSE, NULL)) as prepaid_po_invoice,
        TRY_CAST(`Spare-Integer-1` AS DECIMAL(18,0)) as spare_integer_1,
        TRY_CAST(`Invoice-Num` AS DECIMAL(18,0)) as invoice_num,
        NULLIF(TRIM(`Invoice-NumCV`), '') as invoice_numcv,
        NULLIF(TRIM(`Spare-Char-3`), '') as spare_char_3,
        IF(UPPER(TRIM(`Spare-Logical-2`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Spare-Logical-2`)) = 'FALSE', FALSE, NULL)) as spare_logical_2,
        NULLIF(TRIM(`Spare-Char-4`), '') as spare_char_4,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as update_date_time
from {{ source('bronze', 'apinvhdr') }}
