select
    source_database,
    NULLIF(TRIM(`System-ID`), '') as system_id,
    NULLIF(TRIM(`Cust-key`), '') as cust_key,
    NULLIF(TRIM(`Ref-Num`), '') as ref_num,
    NULLIF(TRIM(`Ref-type`), '') as ref_type,
    NULLIF(TRIM(`Internal-key`), '') as internal_key,
    CAST(TRY_TO_TIMESTAMP(`Due-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as due_date,
    CAST(TRY_TO_TIMESTAMP(`Payment-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as payment_date,
    TRY_CAST(`Payment-Amount` AS DECIMAL(38,2)) as payment_amount,
    TRY_CAST(`Merch-amt` AS DECIMAL(38,2)) as merch_amt,
    TRY_CAST(`Merch-amt2` AS DECIMAL(38,2)) as merch_amt_2,
    TRY_CAST(`merch-amt3` AS DECIMAL(38,2)) as merch_amt_3,
    TRY_CAST(`Sales-Tax-amt` AS DECIMAL(38,2)) as sales_tax_amt,
    TRY_CAST(`Other-tax-amt` AS DECIMAL(38,2)) as other_tax_amt,
    TRY_CAST(`cont-amt` AS DECIMAL(38,2)) as cont_amt,
    TRY_CAST(`Deposit-amt` AS DECIMAL(38,2)) as deposit_amt,
    TRY_CAST(`Freight-amt` AS DECIMAL(38,2)) as freight_amt,
    TRY_CAST(`Other-amt` AS DECIMAL(38,2)) as other_amt,
    TRY_CAST(`Misc-charge-amt` AS DECIMAL(38,2)) as misc_charge_amt,
    TRY_CAST(`Fin-charge-amt` AS DECIMAL(38,2)) as fin_charge_amt,
    TRY_CAST(`Interest-amt` AS DECIMAL(38,2)) as interest_amt,
    TRY_CAST(`Special-amt` AS DECIMAL(38,2)) as special_amt,
    TRY_CAST(`special-allowance-amt` AS DECIMAL(38,2)) as special_allowance_amt,
    TRY_CAST(`Discount-amt` AS DECIMAL(38,2)) as discount_amt,
    TRY_CAST(`Write-off-Amt` AS DECIMAL(38,2)) as write_off_amt,
    NULLIF(TRIM(`Write-off-remark`), '') as write_off_remark,
    NULLIF(TRIM(`Payment-Method`), '') as payment_method,
    NULLIF(TRIM(`Payment-ID-Num`), '') as payment_id_num,
    NULLIF(TRIM(`Paid-Currency`), '') as paid_currency,
    NULLIF(TRIM(`Convert-To-Currency`), '') as convert_to_currency,
    CAST(TRY_TO_TIMESTAMP(`Currency-Conversion-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as currency_conversion_date,
    TRY_CAST(`Currency-Conversion-Rate` AS DECIMAL(18,8)) as currency_conversion_rate,
    NULLIF(TRIM(`Trans-code`), '') as trans_code,
    TRY_CAST(`Sequence-num` AS DECIMAL(18,0)) as sequence_num,
    NULLIF(TRIM(`Sequence-numCV`), '') as sequence_num_cv,
    NULLIF(TRIM(`GL-Acct-Ptr`), '') as gl_acct_ptr,
    IF(UPPER(TRIM(`Posted-to-GL`)) = 'TRUE', TRUE,
    IF(UPPER(TRIM(`Posted-to-GL`)) = 'FALSE', FALSE, NULL)) as posted_to_gl,
    TRY_CAST(`Posting-Period` AS DECIMAL(18,0)) as posting_period,
    TRY_CAST(`Posting-year` AS DECIMAL(18,0)) as posting_year,
    NULLIF(TRIM(`Batch-ID`), '') as batch_id,
    IF(UPPER(TRIM(`Cancelled`)) = 'TRUE', TRUE,
    IF(UPPER(TRIM(`Cancelled`)) = 'FALSE', FALSE, NULL)) as cancelled,
    NULLIF(TRIM(`Update-by`), '') as update_by,
    CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
    NULLIF(TRIM(`Update-time`), '') as update_time,
    NULLIF(TRIM(`Created-by`), '') as created_by,
    CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
    NULLIF(TRIM(`Security-Access`), '') as security_access,
    NULLIF(TRIM(`User-1`), '') as user_1,
    NULLIF(TRIM(`Journal-Number`), '') as journal_number,
    NULLIF(TRIM(`Payment-ID-Reconciled`), '') as payment_id_reconciled,
    TRY_CAST(`Reconciliation-Rate` AS DECIMAL(18,8)) as reconciliation_rate,
    NULLIF(TRIM(`Reconciled-by`), '') as reconciled_by,
    CAST(TRY_TO_TIMESTAMP(`Reconciled-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as reconciled_date,
    NULLIF(TRIM(`Reconciled-time`), '') as reconciled_time,
    IF(UPPER(TRIM(`Recon-Posted-to-GL`)) = 'TRUE', TRUE,
    IF(UPPER(TRIM(`Recon-Posted-to-GL`)) = 'FALSE', FALSE, NULL)) as recon_posted_to_gl,
    NULLIF(TRIM(`Recon-Journal-Number`), '') as recon_journal_number,
    IF(UPPER(TRIM(`Posted-In-Summary-Entry`)) = 'TRUE', TRUE,
    IF(UPPER(TRIM(`Posted-In-Summary-Entry`)) = 'FALSE', FALSE, NULL)) as posted_in_summary_entry,
    IF(UPPER(TRIM(`Recon-Posted-In-Summary-Entry`)) = 'TRUE', TRUE,
    IF(UPPER(TRIM(`Recon-Posted-In-Summary-Entry`)) = 'FALSE', FALSE, NULL)) as recon_posted_in_summary_entry,
    NULLIF(TRIM(`Write-Off-GL-Acct-Ptr`), '') as write_off_gl_acct_ptr,
    NULLIF(TRIM(`Year-Period`), '') as year_period,
    NULLIF(TRIM(`Trans-Num`), '') as trans_num,
    NULLIF(TRIM(`Trans-NumCV`), '') as trans_num_cv,
    NULLIF(TRIM(`Forex-Journal-Number`), '') as forex_journal_number,
    NULLIF(TRIM(`Forex-GL-Acct-Ptr`), '') as forex_gl_acct_ptr,
    TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
    NULLIF(TRIM(`Reconciled-Year-Period`), '') as reconciled_year_period

from {{ source('bronze', 'arcash') }}