select
    source_database,

        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Batch-Warehouse`), '') as batch_warehouse,
        NULLIF(TRIM(`Receipt-Num`), '') as receipt_num,
        NULLIF(TRIM(`Receipt-NumCV`), '') as receipt_num_cv,
        NULLIF(TRIM(`Batch-Num`), '') as batch_num,
        NULLIF(TRIM(`Line-Num`), '') as line_num,
        NULLIF(TRIM(`Line-NumCV`), '') as line_num_cv,
        NULLIF(TRIM(`Warehouse`), '') as warehouse,
        NULLIF(TRIM(`Lot-Code`), '') as lot_code,
        NULLIF(TRIM(`Location`), '') as location,
        NULLIF(TRIM(`Receipt-Status`), '') as receipt_status,
        NULLIF(TRIM(`Serial-Number`), '') as serial_number,
        TRY_CAST(`Quantity` AS DECIMAL(38,4)) as quantity,
        NULLIF(TRIM(`Qty-Cost-UM`), '') as qty_cost_um,
        TRY_CAST(`Standard-Cost` AS DECIMAL(38,4)) as standard_cost,
        TRY_CAST(`Average-Cost` AS DECIMAL(38,4)) as average_cost,
        TRY_CAST(`Last-Cost` AS DECIMAL(38,4)) as last_cost,
        TRY_CAST(`Replacement-Cost` AS DECIMAL(38,4)) as replacement_cost,
        TRY_CAST(`Selling-Cost` AS DECIMAL(38,4)) as selling_cost,
        TRY_CAST(`Cost` AS DECIMAL(38,4)) as cost,
        TRY_CAST(`Extended-Cost` AS DECIMAL(38,2)) as extended_cost,
        TRY_CAST(`Allocated-Quantity` AS DECIMAL(38,4)) as allocated_quantity,
        NULLIF(TRIM(`Allocated-Qty-UM`), '') as allocated_qty_um,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`User-1`), '') as user_1,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time
from {{ source('bronze', 'batch_rec_trl_whs_lot_loc') }}
