select
    source_database,

        NULLIF(TRIM(`System-ID`), '')                    as system_id,
        NULLIF(TRIM(`Origin`), '')                       as origin,
        NULLIF(TRIM(`Journal-Number`), '')               as journal_number,
        NULLIF(TRIM(`Source`), '')                       as source,
        TRY_CAST(`Posting-Year` AS DECIMAL(18,0))             as posting_year,
        TRY_CAST(`Posting-Period` AS DECIMAL(18,0))           as posting_period,
        IF(UPPER(TRIM(`Tax-Only`)) = 'TRUE', TRUE,
            IF(UPPER(TRIM(`Tax-Only`)) = 'FALSE', FALSE, NULL))
                                                         as tax_only,
        NULLIF(TRIM(`Remark`), '')                       as remark,
        NULLIF(TRIM(`Detailed-Remark`), '')              as detailed_remark,
        IF(UPPER(TRIM(`Posted`)) = 'TRUE', TRUE,
            IF(UPPER(TRIM(`Posted`)) = 'FALSE', FALSE, NULL))
                                                         as posted,
        NULLIF(TRIM(`Entered-By`), '')                   as entered_by,
        CAST(TRY_TO_TIMESTAMP(`Entered-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                      as entered_date,
        NULLIF(TRIM(`Entered-Time`), '')                 as entered_time,
        IF(UPPER(TRIM(`Internal-Entry`)) = 'TRUE', TRUE,
            IF(UPPER(TRIM(`Internal-Entry`)) = 'FALSE', FALSE, NULL))
                                                         as internal_entry,
        NULLIF(TRIM(`Posted-By`), '')                    as posted_by,
        CAST(TRY_TO_TIMESTAMP(`Posted-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                       as posted_date,
        NULLIF(TRIM(`Posted-Time`), '')                  as posted_time,
        NULLIF(TRIM(`Revised-By`), '')                   as revised_by,
        CAST(TRY_TO_TIMESTAMP(`Revised-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                      as revised_date,
        NULLIF(TRIM(`Revised-Time`), '')                 as revised_time,
        NULLIF(TRIM(`Un-posted-by`), '')                 as unposted_by,
        CAST(TRY_TO_TIMESTAMP(`Un-posted-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                    as unposted_date,
        NULLIF(TRIM(`Un-posted-Time`), '')               as unposted_time,
        NULLIF(TRIM(`Re-posted-By`), '')                 as reposted_by,
        CAST(TRY_TO_TIMESTAMP(`Re-posted-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                    as reposted_date,
        NULLIF(TRIM(`Re-posted-time`), '')               as reposted_time,
        TRY_CAST(`Amount` AS DECIMAL(18,2))                   as amount,
        IF(UPPER(TRIM(`Reversible`)) = 'TRUE', TRUE,
            IF(UPPER(TRIM(`Reversible`)) = 'FALSE', FALSE, NULL))
                                                         as reversible,
        NULLIF(TRIM(`Reversed-By`), '')                  as reversed_by,
        CAST(TRY_TO_TIMESTAMP(`Reversed-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                     as reversed_date,
        NULLIF(TRIM(`Reversed-Time`), '')                as reversed_time,
        TRY_CAST(`Reversed-To-Period` AS DECIMAL(18,0))       as reversed_to_period,
        TRY_CAST(`Reversed-To-Year` AS DECIMAL(18,0))         as reversed_to_year,
        NULLIF(TRIM(`Entered-Currency`), '')             as entered_currency,
        NULLIF(TRIM(`Convert-To-Currency`), '')          as convert_to_currency,
        CAST(TRY_TO_TIMESTAMP(`Currency-Conversion-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)          as currency_conversion_date,
        TRY_CAST(`Currency-Conversion-Rate` AS DECIMAL(18,6)) as currency_conversion_rate,
        IF(UPPER(TRIM(`Approved`)) = 'TRUE', TRUE,
            IF(UPPER(TRIM(`Approved`)) = 'FALSE', FALSE, NULL))
                                                         as approved,
        NULLIF(TRIM(`Approved-By`), '')                  as approved_by,
        CAST(TRY_TO_TIMESTAMP(`Approved-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                     as approved_date,
        NULLIF(TRIM(`Approved-Time`), '')                as approved_time,
        NULLIF(TRIM(`Batch-Number`), '')                 as batch_number,
        IF(UPPER(TRIM(`On-hold`)) = 'TRUE', TRUE,
            IF(UPPER(TRIM(`On-hold`)) = 'FALSE', FALSE, NULL))
                                                         as on_hold,
        IF(UPPER(TRIM(`Direct-post`)) = 'TRUE', TRUE,
            IF(UPPER(TRIM(`Direct-post`)) = 'FALSE', FALSE, NULL))
                                                         as direct_post,
        NULLIF(TRIM(`Internal-Key`), '')                 as internal_key,
        NULLIF(TRIM(`Update-by`), '')                    as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                       as update_date,
        NULLIF(TRIM(`Update-time`), '')                  as update_time,
        NULLIF(TRIM(`Created-by`), '')                   as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                      as created_date,
        NULLIF(TRIM(`Security-Access`), '')              as security_access,
        NULLIF(TRIM(`User-1`), '')                       as user_1,
        NULLIF(TRIM(`alt-search`), '')                   as alt_search,
        NULLIF(TRIM(`Transfer-JDE`), '')                 as transfer_jde,
        NULLIF(TRIM(`Hold-Reason`), '')                  as hold_reason,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS')        as created_date_time,
        NULLIF(TRIM(`Posting-Year-Period`), '')           as posting_year_period,
        CAST(TRY_TO_TIMESTAMP(`Transaction-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                  as transaction_date,
        NULLIF(TRIM(`Image-File`), '')                   as image_file
from {{ source('bronze', 'gl_entry_header') }}
