select
    source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Batch-Warehouse`), '') as batch_warehouse,
        NULLIF(TRIM(`Receipt-Num`), '') as receipt_num,
        NULLIF(TRIM(`Receipt-NumCV`), '') as receipt_numcv,
        NULLIF(TRIM(`Batch-Num`), '') as batch_num,
        NULLIF(TRIM(`Line-Num`), '') as line_num,
        NULLIF(TRIM(`Line-NumCV`), '') as line_numcv,
        NULLIF(TRIM(`Receipt-Status`), '') as receipt_status,
        NULLIF(TRIM(`Output-Type`), '') as output_type,
        NULLIF(TRIM(`Output-Product-Code`), '') as output_product_code,
        NULLIF(TRIM(`Output-Packaging-Code`), '') as output_packaging_code,
        NULLIF(TRIM(`Output-Prod-Pkg-Code`), '') as output_prod_pkg_code,
        NULLIF(TRIM(`Warehouse`), '') as warehouse,
        NULLIF(TRIM(`Lot-Code`), '') as lot_code,
        NULLIF(TRIM(`Location`), '') as location,
        NULLIF(TRIM(`Serial-Number`), '') as serial_number,
        NULLIF(TRIM(`Output-Cust-ID`), '') as output_cust_id,
        NULLIF(TRIM(`Output-Formula-Code`), '') as output_formula_code,
        NULLIF(TRIM(`Output-Version`), '') as output_version,
        NULLIF(TRIM(`Output-Revision`), '') as output_revision,
        TRY_CAST(`Quantity` AS DECIMAL(38,4)) as quantity,
        TRY_CAST(`Quantity-Loss` AS DECIMAL(38,4)) as quantity_loss,
        NULLIF(TRIM(`Qty-Cost-UM`), '') as qty_cost_um,
        NULLIF(TRIM(`Pkg-Cust-ID`), '') as pkg_cust_id,
        NULLIF(TRIM(`Pkg-Formula-Code`), '') as pkg_formula_code,
        NULLIF(TRIM(`Output-Product-Key`), '') as output_product_key,
        NULLIF(TRIM(`Output-Packaging-Key`), '') as output_packaging_key,
        TRY_CAST(`Standard-Cost` AS DECIMAL(38,4)) as standard_cost,
        TRY_CAST(`Average-Cost` AS DECIMAL(38,4)) as average_cost,
        TRY_CAST(`Last-Cost` AS DECIMAL(38,4)) as last_cost,
        TRY_CAST(`Replacement-Cost` AS DECIMAL(38,4)) as replacement_cost,
        TRY_CAST(`Selling-Cost` AS DECIMAL(38,4)) as selling_cost,
        TRY_CAST(`Cost` AS DECIMAL(38,4)) as cost,
        TRY_CAST(`Extended-Cost` AS DECIMAL(38,4)) as extended_cost,
        TRY_CAST(`Extended-Cost-Standard` AS DECIMAL(38,4)) as extended_cost_standard,
        TRY_CAST(`Drum-Off-FG-Extended-Cost` AS DECIMAL(38,4)) as drum_off_fg_extended_cost,
        NULLIF(TRIM(`Step-Num`), '') as step_num,
        NULLIF(TRIM(`Step-Line-Num`), '') as step_line_num,
        TRY_CAST(`Quantity-Manufactured` AS DECIMAL(38,4)) as quantity_manufactured,
        NULLIF(TRIM(`Qty-Manufactured-UM`), '') as qty_manufactured_um,
        NULLIF(TRIM(`Posted-GL-Acct-Ptr`), '') as posted_gl_acct_ptr,
        NULLIF(TRIM(`Posted-Variance-GL-Acct-Ptr`), '') as posted_variance_gl_acct_ptr,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`User-1`), '') as user_1,
        TRY_CAST(`RM-Unit-Cost` AS DECIMAL(38,4)) as rm_unit_cost,
        TRY_CAST(`RM-Extended-Cost` AS DECIMAL(38,4)) as rm_extended_cost,
        TRY_CAST(`WC-Unit-Cost` AS DECIMAL(38,4)) as wc_unit_cost,
        TRY_CAST(`WC-Extended-Cost` AS DECIMAL(38,4)) as wc_extended_cost,
        TRY_CAST(`Labor-Unit-Cost` AS DECIMAL(38,4)) as labor_unit_cost,
        TRY_CAST(`Labor-Extended-Cost` AS DECIMAL(38,4)) as labor_extended_cost,
        TRY_CAST(`OC-Unit-Cost` AS DECIMAL(38,4)) as oc_unit_cost,
        TRY_CAST(`OC-Extended-Cost` AS DECIMAL(38,4)) as oc_extended_cost,
        TRY_CAST(`Output-Unit-Cost` AS DECIMAL(38,4)) as output_unit_cost,
        TRY_CAST(`Output-Extended-Cost` AS DECIMAL(38,4)) as output_extended_cost,
        NULLIF(TRIM(`Supplier-Lot-Code`), '') as supplier_lot_code,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time
from {{ source('bronze', 'batch_rec_output') }}
