select

        source_database,
        nullif(trim(`System-ID`), '')                                   as system_id,
        nullif(trim(`Lot-Code`), '')                                    as lot_code,
        nullif(trim(`Product-Key`), '')                                 as product_key,
        nullif(trim(`Packaging-key`), '')                               as packaging_key,
        nullif(trim(`Internal-Key`), '')                                as internal_key,
        nullif(trim(`Supplier-ID`), '')                                 as supplier_id,
        nullif(trim(`Supplier-Lot-Code`), '')                           as supplier_lot_code,
        nullif(trim(`Description`), '')                                 as description,
        nullif(trim(`Long-description`), '')                            as long_description,
        TRY_CAST(`standard-cost` AS DECIMAL(38,4))                           as standard_cost,
        CAST(TRY_TO_TIMESTAMP(`standard-cost-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                               as standard_cost_date,
        TRY_CAST(`average-cost` AS DECIMAL(38,4))                            as average_cost,
        TRY_CAST(`last-cost` AS DECIMAL(38,4))                               as last_cost,
        CAST(TRY_TO_TIMESTAMP(`last-cost-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                   as last_cost_date,
        TRY_CAST(`replacement-cost` AS DECIMAL(38,4))                        as replacement_cost,
        TRY_CAST(`selling-cost` AS DECIMAL(38,4))                            as selling_cost,
        TRY_CAST(`Inv-Amount@1` AS DECIMAL(38,4))                            as inv_amount_1,
        TRY_CAST(`Inv-Amount@10` AS DECIMAL(38,4))                           as inv_amount_10,
        nullif(trim(`Inv-Status@1`), '')                                as inv_status_1,
        nullif(trim(`Inv-Flag@1`), '')                                  as inv_flag_1,
        nullif(trim(`Unit-of-Meas`), '')                                as unit_of_meas,
        TRY_CAST(`OH-packages` AS DECIMAL(38,4))                             as oh_packages,
        TRY_CAST(`Weight` AS DECIMAL(38,4))                                  as weight,
        nullif(trim(`Weight-UM`), '')                                   as weight_um,
        nullif(trim(`Product-Code`), '')                                as product_code,
        nullif(trim(`Packaging-Code`), '')                              as packaging_code,
        nullif(trim(`Prod-Pkg-Code`), '')                               as prod_pkg_code,
        nullif(trim(`Origin-Country`), '')                              as origin_country,
        CAST(TRY_TO_TIMESTAMP(`Expiration-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                  as expiration_date,
        IF(upper(trim(`Active`)) = 'TRUE', true,
            IF(upper(trim(`Active`)) = 'FALSE', false, null))          as active,
        nullif(trim(`Created-by`), '')                                  as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                     as created_date,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS')                       as created_date_time,
        nullif(trim(`Update-by`), '')                                   as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                      as update_date,
        nullif(trim(`Update-time`), '')                                 as update_time,
        nullif(trim(`Security-Access`), '')                             as security_access,
        nullif(trim(`User-1`), '')                                      as user_1
from {{ source('bronze', 'lot') }}
