select

        source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Packaging-key`), '') as packaging_key,
        NULLIF(TRIM(`Packaging-code`), '') as packaging_code,
        TRY_CAST(`Measure` AS DECIMAL(10,2)) as measure,
        NULLIF(TRIM(`Unit-of-Meas`), '') as unit_of_meas,
        NULLIF(TRIM(`Package`), '') as package,
        NULLIF(TRIM(`Description`), '') as description,
        NULLIF(TRIM(`Long-description`), '') as long_description,
        TRY_CAST(`Cost` AS DECIMAL(18,2)) as cost,
        TRY_CAST(`Price` AS DECIMAL(18,2)) as price,
        TRY_CAST(`Deposit` AS DECIMAL(18,2)) as deposit,
        TRY_CAST(`weight` AS DECIMAL(10,2)) as weight,
        NULLIF(TRIM(`weight-um`), '') as weight_um,
        TRY_CAST(`area-1` AS DECIMAL(10,2)) as area_1,
        NULLIF(TRIM(`area-um`), '') as area_um,
        NULLIF(TRIM(`pkg-color`), '') as pkg_color,
        IF(UPPER(TRIM(`reusable`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`reusable`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_reusable,
        IF(UPPER(TRIM(`waterproof`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`waterproof`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_waterproof,
        IF(UPPER(TRIM(`bulk`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`bulk`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_bulk,
        NULLIF(TRIM(`Pkg-Type`), '') as pkg_type,
        NULLIF(TRIM(`Pkg-image-file`), '') as pkg_image_file,
        NULLIF(TRIM(`Default-Rtg-key`), '') as default_rtg_key,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`DOT-Package`), '') as dot_package,
        TRY_CAST(`Sequence-1` AS DECIMAL(10,0)) as sequence_1,
        IF(UPPER(TRIM(`Serial-Controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Serial-Controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_serial_controlled,
        IF(UPPER(TRIM(`Active`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Active`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_active,
        TRY_CAST(`DOT-Inspection-Window` AS DECIMAL(10,0)) as dot_inspection_window,
        NULLIF(TRIM(`Container-Packaging-Code`), '') as container_packaging_code,
        NULLIF(TRIM(`Container-Packaging-Key`), '') as container_packaging_key,
        TRY_CAST(`Container-Charge` AS DECIMAL(18,2)) as container_charge,
        TRY_CAST(`Replacement-Cost` AS DECIMAL(18,4)) as replacement_cost,
        IF(UPPER(TRIM(`Track-Containers`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Track-Containers`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_track_containers,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyyMMddHH:mm:ss') as created_date_time,
        NULLIF(TRIM(`Packages-Per-Pallet`), '') as packages_per_pallet,
        NULLIF(TRIM(`Inventory-Label-Type`), '') as inventory_label_type,
        TRY_CAST(`Demurrage-Rate` AS DECIMAL(18,4)) as demurrage_rate,
        TRY_CAST(`Demurrage-Days` AS DECIMAL(10,0)) as demurrage_days,
        TRY_CAST(`Credit-Threshold-Days` AS DECIMAL(10,0)) as credit_threshold_days,
        NULLIF(TRIM(`Storage-Code-Local-Reporting`), '') as storage_code_local_reporting,
        NULLIF(TRIM(`Spare-Char-2`), '') as spare_char_2,
        NULLIF(TRIM(`Serial-Container-Exam-Names@1`), '') as serial_container_exam_names_1,
        NULLIF(TRIM(`Serial-Container-Exam-Names@2`), '') as serial_container_exam_names_2,
        NULLIF(TRIM(`Serial-Container-Exam-Names@3`), '') as serial_container_exam_names_3,
        NULLIF(TRIM(`Serial-Container-Exam-Names@4`), '') as serial_container_exam_names_4,
        NULLIF(TRIM(`Serial-Container-Exam-Names@5`), '') as serial_container_exam_names_5,
        NULLIF(TRIM(`Serial-Container-Exam-Names@6`), '') as serial_container_exam_names_6,
        NULLIF(TRIM(`Serial-Container-Exam-Names@7`), '') as serial_container_exam_names_7,
        NULLIF(TRIM(`Serial-Container-Exam-Names@8`), '') as serial_container_exam_names_8,
        NULLIF(TRIM(`Serial-Container-Exam-Names@9`), '') as serial_container_exam_names_9,
        NULLIF(TRIM(`Serial-Container-Exam-Names@10`), '') as serial_container_exam_names_10,
        NULLIF(TRIM(`Serial-Container-Exam-Names@11`), '') as serial_container_exam_names_11,
        NULLIF(TRIM(`Serial-Container-Exam-Names@12`), '') as serial_container_exam_names_12,
        NULLIF(TRIM(`Serial-Container-Exam-Names@13`), '') as serial_container_exam_names_13,
        NULLIF(TRIM(`Serial-Container-Exam-Names@14`), '') as serial_container_exam_names_14,
        NULLIF(TRIM(`Serial-Container-Exam-Names@15`), '') as serial_container_exam_names_15,
        NULLIF(TRIM(`Serial-Container-Exam-Names@16`), '') as serial_container_exam_names_16,
        NULLIF(TRIM(`Serial-Container-Exam-Names@17`), '') as serial_container_exam_names_17,
        NULLIF(TRIM(`Serial-Container-Exam-Names@18`), '') as serial_container_exam_names_18,
        NULLIF(TRIM(`Serial-Container-Exam-Names@19`), '') as serial_container_exam_names_19,
        NULLIF(TRIM(`Serial-Container-Exam-Names@20`), '') as serial_container_exam_names_20,
        IF(UPPER(TRIM(`Small-Package`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Small-Package`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_small_package,
        TRY_CAST(`Acceptable-Prod-Residue-Weight` AS DECIMAL(18,2)) as acceptable_prod_residue_weight,
        NULLIF(TRIM(`Acceptable-Prod-Residue-WeightUM`), '') as acceptable_prod_residue_weightum,
        IF(UPPER(TRIM(`Req-Sequential-Srl-Cont-Exam`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Req-Sequential-Srl-Cont-Exam`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_req_sequential_srl_cont_exam,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@1`), '') as srl_cont_exam_result_type_1,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@2`), '') as srl_cont_exam_result_type_2,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@3`), '') as srl_cont_exam_result_type_3,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@4`), '') as srl_cont_exam_result_type_4,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@5`), '') as srl_cont_exam_result_type_5,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@6`), '') as srl_cont_exam_result_type_6,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@7`), '') as srl_cont_exam_result_type_7,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@8`), '') as srl_cont_exam_result_type_8,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@9`), '') as srl_cont_exam_result_type_9,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@10`), '') as srl_cont_exam_result_type_10,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@11`), '') as srl_cont_exam_result_type_11,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@12`), '') as srl_cont_exam_result_type_12,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@13`), '') as srl_cont_exam_result_type_13,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@14`), '') as srl_cont_exam_result_type_14,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@15`), '') as srl_cont_exam_result_type_15,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@16`), '') as srl_cont_exam_result_type_16,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@17`), '') as srl_cont_exam_result_type_17,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@18`), '') as srl_cont_exam_result_type_18,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@19`), '') as srl_cont_exam_result_type_19,
        NULLIF(TRIM(`Srl-Cont-Exam-Result-Type@20`), '') as srl_cont_exam_result_type_20,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@1`), '') as srl_cont_exam_passing_values_1,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@2`), '') as srl_cont_exam_passing_values_2,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@3`), '') as srl_cont_exam_passing_values_3,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@4`), '') as srl_cont_exam_passing_values_4,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@5`), '') as srl_cont_exam_passing_values_5,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@6`), '') as srl_cont_exam_passing_values_6,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@7`), '') as srl_cont_exam_passing_values_7,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@8`), '') as srl_cont_exam_passing_values_8,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@9`), '') as srl_cont_exam_passing_values_9,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@10`), '') as srl_cont_exam_passing_values_10,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@11`), '') as srl_cont_exam_passing_values_11,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@12`), '') as srl_cont_exam_passing_values_12,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@13`), '') as srl_cont_exam_passing_values_13,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@14`), '') as srl_cont_exam_passing_values_14,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@15`), '') as srl_cont_exam_passing_values_15,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@16`), '') as srl_cont_exam_passing_values_16,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@17`), '') as srl_cont_exam_passing_values_17,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@18`), '') as srl_cont_exam_passing_values_18,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@19`), '') as srl_cont_exam_passing_values_19,
        NULLIF(TRIM(`Srl-Cont-Exam-Passing-Values@20`), '') as srl_cont_exam_passing_values_20,

        NULLIF(TRIM(`Manual-Serial-Container-Entry`), '') as manual_serial_container_entry,
        IF(UPPER(TRIM(`Run-CAS-RQ`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Run-CAS-RQ`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_run_cas_rq,
        NULLIF(TRIM(`TA-Packaging-Type`), '') as ta_packaging_type,
        IF(UPPER(TRIM(`TA-Lease-No-Charge`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`TA-Lease-No-Charge`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_ta_lease_no_charge,
        IF(UPPER(TRIM(`ISN-Controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`ISN-Controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_isn_controlled,
        NULLIF(TRIM(`Spare-Char-3`), '') as spare_char_3,
        NULLIF(TRIM(`Spare-Char-4`), '') as spare_char_4,
        IF(UPPER(TRIM(`Return-To-Same-Mast-Prod`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Return-To-Same-Mast-Prod`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_return_to_same_mast_prod,
        IF(UPPER(TRIM(`Customer-Owned`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Customer-Owned`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_customer_owned,
        IF(UPPER(TRIM(`Spare-Logical-1`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-1`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_spare_logical_1,
        IF(UPPER(TRIM(`Spare-Logical-2`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Spare-Logical-2`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as is_spare_logical_2
from {{ source('bronze', 'packaging') }}
