select
    source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Batch-Warehouse`), '') as batch_warehouse,
        NULLIF(TRIM(`Batch-Num`), '') as batch_num,
        NULLIF(TRIM(`Batch-NumCV`), '') as batch_num_cv,
        NULLIF(TRIM(`Batch-Status`), '') as batch_status,
        NULLIF(TRIM(`Cust-ID`), '') as cust_id,
        NULLIF(TRIM(`Product-Code`), '') as product_code,
        NULLIF(TRIM(`Packaging-Code`), '') as packaging_code,
        NULLIF(TRIM(`Formula-Code`), '') as formula_code,
        NULLIF(TRIM(`Version-1`), '') as version_1,
        NULLIF(TRIM(`Revision`), '') as revision,
        NULLIF(TRIM(`Prod-Pkg-Code`), '') as prod_pkg_code,
        NULLIF(TRIM(`Description`), '') as description,
        NULLIF(TRIM(`Campaign-ID`), '') as campaign_id,
        NULLIF(TRIM(`FG-Receipt-Route`), '') as fg_receipt_route,
        NULLIF(TRIM(`Default-FG-Warehouse`), '') as default_fg_warehouse,
        NULLIF(TRIM(`Default-FG-Lot-Code`), '') as default_fg_lot_code,
        NULLIF(TRIM(`Default-RM-Warehouse`), '') as default_rm_warehouse,
        TRY_CAST(`Total-RM-Quantity` AS DECIMAL(38,4)) as total_rm_quantity,
        TRY_CAST(`Total-RM-Yield` AS DECIMAL(38,4)) as total_rm_yield,
        TRY_CAST(`Total-RM-Yield-Open` AS DECIMAL(38,4)) as total_rm_yield_open,
        TRY_CAST(`Total-RM-Quantity-Loss` AS DECIMAL(38,4)) as total_rm_quantity_loss,
        NULLIF(TRIM(`Total-RM-Loss-Entry-Option`), '') as total_rm_loss_entry_option,
        TRY_CAST(`Quantity` AS DECIMAL(38,4)) as quantity,
        TRY_CAST(`Quantity-Manufactured` AS DECIMAL(38,4)) as quantity_manufactured,
        NULLIF(TRIM(`Qty-Cost-UM`), '') as qty_cost_um,
        TRY_CAST(`Standard-Cost` AS DECIMAL(38,4)) as standard_cost,
        TRY_CAST(`Actual-Cost` AS DECIMAL(38,4)) as actual_cost,
        TRY_CAST(`Drum-Off-Quantity-Loss` AS DECIMAL(38,4)) as drum_off_quantity_loss,
        NULLIF(TRIM(`Drum-Off-Loss-UM`), '') as drum_off_loss_um,
        NULLIF(TRIM(`Rework-Formula`), '') as rework_formula,
        CAST(TRY_TO_TIMESTAMP(`Start-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as start_date,
        NULLIF(TRIM(`Start-Time`), '') as start_time,
        CAST(TRY_TO_TIMESTAMP(`Due-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as due_date,
        NULLIF(TRIM(`Due-Time`), '') as due_time,
        CAST(TRY_TO_TIMESTAMP(`RM-Inv-Allocation-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as rm_inv_allocation_date,
        TRY_CAST(`Batch-Qty-Multiplier-Based-Yield` AS DECIMAL(38,4)) as batch_qty_multiplier_based_yield,
        NULLIF(TRIM(`Internal-Key`), '') as internal_key,
        NULLIF(TRIM(`Cancel-by`), '') as cancel_by,
        CAST(TRY_TO_TIMESTAMP(`Cancel-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as cancel_date,
        NULLIF(TRIM(`Cancel-time`), '') as cancel_time,
        NULLIF(TRIM(`Cancel-Reason`), '') as cancel_reason,
        NULLIF(TRIM(`Cancel-Code`), '') as cancel_code,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`User-1`), '') as user_1,
        NULLIF(TRIM(`Open-Batch`), '') as open_batch,
        NULLIF(TRIM(`Associated-Batch-Warehouse`), '') as associated_batch_warehouse,
        NULLIF(TRIM(`Associated-Batch-Num`), '') as associated_batch_num,
        NULLIF(TRIM(`Associated-Batch-NumCV`), '') as associated_batch_num_cv,
        NULLIF(TRIM(`Print-Container-Req`), '') as print_container_req,
        NULLIF(TRIM(`MES-Actual-Yield-UM`), '') as mes_actual_yield_um,
        NULLIF(TRIM(`Image-File`), '') as image_file,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_1,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
        TRY_CAST(`MES-Actual-Yield` AS DECIMAL(38,4)) as mes_actual_yield,
        TRY_CAST(`Spare-Decimal-2` AS DECIMAL(38,4)) as spare_decimal_2,
        NULLIF(TRIM(`Associated-Batch-Fill-Type`), '') as associated_batch_fill_type,
        NULLIF(TRIM(`Spare-Logical-2`), '') as spare_logical_2,
        NULLIF(TRIM(`Fill-TID`), '') as fill_tid,
        NULLIF(TRIM(`MES-Production-Status`), '') as mes_production_status,
        NULLIF(TRIM(`Default-FG-Supplier-Lot-Code`), '') as default_fg_supplier_lot_code,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as update_date_time,
        CAST(TRY_TO_TIMESTAMP(`Confirmed-Start-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as confirmed_start_date,
        NULLIF(TRIM(`Spare-Logical-3`), '') as spare_logical_3,
        NULLIF(TRIM(`Batch-Status-User`), '') as batch_status_user,
        NULLIF(TRIM(`Production-Type`), '') as production_type,
        TRY_CAST(`Spare-Integer-3` AS DECIMAL(38,0)) as spare_integer_3,
        TRY_CAST(`Spare-Integer-4` AS DECIMAL(38,0)) as spare_integer_4,
        TRY_CAST(`Spare-Integer-5` AS DECIMAL(38,0)) as spare_integer_5,
        TRY_CAST(`Spare-Decimal-3` AS DECIMAL(38,4)) as spare_decimal_3,
        NULLIF(TRIM(`Spare-Char-3`), '') as spare_char_3,
        NULLIF(TRIM(`Spare-Char-4`), '') as spare_char_4
from {{ source('bronze', 'batch_hdr') }}
