select

        source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Supplier-Name`), '') as supplier_name,
        NULLIF(TRIM(`Supplier-Code`), '') as supplier_code,
        NULLIF(TRIM(`Supplier-Key`), '') as supplier_key,
        NULLIF(TRIM(`Supplier-Name-Soundex`), '') as supplier_name_soundex,
        NULLIF(TRIM(`Address-1`), '') as address_1,
        NULLIF(TRIM(`Address-2`), '') as address_2,
        NULLIF(TRIM(`Address-3`), '') as address_3,
        NULLIF(TRIM(`City`), '') as city,
        NULLIF(TRIM(`State`), '') as state,
        NULLIF(TRIM(`Zip`), '') as zip,
        NULLIF(TRIM(`Country`), '') as country,
        NULLIF(TRIM(`Phone`), '') as phone,
        NULLIF(TRIM(`FAX`), '') as fax,
        NULLIF(TRIM(`History-Company`), '') as history_company,
        NULLIF(TRIM(`Group-ID`), '') as group_id,
        NULLIF(TRIM(`supp-division`), '') as supp_division,
        NULLIF(TRIM(`Default-terms`), '') as default_terms,
        NULLIF(TRIM(`Default-Currency`), '') as default_currency,
        NULLIF(TRIM(`Default-Payment-method`), '') as default_payment_method,
        TRY_CAST(`Default-discount` AS DECIMAL(5,2)) as default_discount,
        CAST(TRY_TO_TIMESTAMP(`Start-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as start_date,
        NULLIF(TRIM(`Supplier-Status`), '') as supplier_status,
        IF(UPPER(TRIM(`Active`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Active`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as active,
        IF(UPPER(TRIM(`Requires-1099`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Requires-1099`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as requires_1099,
        NULLIF(TRIM(`TAX-ID`), '') as tax_id,
        CAST(TRY_TO_TIMESTAMP(`Date-First-Order`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as date_first_order,
        NULLIF(TRIM(`Legal-Name-1099`), '') as legal_name_1099,
        NULLIF(TRIM(`Legal-ID-1099`), '') as legal_id_1099,
        IF(UPPER(TRIM(`Freight-Supplier`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Freight-Supplier`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as freight_supplier,
        NULLIF(TRIM(`Freight-ID`), '') as freight_id,
        NULLIF(TRIM(`Supplier-ap-acct-ptr`), '') as supplier_ap_acct_ptr,
        TRY_CAST(`Supplier-amount-limit` AS DECIMAL(18,2)) as supplier_amount_limit,
        NULLIF(TRIM(`default-tax-code`), '') as default_tax_code,
        NULLIF(TRIM(`alt-search`), '') as alt_search,
        NULLIF(TRIM(`cust-key`), '') as cust_key,
        TRY_CAST(`Zone-Key` AS DECIMAL(18,0)) as zone_key,
        IF(UPPER(TRIM(`Internal-Site`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Internal-Site`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as internal_site,
        NULLIF(TRIM(`Shipper-ID`), '') as shipper_id,
        NULLIF(TRIM(`Ship-Mode`), '') as ship_mode,
        IF(UPPER(TRIM(`Manual-Use-Tax`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Manual-Use-Tax`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as manual_use_tax,
        NULLIF(TRIM(`Default-Payment-Comment`), '') as default_payment_comment,
        NULLIF(TRIM(`Payment-Frequency`), '') as payment_frequency,
        IF(UPPER(TRIM(`Temporary-Supplier`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Temporary-Supplier`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as temporary_supplier,
        TRY_CAST(`Days-to-clear` AS DECIMAL(10,0)) as days_to_clear,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyyMMddHH:mm:ss') as created_date_time,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyyMMddHH:mm:ss') as update_date_time,
        NULLIF(TRIM(`Security-Access-1`), '') as security_access_1,
        NULLIF(TRIM(`User-1`), '') as user_1,
        NULLIF(TRIM(`Uber-Keywords`), '') as uber_keywords,
        NULLIF(TRIM(`Uber-Search`), '') as uber_search,
        NULLIF(TRIM(`Address-Change`), '') as address_change,
        NULLIF(TRIM(`Default-SPU-New-Product-Prefix`), '') as default_spu_new_product_prefix,
        IF(UPPER(TRIM(`Require-Ship-From-ID-in-SPU`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Require-Ship-From-ID-in-SPU`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as require_ship_from_id_in_spu,
        NULLIF(TRIM(`Image-File`), '') as image_file,
        NULLIF(TRIM(`Spare-Char-1`), '') as spare_char_1,
        NULLIF(TRIM(`Spare-Char-2`), '') as spare_char_2,
        NULLIF(TRIM(`Spare-Char-3`), '') as spare_char_3
from {{ source('bronze', 'suppname') }}
