with cleaned as (

    select
-- 1. IDENTIFIERS & CORE INFO
        source_database,
        nullif(trim(`System-ID`), '')         as system_id,
        nullif(trim(`cust-name`), '')         as cust_name,
        nullif(trim(`Cust-code`), '')         as cust_code,
        nullif(trim(`Cust-key`), '')          as cust_key,
        nullif(trim(`Cust-Name-Soundex`), '') as cust_name_soundex,
        nullif(trim(`Legal-Name`), '')        as legal_name,
        nullif(trim(`alt-search`), '')        as alt_search,
        nullif(trim(`Group-ID`), '')          as group_id,
        nullif(trim(`DB-Code`), '')           as db_code,
        nullif(trim(`Cust-Status`), '')       as cust_status,
        nullif(trim(`customer-class`), '')    as customer_class,
        nullif(trim(`Trade-class`), '')       as trade_class,
        nullif(trim(`Cust-division`), '')     as cust_division,
        nullif(trim(`Industry-code`), '')     as industry_code,
        nullif(trim(`Language`), '')          as language,

        -- 2. CONTACT & ADDRESS
        nullif(trim(`Address-1`), '') as address_1,
        nullif(trim(`Address-2`), '') as address_2,
        nullif(trim(`Address-3`), '') as address_3,
        nullif(trim(`City`), '')      as city,
        nullif(trim(`State`), '')     as state,
        nullif(trim(`Zip`), '')       as zip,
        nullif(trim(`Country`), '')   as country,
        nullif(trim(`Phone`), '')     as phone,
        nullif(trim(`FAX`), '')       as fax,

        -- 3. FINANCIALS & AMOUNTS
        TRY_CAST(`Normal-payment-days` AS DECIMAL(18,0))      as normal_payment_days,
        TRY_CAST(`Default-discount` AS DECIMAL(18,2))         as default_discount,
        TRY_CAST(`Credit-limit` AS DECIMAL(38,2))             as credit_limit,
        TRY_CAST(`Overdue-amount` AS DECIMAL(38,2))           as overdue_amount,
        TRY_CAST(`Over-due-days` AS DECIMAL(18,0))            as over_due_days,
        TRY_CAST(`Overdue-percentage` AS DECIMAL(18,2))       as overdue_percentage,
        TRY_CAST(`min-fin-chg-threshold` AS DECIMAL(38,2))    as min_fin_chg_threshold,
        TRY_CAST(`min-fin-chg-amt` AS DECIMAL(38,2))          as min_fin_chg_amt,
        TRY_CAST(`Credit-score` AS DECIMAL(38,2))             as credit_score,
        TRY_CAST(`Customer-priority` AS DECIMAL(18,0))        as customer_priority,
        TRY_CAST(`Minimum-Order-Quantity` AS DECIMAL(18,0))   as minimum_order_quantity,
        nullif(trim(`Minimum-Order-Quantity-UM`), '')     as minimum_order_quantity_um,
        nullif(trim(`Default-Currency`), '')              as default_currency,
        nullif(trim(`Credit-Limit-Currency`), '')         as credit_limit_currency,

        -- 4. LOGISTICS & SALES
        nullif(trim(`Default-terms`), '')            as default_terms,
        nullif(trim(`Default-Payment-method`), '')   as default_payment_method,
        nullif(trim(`Normal-payment-method`), '')    as normal_payment_method,
        nullif(trim(`Default-sales-agent`), '')      as default_sales_agent,
        nullif(trim(`Default-sales-agent-2`), '')    as default_sales_agent_2,
        nullif(trim(`Agent-code`), '')               as agent_code,
        nullif(trim(`Territory`), '')                as territory,
        nullif(trim(`default-warehouse`), '')        as default_warehouse,
        nullif(trim(`Originating-Warehouse`), '')    as originating_warehouse,
        nullif(trim(`Preferred-Shipper`), '')        as preferred_shipper,
        nullif(trim(`Preferred-Ship-Mode`), '')      as preferred_ship_mode,
        nullif(trim(`Preferred-Route`), '')          as preferred_route,
        TRY_CAST(`Zone-Key` AS DECIMAL(18,0))             as zone_key,
        nullif(trim(`Default-price-code`), '')       as default_price_code,
        nullif(trim(`Default-Price-Group`), '')      as default_price_group,

        -- 5. BOOLEAN LOGIC
        IF(upper(trim(`Active`)) = 'TRUE', true, IF(upper(trim(`Active`)) = 'FALSE', false, null))                                             as active,
        IF(upper(trim(`Gets-statement`)) = 'TRUE', true, IF(upper(trim(`Gets-statement`)) = 'FALSE', false, null))                             as gets_statement,
        IF(upper(trim(`Gets-finance-charges`)) = 'TRUE', true, IF(upper(trim(`Gets-finance-charges`)) = 'FALSE', false, null))                 as gets_finance_charges,
        IF(upper(trim(`target-customer`)) = 'TRUE', true, IF(upper(trim(`target-customer`)) = 'FALSE', false, null))                          as target_customer,
        IF(upper(trim(`Gets-Price-change`)) = 'TRUE', true, IF(upper(trim(`Gets-Price-change`)) = 'FALSE', false, null))                      as gets_price_change,
        IF(upper(trim(`Pays-superfund`)) = 'TRUE', true, IF(upper(trim(`Pays-superfund`)) = 'FALSE', false, null))                            as pays_superfund,
        IF(upper(trim(`Gets-misc-charges`)) = 'TRUE', true, IF(upper(trim(`Gets-misc-charges`)) = 'FALSE', false, null))                      as gets_misc_charges,
        IF(upper(trim(`Gets-container-service`)) = 'TRUE', true, IF(upper(trim(`Gets-container-service`)) = 'FALSE', false, null))            as gets_container_service,
        IF(upper(trim(`Manifest-needed`)) = 'TRUE', true, IF(upper(trim(`Manifest-needed`)) = 'FALSE', false, null))                          as manifest_needed,
        IF(upper(trim(`On-credit-hold`)) = 'TRUE', true, IF(upper(trim(`On-credit-hold`)) = 'FALSE', false, null))                            as on_credit_hold,
        IF(upper(trim(`On-credit-watch`)) = 'TRUE', true, IF(upper(trim(`On-credit-watch`)) = 'FALSE', false, null))                          as on_credit_watch,
        IF(upper(trim(`Req-ord-acknow`)) = 'TRUE', true, IF(upper(trim(`Req-ord-acknow`)) = 'FALSE', false, null))                            as req_ord_acknow,
        IF(upper(trim(`Req-Invoice`)) = 'TRUE', true, IF(upper(trim(`Req-Invoice`)) = 'FALSE', false, null))                                  as req_invoice,
        IF(upper(trim(`Req-C-of-A`)) = 'TRUE', true, IF(upper(trim(`Req-C-of-A`)) = 'FALSE', false, null))                                   as req_c_of_a,
        IF(upper(trim(`Internal-Site`)) = 'TRUE', true, IF(upper(trim(`Internal-Site`)) = 'FALSE', false, null))                              as internal_site,
        IF(upper(trim(`Apply-Sales-Tax`)) = 'TRUE', true, IF(upper(trim(`Apply-Sales-Tax`)) = 'FALSE', false, null))                          as apply_sales_tax,
        IF(upper(trim(`Require-Cust-PO-Order-Time`)) = 'TRUE', true, IF(upper(trim(`Require-Cust-PO-Order-Time`)) = 'FALSE', false, null))    as require_cust_po_order_time,

        -- 6. DATES & TIMESTAMPS
        CAST(TRY_TO_TIMESTAMP(`Start-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                    as start_date,
        CAST(TRY_TO_TIMESTAMP(`Date-First-Order`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)              as date_first_order,
        CAST(TRY_TO_TIMESTAMP(`First-Sale-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)               as first_sale_date,
        CAST(TRY_TO_TIMESTAMP(`Last-Sale-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                as last_sale_date,
        CAST(TRY_TO_TIMESTAMP(`Credit-review-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)            as credit_review_date,
        CAST(TRY_TO_TIMESTAMP(`Fed-Tax-Exempt-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)           as fed_tax_exempt_date,
        CAST(TRY_TO_TIMESTAMP(`State-Tax-Exempt-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)         as state_tax_exempt_date,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                   as update_date,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                  as created_date,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS')     as update_date_time,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS')    as created_date_time,

        -- 7. CREDIT MATRIX (1-15)
        TRY_CAST(`Credit-matrix@1` AS DECIMAL(38,2)) as credit_matrix_1,
        TRY_CAST(`Credit-matrix@2` AS DECIMAL(38,2)) as credit_matrix_2,
        TRY_CAST(`Credit-matrix@3` AS DECIMAL(38,2)) as credit_matrix_3,
        TRY_CAST(`Credit-matrix@4` AS DECIMAL(38,2)) as credit_matrix_4,
        TRY_CAST(`Credit-matrix@5` AS DECIMAL(38,2)) as credit_matrix_5,
        TRY_CAST(`Credit-matrix@6` AS DECIMAL(38,2)) as credit_matrix_6,
        TRY_CAST(`Credit-matrix@7` AS DECIMAL(38,2)) as credit_matrix_7,
        TRY_CAST(`Credit-matrix@8` AS DECIMAL(38,2)) as credit_matrix_8,
        TRY_CAST(`Credit-matrix@9` AS DECIMAL(38,2)) as credit_matrix_9,
        TRY_CAST(`Credit-matrix@10` AS DECIMAL(38,2)) as credit_matrix_10,
        TRY_CAST(`Credit-matrix@11` AS DECIMAL(38,2)) as credit_matrix_11,
        TRY_CAST(`Credit-matrix@12` AS DECIMAL(38,2)) as credit_matrix_12,
        TRY_CAST(`Credit-matrix@13` AS DECIMAL(38,2)) as credit_matrix_13,
        TRY_CAST(`Credit-matrix@14` AS DECIMAL(38,2)) as credit_matrix_14,
        TRY_CAST(`Credit-matrix@15` AS DECIMAL(38,2)) as credit_matrix_15,

        -- 8. TAX & LEGAL
        nullif(trim(`Fed-TAX-exempt`), '')                as fed_tax_exempt,
        nullif(trim(`State-tax-exempt`), '')              as state_tax_exempt,
        nullif(trim(`default-sales-tax-code`), '')        as default_sales_tax_code,
        nullif(trim(`Avatax-Exempt-Code`), '')            as avatax_exempt_code,
        nullif(trim(`Image-File-Federal-Tax-Exempt`), '') as image_file_federal_tax_exempt,
        nullif(trim(`Image-File-State-Tax-Exempt`), '')   as image_file_state_tax_exempt,

        -- 9. SPARE & USER FIELDS
        nullif(trim(`User-Char-1`), '')          as user_char_1,
        nullif(trim(`User-Char-2`), '')          as user_char_2,
        TRY_CAST(`User-Decimal-1` AS DECIMAL(38,2))   as user_decimal_1,
        TRY_CAST(`User-Decimal-2` AS DECIMAL(38,2))   as user_decimal_2,
        nullif(trim(`Spare-Char-3`), '')          as spare_char_3,
        nullif(trim(`Spare-Char-5`), '')          as spare_char_5,
        TRY_CAST(`Spare-Decimal-1` AS DECIMAL(38,10)) as spare_decimal_1,
        TRY_CAST(`Spare-Decimal-2` AS DECIMAL(38,10)) as spare_decimal_2,

        -- 10. METADATA & SYSTEM
        nullif(trim(`Update-by`), '')       as update_by,
        nullif(trim(`Update-time`), '')     as update_time,
        nullif(trim(`Created-by`), '')      as created_by,
        nullif(trim(`History-Company`), '') as history_company,
        nullif(trim(`AR-GL-Acct-ptr`), '')  as ar_gl_acct_ptr,
        nullif(trim(`Image-File`), '')      as image_file,
        nullif(trim(`Uber-Keywords`), '')   as uber_keywords,
        nullif(trim(`Uber-Search`), '')     as uber_search
    from {{ source('bronze', 'cust') }}

),

free_field as (
    select
        source_database,
        TRY_CAST(data_key AS DECIMAL(18,0)) as data_key_num,
        cust_segment
    from {{ ref('stg_free_field_data') }}
    where program_id = 'Custfmnt'
      and cust_segment is not null
),

plugs as (
    select
        'CHINA'              as source_database,
        null                 as system_id,
        'China Budget Plug'  as cust_name,
        '99999'              as cust_code,
        null                 as cust_key,
        null                 as cust_name_soundex,
        null                 as legal_name,
        null                 as alt_search,
        'DERIVATIVE GROWTH'  as group_id,
        null                 as db_code,
        null                 as cust_status,
        null                 as customer_class,
        null                 as trade_class,
        null                 as cust_division,
        null                 as industry_code,
        null                 as language,
        null                 as address_1,
        null                 as address_2,
        null                 as address_3,
        null                 as city,
        null                 as state,
        null                 as zip,
        null                 as country,
        null                 as phone,
        null                 as fax,
        null                 as normal_payment_days,
        null                 as default_discount,
        null                 as credit_limit,
        null                 as overdue_amount,
        null                 as over_due_days,
        null                 as overdue_percentage,
        null                 as min_fin_chg_threshold,
        null                 as min_fin_chg_amt,
        null                 as credit_score,
        null                 as customer_priority,
        null                 as minimum_order_quantity,
        null                 as minimum_order_quantity_um,
        null                 as default_currency,
        null                 as credit_limit_currency,
        null                 as default_terms,
        null                 as default_payment_method,
        null                 as normal_payment_method,
        null                 as default_sales_agent,
        'Sissic H.'          as default_sales_agent_2,
        null                 as agent_code,
        null                 as territory,
        null                 as default_warehouse,
        null                 as originating_warehouse,
        null                 as preferred_shipper,
        null                 as preferred_ship_mode,
        null                 as preferred_route,
        null                 as zone_key,
        null                 as default_price_code,
        null                 as default_price_group,
        null                 as active,
        null                 as gets_statement,
        null                 as gets_finance_charges,
        null                 as target_customer,
        null                 as gets_price_change,
        null                 as pays_superfund,
        null                 as gets_misc_charges,
        null                 as gets_container_service,
        null                 as manifest_needed,
        null                 as on_credit_hold,
        null                 as on_credit_watch,
        null                 as req_ord_acknow,
        null                 as req_invoice,
        null                 as req_c_of_a,
        null                 as internal_site,
        null                 as apply_sales_tax,
        null                 as require_cust_po_order_time,
        null                 as start_date,
        null                 as date_first_order,
        null                 as first_sale_date,
        null                 as last_sale_date,
        null                 as credit_review_date,
        null                 as fed_tax_exempt_date,
        null                 as state_tax_exempt_date,
        null                 as update_date,
        null                 as created_date,
        null                 as update_date_time,
        null                 as created_date_time,
        null                 as credit_matrix_1,
        null                 as credit_matrix_2,
        null                 as credit_matrix_3,
        null                 as credit_matrix_4,
        null                 as credit_matrix_5,
        null                 as credit_matrix_6,
        null                 as credit_matrix_7,
        null                 as credit_matrix_8,
        null                 as credit_matrix_9,
        null                 as credit_matrix_10,
        null                 as credit_matrix_11,
        null                 as credit_matrix_12,
        null                 as credit_matrix_13,
        null                 as credit_matrix_14,
        null                 as credit_matrix_15,
        null                 as fed_tax_exempt,
        null                 as state_tax_exempt,
        null                 as default_sales_tax_code,
        null                 as avatax_exempt_code,
        null                 as image_file_federal_tax_exempt,
        null                 as image_file_state_tax_exempt,
        null                 as user_char_1,
        null                 as user_char_2,
        null                 as user_decimal_1,
        null                 as user_decimal_2,
        null                 as spare_char_3,
        null                 as spare_char_5,
        null                 as spare_decimal_1,
        null                 as spare_decimal_2,
        null                 as update_by,
        null                 as update_time,
        null                 as created_by,
        null                 as history_company,
        null                 as ar_gl_acct_ptr,
        null                 as image_file,
        null                 as uber_keywords,
        null                 as uber_search,
        -- derived columns that bypass the final select logic
        'DERIVATIVE GROWTH'  as cust_group,
        'PURE DERIVATIVES'   as cust_segment
)

-- Final select -- unchanged except for the join/cast fix below
select
    c.*,
    coalesce(c.group_id, c.cust_name) as cust_group,
    ff.cust_segment                   as cust_segment
from cleaned c
left join free_field ff
    on  c.source_database                        = ff.source_database
    and TRY_CAST(c.cust_key AS DECIMAL(18,0))     = ff.data_key_num

union all

select * from plugs
