select
    source_database,

        nullif(trim(`Cust-ID`), '')                                     as cust_id,
        nullif(trim(`Cust-Key`), '')                                    as cust_key,
        nullif(trim(`Product-Key`), '')                                 as product_key,
        nullif(trim(`Packaging-Key`), '')                               as packaging_key,
        TRY_CAST(`Internal-Key` AS DECIMAL(18,0))                            as internal_key,
        nullif(trim(`Internal-KeyCV`), '')                              as internal_key_cv,
        nullif(trim(`Control-Key`), '')                                 as control_key,
        nullif(trim(`Product-Code`), '')                                as product_code,
        nullif(trim(`Packaging-Code`), '')                              as packaging_code,
        nullif(trim(`Prod-Pkg-Code`), '')                               as prod_pkg_code,
        TRY_CAST(`Sale-Measure` AS DECIMAL(18,2))                            as sale_measure,
        nullif(trim(`Sale-MeasureCV`), '')                              as sale_measure_cv,
        nullif(trim(`Sale-UM`), '')                                     as sale_um,
        nullif(trim(`Sale-Pkg`), '')                                    as sale_pkg,
        nullif(trim(`Price-Breaks-Basis`), '')                          as price_breaks_basis,
        nullif(trim(`Price-UM`), '')                                    as price_um,
        nullif(trim(`Breaks-UM`), '')                                   as breaks_um,
        nullif(trim(`Price-Adjustment-Type`), '')                       as price_adjustment_type,
        nullif(trim(`Currency`), '')                                    as currency,
        CAST(TRY_TO_TIMESTAMP(`From-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                        as from_date,
        CAST(TRY_TO_TIMESTAMP(`To-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                          as to_date,
        CAST(TRY_TO_TIMESTAMP(`Firm-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                        as firm_date,
        IF(upper(trim(`To-Date-Exists`)) = 'YES', true,
            IF(upper(trim(`To-Date-Exists`)) = 'NO', false, null))     as to_date_exists,
        IF(upper(trim(`Current-Price`)) = 'YES', true,
            IF(upper(trim(`Current-Price`)) = 'NO', false, null))      as current_price,
        IF(upper(trim(`Printed-Flag`)) = 'YES', true,
            IF(upper(trim(`Printed-Flag`)) = 'NO', false, null))       as printed,
        IF(upper(trim(`Spare-Logical-1`)) = 'YES', true,
            IF(upper(trim(`Spare-Logical-1`)) = 'NO', false, null))    as spare_logical_1,
        TRY_CAST(`Breaks-From@1` AS DECIMAL(38,4))                           as breaks_from_1,
        TRY_CAST(`Breaks-From@2` AS DECIMAL(38,4))                           as breaks_from_2,
        TRY_CAST(`Breaks-From@3` AS DECIMAL(38,4))                           as breaks_from_3,
        TRY_CAST(`Breaks-From@4` AS DECIMAL(38,4))                           as breaks_from_4,
        TRY_CAST(`Breaks-From@5` AS DECIMAL(38,4))                           as breaks_from_5,
        TRY_CAST(`Breaks-From@6` AS DECIMAL(38,4))                           as breaks_from_6,
        TRY_CAST(`Breaks-From@7` AS DECIMAL(38,4))                           as breaks_from_7,
        TRY_CAST(`Breaks-From@8` AS DECIMAL(38,4))                           as breaks_from_8,
        TRY_CAST(`Breaks-From@9` AS DECIMAL(38,4))                           as breaks_from_9,
        TRY_CAST(`Breaks-From@10` AS DECIMAL(38,4))                           as breaks_from_10,
        TRY_CAST(`Breaks-From@11` AS DECIMAL(38,4))                           as breaks_from_11,
        TRY_CAST(`Breaks-From@12` AS DECIMAL(38,4))                           as breaks_from_12,
        TRY_CAST(`Breaks-From@13` AS DECIMAL(38,4))                           as breaks_from_13,
        TRY_CAST(`Breaks-From@14` AS DECIMAL(38,4))                           as breaks_from_14,
        TRY_CAST(`Breaks-From@15` AS DECIMAL(38,4))                           as breaks_from_15,
        TRY_CAST(`Breaks-From@16` AS DECIMAL(38,4))                           as breaks_from_16,
        TRY_CAST(`Breaks-From@17` AS DECIMAL(38,4))                           as breaks_from_17,
        TRY_CAST(`Breaks-From@18` AS DECIMAL(38,4))                           as breaks_from_18,
        TRY_CAST(`Breaks-From@19` AS DECIMAL(38,4))                           as breaks_from_19,
        TRY_CAST(`Breaks-From@20` AS DECIMAL(38,4))                           as breaks_from_20,
        TRY_CAST(`Breaks-To@1` AS DECIMAL(38,4))                             as breaks_to_1,
        TRY_CAST(`Breaks-To@2` AS DECIMAL(38,4))                             as breaks_to_2,
        TRY_CAST(`Breaks-To@3` AS DECIMAL(38,4))                             as breaks_to_3,
        TRY_CAST(`Breaks-To@4` AS DECIMAL(38,4))                             as breaks_to_4,
        TRY_CAST(`Breaks-To@5` AS DECIMAL(38,4))                             as breaks_to_5,
        TRY_CAST(`Breaks-To@6` AS DECIMAL(38,4))                             as breaks_to_6,
        TRY_CAST(`Breaks-To@7` AS DECIMAL(38,4))                             as breaks_to_7,
        TRY_CAST(`Breaks-To@8` AS DECIMAL(38,4))                             as breaks_to_8,
        TRY_CAST(`Breaks-To@9` AS DECIMAL(38,4))                             as breaks_to_9,
        TRY_CAST(`Breaks-To@10` AS DECIMAL(38,4))                             as breaks_to_10,
        TRY_CAST(`Breaks-To@11` AS DECIMAL(38,4))                             as breaks_to_11,
        TRY_CAST(`Breaks-To@12` AS DECIMAL(38,4))                             as breaks_to_12,
        TRY_CAST(`Breaks-To@13` AS DECIMAL(38,4))                             as breaks_to_13,
        TRY_CAST(`Breaks-To@14` AS DECIMAL(38,4))                             as breaks_to_14,
        TRY_CAST(`Breaks-To@15` AS DECIMAL(38,4))                             as breaks_to_15,
        TRY_CAST(`Breaks-To@16` AS DECIMAL(38,4))                             as breaks_to_16,
        TRY_CAST(`Breaks-To@17` AS DECIMAL(38,4))                             as breaks_to_17,
        TRY_CAST(`Breaks-To@18` AS DECIMAL(38,4))                             as breaks_to_18,
        TRY_CAST(`Breaks-To@19` AS DECIMAL(38,4))                             as breaks_to_19,
        TRY_CAST(`Breaks-To@20` AS DECIMAL(38,4))                             as breaks_to_20,
        TRY_CAST(`Breaks-Price@1` AS DECIMAL(38,4))                          as breaks_price_1,
        TRY_CAST(`Breaks-Price@2` AS DECIMAL(38,4))                          as breaks_price_2,
        TRY_CAST(`Breaks-Price@3` AS DECIMAL(38,4))                          as breaks_price_3,
        TRY_CAST(`Breaks-Price@4` AS DECIMAL(38,4))                          as breaks_price_4,
        TRY_CAST(`Breaks-Price@5` AS DECIMAL(38,4))                          as breaks_price_5,
        TRY_CAST(`Breaks-Price@6` AS DECIMAL(38,4))                          as breaks_price_6,
        TRY_CAST(`Breaks-Price@7` AS DECIMAL(38,4))                          as breaks_price_7,
        TRY_CAST(`Breaks-Price@8` AS DECIMAL(38,4))                          as breaks_price_8,
        TRY_CAST(`Breaks-Price@9` AS DECIMAL(38,4))                          as breaks_price_9,
        TRY_CAST(`Breaks-Price@10` AS DECIMAL(38,4))                          as breaks_price_10,
        TRY_CAST(`Breaks-Price@11` AS DECIMAL(38,4))                          as breaks_price_11,
        TRY_CAST(`Breaks-Price@12` AS DECIMAL(38,4))                          as breaks_price_12,
        TRY_CAST(`Breaks-Price@13` AS DECIMAL(38,4))                          as breaks_price_13,
        TRY_CAST(`Breaks-Price@14` AS DECIMAL(38,4))                          as breaks_price_14,
        TRY_CAST(`Breaks-Price@15` AS DECIMAL(38,4))                          as breaks_price_15,
        TRY_CAST(`Breaks-Price@16` AS DECIMAL(38,4))                          as breaks_price_16,
        TRY_CAST(`Breaks-Price@17` AS DECIMAL(38,4))                          as breaks_price_17,
        TRY_CAST(`Breaks-Price@18` AS DECIMAL(38,4))                          as breaks_price_18,
        TRY_CAST(`Breaks-Price@19` AS DECIMAL(38,4))                          as breaks_price_19,
        TRY_CAST(`Breaks-Price@20` AS DECIMAL(38,4))                          as breaks_price_20,
        TRY_CAST(`TVA` AS DECIMAL(38,4))                                     as tva,
        TRY_CAST(`Allowance-1` AS DECIMAL(38,4))                             as allowance_1,
        TRY_CAST(`Discount-1` AS DECIMAL(18,2))                              as discount_1,
        TRY_CAST(`Discount-2` AS DECIMAL(18,2))                              as discount_2,
        TRY_CAST(`Notification-Days` AS DECIMAL(18,0))                       as notification_days,
        TRY_CAST(`Spare-Integer-1` AS DECIMAL(18,0))                         as spare_integer_1,
        TRY_CAST(`Spare-Decimal-1` AS DECIMAL(38,10))                        as spare_decimal_1,
        nullif(trim(`Security-Access`), '')                             as security_access,
        nullif(trim(`User-1`), '')                                      as user_1,
        nullif(trim(`Letter-Format`), '')                               as letter_format,
        nullif(trim(`Printed-By`), '')                                  as printed_by,
        nullif(trim(`Image-File`), '')                                  as image_file,
        nullif(trim(`Spare-Char-2`), '')                                as spare_char_2,
        nullif(trim(`Created-By`), '')                                  as created_by,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS')                       as created_date_time,
        nullif(trim(`Update-By`), '')                                  as update_by,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS')                       as update_date_time,
        TRY_TO_TIMESTAMP(`Printed-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS')                       as printed_date_time,
        CAST(TRY_TO_TIMESTAMP(`Spare-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE)                                     as spare_date_1
from {{ source('bronze', 'cust_prod_price') }}
