select

        source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Product-Key`), '') as product_key,
        NULLIF(TRIM(`Packaging-Key`), '') as packaging_key,
        NULLIF(TRIM(`Facility`), '') as facility,
        NULLIF(TRIM(`Lot-Code`), '') as lot_code,
        TRY_CAST(`Inv-Amount@1` AS DECIMAL(18,4)) as inv_amount_1,
        TRY_CAST(`Inv-Amount@2` AS DECIMAL(18,4)) as inv_amount_2,
        TRY_CAST(`Inv-Amount@3` AS DECIMAL(18,4)) as inv_amount_3,
        TRY_CAST(`Inv-Amount@4` AS DECIMAL(18,4)) as inv_amount_4,
        TRY_CAST(`Inv-Amount@5` AS DECIMAL(18,4)) as inv_amount_5,
        TRY_CAST(`Inv-Amount@6` AS DECIMAL(18,4)) as inv_amount_6,
        TRY_CAST(`Inv-Amount@7` AS DECIMAL(18,4)) as inv_amount_7,
        TRY_CAST(`Inv-Amount@8` AS DECIMAL(18,4)) as inv_amount_8,
        TRY_CAST(`Inv-Amount@9` AS DECIMAL(18,4)) as inv_amount_9,
        TRY_CAST(`Inv-Amount@10` AS DECIMAL(18,4)) as inv_amount_10,
        NULLIF(TRIM(`Inv-Status@1`), '') as inv_status_1,
        NULLIF(TRIM(`Inv-Status@2`), '') as inv_status_2,
        NULLIF(TRIM(`Inv-Status@3`), '') as inv_status_3,
        NULLIF(TRIM(`Inv-Status@4`), '') as inv_status_4,
        NULLIF(TRIM(`Inv-Status@5`), '') as inv_status_5,
        NULLIF(TRIM(`Inv-Status@6`), '') as inv_status_6,
        NULLIF(TRIM(`Inv-Status@7`), '') as inv_status_7,
        NULLIF(TRIM(`Inv-Status@8`), '') as inv_status_8,
        NULLIF(TRIM(`Inv-Status@9`), '') as inv_status_9,
        NULLIF(TRIM(`Inv-Status@10`), '') as inv_status_10,
        IF(UPPER(TRIM(`Inv-Flag@1`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@1`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_1,
        IF(UPPER(TRIM(`Inv-Flag@2`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@2`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_2,
        IF(UPPER(TRIM(`Inv-Flag@3`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@3`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_3,
        IF(UPPER(TRIM(`Inv-Flag@4`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@4`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_4,
        IF(UPPER(TRIM(`Inv-Flag@5`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@5`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_5,
        IF(UPPER(TRIM(`Inv-Flag@6`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@6`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_6,
        IF(UPPER(TRIM(`Inv-Flag@7`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@7`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_7,
        IF(UPPER(TRIM(`Inv-Flag@8`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@8`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_8,
        IF(UPPER(TRIM(`Inv-Flag@9`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@9`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_9,
        IF(UPPER(TRIM(`Inv-Flag@10`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Inv-Flag@10`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as inv_flag_10,
        NULLIF(TRIM(`Unit-of-Meas`), '') as unit_of_meas,
        TRY_CAST(`OH-Packages` AS DECIMAL(18,0)) as oh_packages,
        IF(UPPER(TRIM(`Serial-Number-Controlled`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Serial-Number-Controlled`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as serial_number_controlled,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`OH-Increase-User-List`), '') as oh_increase_user_list,
        NULLIF(TRIM(`User-1`), '') as user_1,
        NULLIF(TRIM(`Facility-Type`), '') as facility_type,
        IF(UPPER(TRIM(`Internal-Warehouse`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Internal-Warehouse`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as internal_warehouse,
        TRY_CAST(`Lab-Results@1` AS DECIMAL(18,4)) as lab_results_1,
        TRY_CAST(`Lab-Results@2` AS DECIMAL(18,4)) as lab_results_2,
        TRY_CAST(`Lab-Results@3` AS DECIMAL(18,4)) as lab_results_3,
        TRY_CAST(`Lab-Results@4` AS DECIMAL(18,4)) as lab_results_4,
        TRY_CAST(`Lab-Results@5` AS DECIMAL(18,4)) as lab_results_5,
        TRY_CAST(`Lab-Results@6` AS DECIMAL(18,4)) as lab_results_6,
        TRY_CAST(`Lab-Results@7` AS DECIMAL(18,4)) as lab_results_7,
        TRY_CAST(`Lab-Results@8` AS DECIMAL(18,4)) as lab_results_8,
        TRY_CAST(`Lab-Results@9` AS DECIMAL(18,4)) as lab_results_9,
        TRY_CAST(`Lab-Results@10` AS DECIMAL(18,4)) as lab_results_10,

        CAST(TRY_TO_TIMESTAMP(`Expiration-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as expiration_date,
        TRY_CAST(`Standard-Cost` AS DECIMAL(18,4)) as standard_cost,
        CAST(TRY_TO_TIMESTAMP(`Standard-Cost-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as standard_cost_date,
        TRY_CAST(`Average-Cost` AS DECIMAL(18,4)) as average_cost,
        TRY_CAST(`Last-Cost` AS DECIMAL(18,4)) as last_cost,
        CAST(TRY_TO_TIMESTAMP(`Last-Cost-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_cost_date,
        TRY_CAST(`Replacement-Cost` AS DECIMAL(18,4)) as replacement_cost,
        TRY_CAST(`Selling-Cost` AS DECIMAL(18,4)) as selling_cost,
        NULLIF(TRIM(`Product-Code`), '') as product_code,
        NULLIF(TRIM(`Packaging-Code`), '') as packaging_code,
        NULLIF(TRIM(`Prod-Pkg-Code`), '') as prod_pkg_code,
        IF(UPPER(TRIM(`Display-Item`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Display-Item`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as display_item,
        TRY_CAST(`Weight` AS DECIMAL(18,4)) as weight,
        NULLIF(TRIM(`Weight-UM`), '') as weight_um,
        IF(UPPER(TRIM(`Facility-Display`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Facility-Display`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as facility_display,
        IF(UPPER(TRIM(`Active`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Active`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as active,
        IF(UPPER(TRIM(`FIFO-Available`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`FIFO-Available`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as fifo_available,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyyMMddHH:mm:ss') as created_date_time,
        IF(UPPER(TRIM(`Positive-On-Hand`)) IN ('YES','Y','TRUE','T','1'), TRUE,
        IF(UPPER(TRIM(`Positive-On-Hand`)) IN ('NO','N','FALSE','F','0'), FALSE, NULL)) as positive_on_hand,
        NULLIF(TRIM(`Spare-Char-1`), '') as spare_char_1
from {{ source('bronze', 'prod_pkg_whs_lot') }}
