select
    source_database,

    nullif(trim(`System-ID`), '') as system_id,
    nullif(trim(`Cust-Key`), '') as cust_key,
    nullif(trim(`Cust-ID`), '') as cust_id,
    nullif(trim(`Product-Key`), '') as product_key,
    nullif(trim(`Product-Code`), '') as product_code,
    nullif(trim(`Packaging-Key`), '') as packaging_key,
    nullif(trim(`Packaging-Code`), '') as packaging_code,
    nullif(trim(`Prod-Pkg-Code`), '') as prod_pkg_code,
    nullif(trim(`Internal-Key`), '') as internal_key,
    nullif(trim(`Internal-KeyCV`), '') as internal_keycv,
    nullif(trim(`Project-Num`), '') as project_num,
    nullif(trim(`Cust-Product-Name`), '') as cust_product_name,
    nullif(trim(`Cust-Product-Code`), '') as cust_product_code,
    nullif(trim(`Cust-Stencil-Code`), '') as cust_stencil_code,
    nullif(trim(`Description`), '') as description,
    nullif(trim(`Long-Description`), '') as long_description,
    nullif(trim(`Price-Remark`), '') as price_remark,
    nullif(trim(`Freight-Remark`), '') as freight_remark,
    TRY_CAST(`Current-Price` AS DECIMAL(38,4)) as current_price,
    TRY_CAST(`Future-Price` AS DECIMAL(38,4)) as future_price,
    TRY_CAST(`Discount-1` AS DECIMAL(18,2)) as discount_1,
    TRY_CAST(`Discount-2` AS DECIMAL(18,2)) as discount_2,
    TRY_CAST(`Discount-3` AS DECIMAL(18,2)) as discount_3,
    TRY_CAST(`Allowance-1` AS DECIMAL(38,4)) as allowance_1,
    TRY_CAST(`Allowance-2` AS DECIMAL(38,4)) as allowance_2,
    TRY_CAST(`Allowance-3` AS DECIMAL(38,4)) as allowance_3,
    TRY_CAST(`TVA` AS DECIMAL(38,4)) as tva,
    TRY_CAST(`Demurrage` AS DECIMAL(38,4)) as demurrage,
    TRY_CAST(`Container-Deposit` AS DECIMAL(38,2)) as container_deposit,
    TRY_CAST(`Container-Charge` AS DECIMAL(38,2)) as container_charge,
    nullif(trim(`Currency`), '') as currency,
    nullif(trim(`Price-Code`), '') as price_code,
    nullif(trim(`Price-Group`), '') as price_group,
    nullif(trim(`Price-UM`), '') as price_um,
    nullif(trim(`Price-Type`), '') as price_type,
    nullif(trim(`Price-Schedule-Selection-Basis`), '') as price_schedule_selection_basis,
    nullif(trim(`Sales-Agent-ID`), '') as sales_agent_id,
    TRY_CAST(`Sales-Agent-Commission-Rate` AS DECIMAL(18,2)) as sales_agent_commission_rate,
    TRY_CAST(`Commission-Rate` AS DECIMAL(18,2)) as commission_rate,
    nullif(trim(`Product-Division-Key`), '') as product_division_key,
    TRY_CAST(`Sale-Measure` AS DECIMAL(18,2)) as sale_measure,
    nullif(trim(`Sale-MeasureCV`), '') as sale_measurecv,
    nullif(trim(`Sale-UM`), '') as sale_um,
    nullif(trim(`Sale-Pkg`), '') as sale_pkg,
    TRY_CAST(`Container-Weight` AS DECIMAL(18,2)) as container_weight,
    nullif(trim(`Container-Weight-UM`), '') as container_weight_um,
    nullif(trim(`Return-Packaging-Key`), '') as return_packaging_key,
    TRY_CAST(`Min-Freight-Weight` AS DECIMAL(38,2)) as min_freight_weight,
    nullif(trim(`Freight-Weight-UM`), '') as freight_weight_um,
    TRY_CAST(`Freight-Class-Key` AS DECIMAL(18,0)) as freight_class_key,
    CAST(TRY_TO_TIMESTAMP(`Current-Price-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as current_price_date,
    CAST(TRY_TO_TIMESTAMP(`Future-Price-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as future_price_date,
    CAST(TRY_TO_TIMESTAMP(`Contract-Date-From`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as contract_date_from,
    CAST(TRY_TO_TIMESTAMP(`Contract-Date-To`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as contract_date_to,
    CAST(TRY_TO_TIMESTAMP(`MSDS-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as msds_date,
    CAST(TRY_TO_TIMESTAMP(`Last-Sale-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as last_sale_date,
    CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
    CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
    TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as update_date_time,
    TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
    nullif(trim(`Shelf-Life-Date`), '') as shelf_life_date,
    IF(upper(trim(`Active`)) = 'TRUE', true, IF(upper(trim(`Active`)) = 'FALSE', false, null)) as active,
    IF(upper(trim(`Sales-Taxable`)) = 'TRUE', true, IF(upper(trim(`Sales-Taxable`)) = 'FALSE', false, null)) as sales_taxable,
    IF(upper(trim(`Container-Tracking`)) = 'TRUE', true, IF(upper(trim(`Container-Tracking`)) = 'FALSE', false, null)) as container_tracking,
    IF(upper(trim(`Allow-Excise-Tax`)) = 'TRUE', true, IF(upper(trim(`Allow-Excise-Tax`)) = 'FALSE', false, null)) as allow_excise_tax,
    IF(upper(trim(`Superfund-Taxable`)) = 'TRUE', true, IF(upper(trim(`Superfund-Taxable`)) = 'FALSE', false, null)) as superfund_taxable,
    IF(upper(trim(`CFC-Taxable`)) = 'TRUE', true, IF(upper(trim(`CFC-Taxable`)) = 'FALSE', false, null)) as cfc_taxable,
    IF(upper(trim(`Marine-Taxable`)) = 'TRUE', true, IF(upper(trim(`Marine-Taxable`)) = 'FALSE', false, null)) as marine_taxable,
    IF(upper(trim(`Include-Automated-Print`)) = 'TRUE', true, IF(upper(trim(`Include-Automated-Print`)) = 'FALSE', false, null)) as include_automated_print,
    IF(upper(trim(`GWIS-Ship-Doc-Always-Print`)) = 'TRUE', true, IF(upper(trim(`GWIS-Ship-Doc-Always-Print`)) = 'FALSE', false, null)) as gwis_ship_doc_always_print,
    IF(upper(trim(`Exclude-Price-Change-Letter`)) = 'TRUE', true, IF(upper(trim(`Exclude-Price-Change-Letter`)) = 'FALSE', false, null)) as exclude_price_change_letter,
    nullif(trim(`Raw-Material-Spec-ID`), '') as raw_material_spec_id,
    nullif(trim(`Finished-Good-Spec-ID`), '') as finished_good_spec_id,
    nullif(trim(`CofA-Required`), '') as cofa_required,
    nullif(trim(`CofA-Print-Lot-Image`), '') as cofa_print_lot_image,
    nullif(trim(`Auto-Allocate-Lot-Rule`), '') as auto_allocate_lot_rule,
    TRY_CAST(`Shelf-Life-Percentage` AS DECIMAL(18,0)) as shelf_life_percentage,
    TRY_CAST(`Shelf-Life-Percentage-2` AS DECIMAL(18,0)) as shelf_life_percentage_2,
    TRY_CAST(`Percent-Of-Shelf-Life` AS DECIMAL(18,2)) as percent_of_shelf_life,
    nullif(trim(`User-1`), '') as user_1,
    nullif(trim(`User-Char-1`), '') as user_char_1,
    nullif(trim(`User-Char-2`), '') as user_char_2,
    TRY_CAST(`User-Decimal-1` AS DECIMAL(38,2)) as user_decimal_1,
    TRY_CAST(`User-Decimal-2` AS DECIMAL(38,2)) as user_decimal_2,
    TRY_CAST(`User-Int-1` AS DECIMAL(18,0)) as user_int_1,
    TRY_CAST(`User-Int-2` AS DECIMAL(18,0)) as user_int_2,
    nullif(trim(`Spare-Char-3`), '') as spare_char_3,
    nullif(trim(`Spare-Char-4`), '') as spare_char_4,
    TRY_CAST(`Spare-Decimal-1` AS DECIMAL(38,10)) as spare_decimal_1,
    TRY_CAST(`Spare-Decimal-2` AS DECIMAL(38,10)) as spare_decimal_2,
    TRY_CAST(`Spare-Integer-2` AS DECIMAL(18,0)) as spare_integer_2,
    TRY_CAST(`Spare-Integer-3` AS DECIMAL(18,0)) as spare_integer_3,
    CAST(TRY_TO_TIMESTAMP(`Spare-Date-2`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_2,
    CAST(TRY_TO_TIMESTAMP(`Spare-Date-3`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as spare_date_3,
    nullif(trim(`Sales-Tax-Code`), '') as sales_tax_code,
    nullif(trim(`Purchase-Limit-Group`), '') as purchase_limit_group,
    nullif(trim(`Purchasing-Contact`), '') as purchasing_contact,
    nullif(trim(`Security-Access-2`), '') as security_access_2,
    nullif(trim(`Image-File`), '') as image_file,
    nullif(trim(`Update-by`), '') as update_by,
    nullif(trim(`Update-time`), '') as update_time,
    nullif(trim(`Created-by`), '') as created_by,
    nullif(trim(`Uber-Search`), '') as uber_search
from {{ source('bronze', 'cust_product') }}
