select

        source_database,
        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`Remark-type`), '') as remark_type,
        NULLIF(TRIM(`Remark-Key`), '') as remark_key,
        NULLIF(TRIM(`Remark-sequence`), '') as remark_sequence,
        NULLIF(TRIM(`Remark-sequenceCV`), '') as remark_sequencecv,
        NULLIF(TRIM(`Remark-Data`), '') as remark_data,
        NULLIF(TRIM(`Remark-Font`), '') as remark_font,
        NULLIF(TRIM(`Other-Data`), '') as other_data,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`Old-Remark-Type`), '') as old_remark_type,
        NULLIF(TRIM(`User-2`), '') as user_2,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        TRY_TO_TIMESTAMP(`Update-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as update_date_time,
        NULLIF(TRIM(`Standard-Remark-Key`), '') as standard_remark_key,
        NULLIF(TRIM(`Standard-Remark-Sequence`), '') as standard_remark_sequence,
        NULLIF(TRIM(`Standard-Remark-SequenceCV`), '') as standard_remark_sequencecv,
        NULLIF(TRIM(`Other-Data-2`), '') as other_data_2,
        NULLIF(TRIM(`Other-Data-3`), '') as other_data_3,
        IF(UPPER(TRIM(`Remark-Logical-1`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Remark-Logical-1`)) = 'FALSE', FALSE, NULL)) as is_remark_logical_1,
        IF(UPPER(TRIM(`Remark-Logical-2`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Remark-Logical-2`)) = 'FALSE', FALSE, NULL)) as is_remark_logical_2,
        CAST(TRY_TO_TIMESTAMP(`Remark-Date-1`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as remark_date_1,
        CAST(TRY_TO_TIMESTAMP(`Next-Review-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as next_review_date,
        NULLIF(TRIM(`Display-Remark-Btwn-From-Mth`), '') as display_remark_btwn_from_mth,
        NULLIF(TRIM(`Display-Remark-Btwn-From-Day`), '') as display_remark_btwn_from_day,
        NULLIF(TRIM(`Display-Remark-Btwn-From-Year`), '') as display_remark_btwn_from_year,
        NULLIF(TRIM(`Display-Remark-Btwn-To-Mth`), '') as display_remark_btwn_to_mth,
        NULLIF(TRIM(`Display-Remark-Btwn-To-Day`), '') as display_remark_btwn_to_day,
        NULLIF(TRIM(`Display-Remark-Btwn-To-Year`), '') as display_remark_btwn_to_year,
        CAST(TRY_TO_TIMESTAMP(`Display-Remark-Btwn-Use-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as display_remark_btwn_use_date,
        NULLIF(TRIM(`Spare-Char-1`), '') as spare_char_1
from {{ source('bronze', 'remarks') }}
