select
    source_database,

        NULLIF(TRIM(`System-ID`), '') as system_id,
        NULLIF(TRIM(`product-key`), '') as product_key,
        NULLIF(TRIM(`packaging-key`), '') as packaging_key,
        NULLIF(TRIM(`Facility`), '') as facility,
        NULLIF(TRIM(`Lot-Code`), '') as lot_code,
        NULLIF(TRIM(`Location`), '') as location,
        NULLIF(TRIM(`serial-number`), '') as serial_number,
        NULLIF(TRIM(`int-key`), '') as int_key,
        TRY_CAST(`Amount` AS DECIMAL(38,4)) as amount,
        NULLIF(TRIM(`Unit-of-Meas`), '') as unit_of_meas,
        TRY_CAST(`cost` AS DECIMAL(38,4)) as cost,
        NULLIF(TRIM(`Cost-Table`), '') as cost_table,
        NULLIF(TRIM(`Cost-Type`), '') as cost_type,
        NULLIF(TRIM(`Module-ID`), '') as module_id,
        NULLIF(TRIM(`Pgm-Name`), '') as pgm_name,
        NULLIF(TRIM(`Event-Code`), '') as event_code,
        NULLIF(TRIM(`Code-Value`), '') as code_value,
        NULLIF(TRIM(`Description`), '') as description,
        NULLIF(TRIM(`GL-Acct`), '') as gl_acct,
        TRY_CAST(`Posting-Year` AS DECIMAL(18,0)) as posting_year,
        NULLIF(TRIM(`Posting-YearCV`), '') as posting_yearcv,
        TRY_CAST(`Posting-Period` AS DECIMAL(18,0)) as posting_period,
        NULLIF(TRIM(`Posting-PeriodCV`), '') as posting_periodcv,
        NULLIF(TRIM(`Update-by`), '') as update_by,
        CAST(TRY_TO_TIMESTAMP(`Update-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as update_date,
        NULLIF(TRIM(`Update-time`), '') as update_time,
        NULLIF(TRIM(`Created-by`), '') as created_by,
        CAST(TRY_TO_TIMESTAMP(`Created-date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as created_date,
        NULLIF(TRIM(`Security-Access`), '') as security_access,
        NULLIF(TRIM(`Cost-UM`), '') as cost_um,
        TRY_CAST(`Sequence-1` AS DECIMAL(18,0)) as sequence_1,
        NULLIF(TRIM(`Measure`), '') as measure,
        TRY_CAST(`inv-mult@1` AS DECIMAL(38,4)) as inv_mult_1,
        TRY_CAST(`inv-mult@2` AS DECIMAL(38,4)) as inv_mult_2,
        TRY_CAST(`inv-mult@3` AS DECIMAL(38,4)) as inv_mult_3,
        TRY_CAST(`inv-mult@4` AS DECIMAL(38,4)) as inv_mult_4,
        TRY_CAST(`inv-mult@5` AS DECIMAL(38,4)) as inv_mult_5,
        TRY_CAST(`inv-mult@6` AS DECIMAL(38,4)) as inv_mult_6,
        TRY_CAST(`inv-mult@7` AS DECIMAL(38,4)) as inv_mult_7,
        TRY_CAST(`inv-mult@8` AS DECIMAL(38,4)) as inv_mult_8,
        TRY_CAST(`inv-mult@9` AS DECIMAL(38,4)) as inv_mult_9,
        TRY_CAST(`inv-mult@10` AS DECIMAL(38,4)) as inv_mult_10,
        TRY_CAST(`Trans-Num` AS DECIMAL(18,0)) as trans_num,
        NULLIF(TRIM(`Trans-NumCV`), '') as trans_numcv,
        NULLIF(TRIM(`Product-Code`), '') as product_code,
        NULLIF(TRIM(`Packaging-Code`), '') as packaging_code,
        NULLIF(TRIM(`Prod-Pkg-Code`), '') as prod_pkg_code,
        NULLIF(TRIM(`Display-Item`), '') as display_item,
        NULLIF(TRIM(`Posted-Currency`), '') as posted_currency,
        TRY_CAST(`Posted-Exchange-Rate` AS DECIMAL(18,8)) as posted_exchange_rate,
        IF(UPPER(TRIM(`Posted-to-GL`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-to-GL`)) = 'FALSE', FALSE, NULL)) as posted_to_gl,
        CAST(TRY_TO_TIMESTAMP(`Posted-to-GL-Date`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') AS DATE) as posted_to_gl_date,
        NULLIF(TRIM(`Posted-to-GL-Time`), '') as posted_to_gl_time,
        IF(UPPER(TRIM(`Posted-Summary-Entry`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Posted-Summary-Entry`)) = 'FALSE', FALSE, NULL)) as posted_summary_entry,
        NULLIF(TRIM(`Posted-Journal-Number`), '') as posted_journal_number,
        NULLIF(TRIM(`Posted-Inv-GL-Acct-Ptr`), '') as posted_inv_gl_acct_ptr,
        NULLIF(TRIM(`Posted-Inv-Adjust-GL-Acct-Ptr`), '') as posted_inv_adjust_gl_acct_ptr,
        NULLIF(TRIM(`Posted-Inv-Variance-GL-Acct-Ptr`), '') as posted_inv_variance_gl_acct_ptr,
        TRY_CAST(`Posted-Standard-Cost` AS DECIMAL(38,4)) as posted_standard_cost,
        TRY_CAST(`Trans-ID` AS DECIMAL(18,0)) as trans_id,
        NULLIF(TRIM(`Trans-IDCV`), '') as trans_idcv,
        TRY_CAST(`PPW-OH-Previous-Balance` AS DECIMAL(38,4)) as ppw_oh_previous_balance,
        TRY_CAST(`PPW-OH-Current-Balance` AS DECIMAL(38,4)) as ppw_oh_current_balance,
        NULLIF(TRIM(`PPW-OH-Balance-UM`), '') as ppw_oh_balance_um,
        NULLIF(TRIM(`Year-Period`), '') as year_period,
        TRY_CAST(`Average-Cost` AS DECIMAL(38,4)) as average_cost,
        TRY_CAST(`Old-Average-Cost` AS DECIMAL(38,4)) as old_average_cost,
        TRY_CAST(`New-Average-Cost` AS DECIMAL(38,4)) as new_average_cost,
        TRY_CAST(`Old-QOH` AS DECIMAL(38,4)) as old_qoh,
        TRY_CAST(`New-QOH` AS DECIMAL(38,4)) as new_qoh,
        NULLIF(TRIM(`Cost-File`), '') as cost_file,
        NULLIF(TRIM(`Proj-Num`), '') as proj_num,
        NULLIF(TRIM(`Equipment-Key`), '') as equipment_key,
        NULLIF(TRIM(`Safety-Code`), '') as safety_code,
        NULLIF(TRIM(`Quality-Code`), '') as quality_code,
        NULLIF(TRIM(`Proj-Product-Key`), '') as proj_product_key,
        NULLIF(TRIM(`Trans-Details`), '') as trans_details,
        TRY_TO_TIMESTAMP(`Created-Date-Time`, 'yyyy-MM-dd HH:mm:ss.SSSSSSS') as created_date_time,
        TRY_CAST(`New-Standard-Cost` AS DECIMAL(38,4)) as new_standard_cost,
        TRY_CAST(`New-Last-Cost` AS DECIMAL(38,4)) as new_last_cost,
        IF(UPPER(TRIM(`Update-Cost`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Update-Cost`)) = 'FALSE', FALSE, NULL)) as update_cost,
        NULLIF(TRIM(`Freight-Cost-Accrual-GL-Acct-Ptr`), '') as freight_cost_accrual_gl_acct_ptr,
        TRY_CAST(`Specific-Gravity` AS DECIMAL(18,8)) as specific_gravity,
        NULLIF(TRIM(`Spare-Char-2`), '') as spare_char_2,
        IF(UPPER(TRIM(`Post-Cost-Adjustment`)) = 'TRUE', TRUE,
        IF(UPPER(TRIM(`Post-Cost-Adjustment`)) = 'FALSE', FALSE, NULL)) as post_cost_adjustment,
        TRY_CAST(`Old-Cost` AS DECIMAL(38,4)) as old_cost
from {{ source('bronze', 'inv_transact') }}
