- "System-id"
- "Product-name"
- "Product-code"
- "Product-division-key"
- "Product-key"
- "Description"
- "Long-description"
- "DOT-Name"
- "Cntns"
- "Hazard-Text"
- "Product-class-key"
- "Specific-Gravity"
- "Package-Group"
- "Dft-Packaging-key"
- "Product-Type"
- "UN-code"
- "Packaging-Group"
- "Freight-class"
- "Freight-note"
- "Inv-Amount@1"
- "Inv-Amount@2"
- "Inv-Amount@3"
- "Inv-Amount@4"
- "Inv-Amount@5"
- "Inv-Amount@6"
- "Inv-Amount@7"
- "Inv-Amount@8"
- "Inv-Amount@9"
- "Inv-Amount@10"
- "Inv-Status@1"
- "Inv-Status@2"
- "Inv-Status@3"
- "Inv-Status@4"
- "Inv-Status@5"
- "Inv-Status@6"
- "Inv-Status@7"
- "Inv-Status@8"
- "Inv-Status@9"
- "Inv-Status@10"
- "Inv-Flag@1"
- "Inv-Flag@2"
- "Inv-Flag@3"
- "Inv-Flag@4"
- "Inv-Flag@5"
- "Inv-Flag@6"
- "Inv-Flag@7"
- "Inv-Flag@8"
- "Inv-Flag@9"
- "Inv-Flag@10"
- "Unit-of-Meas"
- "OH-packages"
- "CAS-Number"
- "HMIS-Health-Rating"
- "HMIS-Flammability-Rating"
- "HMIS-Reactivity-Rating"
- "HMIS-Personal-Protection-Rating"
- "SARA-Pure"
- "SARA-Mixture"
- "SARA-Solid"
- "SARA-Liquid"
- "SARA-Gas"
- "DNU-SARA-Immediate"
- "DNU-SARA-Chronic"
- "DNU-SARA-Fire"
- "DNU-SARA-Sudden-Pressure"
- "DNU-SARA-Reactivity"
- "SARA-Storage-Code-Type"
- "SARA-Storage-Code-Temp"
- "SARA-Storage-Code-Pressure"
- "EPA-Waste-Code-1"
- "EPA-Waste-Code-2"
- "EPA-Waste-Code-3"
- "EPA-Waste-Code-4"
- "controlled-substance"
- "section-312"
- "Emergency-Response-Guide"
- "MSDS-Date"
- "C-of-A-Date"
- "superfund-rate"
- "Excise-Tax-Rate"
- "CFC-Rate"
- "Marine-Tax-Rate"
- "Lot-Controlled"
- "Location-Controlled"
- "Serial-Number-Controlled"
- "Update-by"
- "Update-date"
- "Update-time"
- "Created-by"
- "Created-date"
- "Update-Date-Time"
- "User-1"
- "Freight-Class-Key"
- "Sequence-1"
- "DisablePosting"
- "Budget-Amount"
- "Signal-word"
- "Stmt-of-hazard"
- "Precautionary-measures"
- "First-aid-eye"
- "First-aid-skin"
- "First-aid-inhalation"
- "First-aid-ingestion"
- "Components-1"
- "Components-2"
- "Components-3"
- "DOT-hazard-stmnt"
- "RQ"
- "User-2"
- "UM-Conversion-Percentage"
- "NFPA-Health-Rating"
- "NFPA-Flammability-Rating"
- "NFPA-Reactivity-Rating"
- "NFPA-Special-Hazards-Rating"
- "Label-Data-Rev-Date"
- "UM-Conversion-Type"
- "Shelf-Life"
- "Solution-Factor"
- "Receipt-Route"
- "Require-HM-Column"
- "Product-Division"
- "GL-Acct-Ptr"
- "Product-Class"
- "Use-FIFO"
- "User-Logical-2"
- "MSDS-Image-File"
- "User-Char-2"
- "User-Decimal-1"
- "User-Decimal-2"
- "User-Int-1"
- "User-Int-2"
- "Weight"
- "Weight-UM"
- "EHS-Name"
- "Section-313"
- "Component-CAS-Number@1"
- "Component-CAS-Number@2"
- "Component-CAS-Number@3"
- "Component-CAS-Number@4"
- "Component-CAS-Number@5"
- "Component-CAS-Number@6"
- "Component-CAS-Number@7"
- "Component-CAS-Number@8"
- "Component-CAS-Number@9"
- "Component-CAS-Number@10"
- "Component-CAS-Number@11"
- "Component-CAS-Number@12"
- "Component-CAS-Number@13"
- "Component-CAS-Number@14"
- "Component-CAS-Number@15"
- "Component-CAS-Number@16"
- "Component-CAS-Number@17"
- "Component-CAS-Number@18"
- "Component-CAS-Number@19"
- "Component-CAS-Number@20"
- "SARA-EHS-TPQ"
- "CERCLA-311"
- "Other-311"
- "Tax-UM"
- "Tax-Group"
- "Active"
- "Security-Access-2"
- "User-Char-3"
- "User-Logical-3"
- "HMIS-Physical-Hazard"
- "Local-TPQ-UM"
- "Last-Sale-Date"
- "OH-Zero-Date"
- "Local-TPQ"
- "Spare-Decimal-2"
- "Local-Right-To-Know"
- "Quote-Temporary-Product"
- "Spare-Integer-1"
- "Spare-Integer-2"
- "Product-Name-Change"
- "Created-Date-Time"
- "Tariff-Code"
- "Product-Synonym"
- "Spec-Sheet-Image-File"
- "No-CofA-Required"
- "Index-Price-Group"
- "Do-Not-Track-Inventory"
- "Spare-Decimal-3"
- "Location-Storage-Code"
- "Purchase-Limit-Group"
- "Formula-Price-Group"
- "Component-CAS-Percentage@1"
- "Component-CAS-Percentage@2"
- "Component-CAS-Percentage@3"
- "Component-CAS-Percentage@4"
- "Component-CAS-Percentage@5"
- "Component-CAS-Percentage@6"
- "Component-CAS-Percentage@7"
- "Component-CAS-Percentage@8"
- "Component-CAS-Percentage@9"
- "Component-CAS-Percentage@10"
- "Component-CAS-Percentage@11"
- "Component-CAS-Percentage@12"
- "Component-CAS-Percentage@13"
- "Component-CAS-Percentage@14"
- "Component-CAS-Percentage@15"
- "Component-CAS-Percentage@16"
- "Component-CAS-Percentage@17"
- "Component-CAS-Percentage@18"
- "Component-CAS-Percentage@19"
- "Component-CAS-Percentage@20"
- "Auto-Lot-Code-Alias"
- "Contained-Calculate-Factor"
- "Spare-Logical-4"
- "Internal-Use-Image-File"
- "Food-Grade"
- "PH-Flammable"
- "PH-Gas-under-Pressure"
- "PH-Explosive"
- "PH-Self-heating"
- "PH-Pyrophoric-liquid-solid"
- "PH-Pyrophoric-Gas"
- "PH-Corrosive-to-metal"
- "PH-Oxidizer"
- "PH-Organic-peroxide"
- "PH-Self-reactive"
- "PH-Water-emits-flammable-gas"
- "PH-Combustible-Dust"
- "PH-HNOC"
- "HH-Carcinogenicity"
- "HH-Acute-toxicity"
- "HH-Reproductive-toxicity"
- "HH-Skin-Corrosion-Irritation"
- "HH-Respiratory-Skin"
- "HH-Eye-damage-Irritation"
- "HH-Specific-Target-Organ"
- "HH-Aspiration-Hazard"
- "HH-Germ-cell-mutagenicity"
- "HH-Simple-Asphyxiant"
- "HH-HNOC"
- "Uber-Keywords"
- "Uber-Search"
- "PDR"
- "Spare-Char-7"
- "Spare-Char-8"
- "Spare-Char-9"
- "Spare-Logical-5"
- "Spare-Logical-6"
- "Supp-Product-Code"
- "Created-From-ProdCatalog"
- "Spare-Char-10"
- "Spare-Logical-7"
- "Allow-Name-Override"
- "Supplier-ID"
- "Secondary-GHS-Product-Label"
- "Spare-Date-3"
- "Spare-Date-4"
