- "System-ID"
- "Product-Key"
- "Packaging-Key"
- "Inv-Measure"
- "Inv-UM"
- "Inv-Pkg"
- "Weight"
- "Weight-UM"
- "RQ"
- "RQ-UM"
- "Freight-Class"
- "Kit"
- "Standard-Cost"
- "Standard-Cost-Date"
- "Average-Cost"
- "Last-Cost"
- "Last-Cost-Date"
- "Replacement-Cost"
- "Selling-Cost"
- "Inv-Amount@1"
- "Inv-Amount@2"
- "Inv-Amount@3"
- "Inv-Amount@4"
- "Inv-Amount@5"
- "Inv-Amount@6"
- "Inv-Amount@7"
- "Inv-Amount@8"
- "Inv-Amount@9"
- "Inv-Amount@10"
- "Inv-Status@1"
- "Inv-Status@2"
- "Inv-Status@3"
- "Inv-Status@4"
- "Inv-Status@5"
- "Inv-Status@6"
- "Inv-Status@7"
- "Inv-Status@8"
- "Inv-Status@9"
- "Inv-Status@10"
- "Inv-Flag@1"
- "Inv-Flag@2"
- "Inv-Flag@3"
- "Inv-Flag@4"
- "Inv-Flag@5"
- "Inv-Flag@6"
- "Inv-Flag@7"
- "Inv-Flag@8"
- "Inv-Flag@9"
- "Inv-Flag@10"
- "Unit-of-Meas"
- "OH-packages"
- "Old-Product-Number"
- "Dft-Formula-Code"
- "Update-by"
- "Update-date"
- "Update-time"
- "Created-by"
- "Created-date"
- "Update-Date-Time"
- "User-1"
- "Sequence-1"
- "Product-Code"
- "Packaging-Code"
- "Prod-Pkg-Code"
- "Raw-Material-Spec-ID"
- "Finished-Good-Spec-ID"
- "Active"
- "Security-Access-2"
- "Placard-Code"
- "Above-RQ-Shipping-Name"
- "Below-RQ-Shipping-Name"
- "Above-RQ-HM-Flag"
- "Below-RQ-HM-Flag"
- "BOL-Level"
- "DOT-Packaging"
- "Prod-Pkg-Name"
- "Spare-Date-1"
- "Spare-Date-2"
- "Spare-Decimal-1"
- "Spare-Decimal-2"
- "Print-On-Container-Return-BOL"
- "Quote-Temporary-Prod-Pkg"
- "Shelf-Life"
- "Items-Per-Package"
- "Spare-Integer-3"
- "Product-Priority"
- "Created-Date-Time"
- "Product-Status"
- "Packages-Per-Pallet"
- "NMFC-Number"
- "Container-Weight-UM"
- "Container-Weight"
- "International-Shipping-Name"
- "International-HM-Flag"
- "Spare-Logical-3"
- "Spare-Logical-4"
- "Receipt-Route"
- "Location-Storage-Code"
- "Inventory-Alert"
- "MSDS-Date"
- "MSDS-Image-File"
- "Placard-Code-Exception"
- "Uber-Keywords"
- "Uber-Search"
- "DNU-Rental-Class"
- "Product-Image-File"
- "Spare-Integer-4"
- "Created-From-ProdCatalog"
- "Replacement-Price"
- "Is-Exchange-Type"
- "Is-Bulk-Tank"
- "Rental-Class-Key"
- "Rental-Class-KeyCV"
- "Spare-Char-9"
- "Spare-Char-10"
- "Spare-Char-11"
