- "System-ID"
- "Product-Key"
- "Packaging-Key"
- "Facility"
- "Lot-Code"
- "Location"
- "Inv-Amount@1"
- "Inv-Amount@2"
- "Inv-Amount@3"
- "Inv-Amount@4"
- "Inv-Amount@5"
- "Inv-Amount@6"
- "Inv-Amount@7"
- "Inv-Amount@8"
- "Inv-Amount@9"
- "Inv-Amount@10"
- "Inv-Status@1"
- "Inv-Status@2"
- "Inv-Status@3"
- "Inv-Status@4"
- "Inv-Status@5"
- "Inv-Status@6"
- "Inv-Status@7"
- "Inv-Status@8"
- "Inv-Status@9"
- "Inv-Status@10"
- "Inv-Flag@1"
- "Inv-Flag@2"
- "Inv-Flag@3"
- "Inv-Flag@4"
- "Inv-Flag@5"
- "Inv-Flag@6"
- "Inv-Flag@7"
- "Inv-Flag@8"
- "Inv-Flag@9"
- "Inv-Flag@10"
- "Unit-of-Meas"
- "OH-Packages"
- "Serial-Number-Controlled"
- "Update-by"
- "Update-date"
- "Update-time"
- "Created-by"
- "Created-date"
- "Security-Access"
- "User-1"
- "Facility-Type"
- "Internal-Warehouse"
- "Lab-Results@1"
- "Lab-Results@2"
- "Lab-Results@3"
- "Lab-Results@4"
- "Lab-Results@5"
- "Lab-Results@6"
- "Lab-Results@7"
- "Lab-Results@8"
- "Lab-Results@9"
- "Lab-Results@10"
- "Expiration-Date"
- "Product-Code"
- "Packaging-Code"
- "Prod-Pkg-Code"
- "Display-Item"
- "Weight"
- "Weight-UM"
- "Facility-Display"
- "Active"
- "Created-Date-Time"
- "Positive-On-Hand"
